### ISSUE TITLE
Allow installation of PHP 8

### ISSUE THREAD

**Issue by localheinz** [shivammathur/setup-php#104]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to install PHP 8 (https://github.com/php/php-src/tree/master).

**Describe the solution you'd like**

Add version alias `master` or similar, which allowed installing PHP 8 (https://github.com/php/php-src/tree/master).

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by shivammathur** [comment]
Working on this currently.

**Comment by shivammathur** [comment]
@localheinz 
```yml
uses: shivammathur/setup-php@v1
with:
  php-version: '8.0'
```

This will now setup a nightly build `PHP 8.0.0-dev` from the master branch on `ubuntu` and `macOS`.
The build has `JIT` compiler enabled with the following configuration. You can use `ini-values` input to change these values. Refer to this RFC for details - https://wiki.php.net/rfc/jit
```ini
opcache.jit_buffer_size = 256M
opcache.jit = 1235
pcre.jit = 1
```

**Comment by localheinz** [comment]
@shivammathur 

Awesome, thank you!

**Comment by sebastianbergmann** [comment]
@shivammathur Thank you! We (and by that I mean @localheinz) we use this ASAP for PHPUnit's CI pipeline(s).

**Comment by localheinz** [comment]
@shivammathur 

Sorry to bother you, but we've just tried it out in https://github.com/sebastianbergmann/phpunit/pull/3979: looks like PHP 7.3.12 is used:

- https://github.com/sebastianbergmann/phpunit/pull/3979/checks?check_run_id=339672157#step:3:12
- https://github.com/sebastianbergmann/phpunit/pull/3979/checks?check_run_id=339672157#step:8:6

Are we doing it wrong, or are we too early?

**Comment by shivammathur** [comment]
Please quote these versions as GitHub Actions truncates zeros after decimal in inputs.
```
php-version:
  - '7.3'
  - '7.4'
  - '8.0'
```
