### ISSUE TITLE
Sponsor link not working

### ISSUE THREAD

**Issue by htollefsen** [shivammathur/setup-php#108]
Displays the following errormessage:
```
Some errors were encountered when parsing the FUNDING.yml file:

Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
Learn more about formatting FUNDING.yml.
```

One of the provided options not working is github, and I bet they are "enrolled in GitHub Sponsors" ;)

**Comment by shivammathur** [comment]
GitHub sponsors is not available in my country yet. Hope soon
