### ISSUE TITLE
Install prestissimo by default

### ISSUE THREAD

**Issue by georgeboot** [shivammathur/setup-php#12]
Should this package install https://github.com/hirak/prestissimo by default? This is a widely used composer plugin to speed up your installs by a magnitude.

If there is interest, I'm willing to add a PR later today.

**Comment by shivammathur** [comment]
In my testing prestissimo on windows did not help much.
Also this will be integrated in composer 2.0 (composer/composer#5293)

Till 2.0 composer release we can integrate this on `macOS` and `ubuntu` here
Please submit a PR on the `develop` branch.

**Comment by shivammathur** [comment]
@georgeboot Can you give me an ETA on your PR, or I will add this in the next release.

**Comment by shivammathur** [comment]
@georgeboot Thanks for your contribution.
