### ISSUE TITLE
XML extension missing for PHP 7.0

### ISSUE THREAD

**Issue by IchHabRecht** [shivammathur/setup-php#120]
**Describe the bug**
When using ubuntu-18.04 with PHP 7.0 the xml extension doesn't seem to be correctly enabled.

**To Reproduce**
You can find a broken build here https://github.com/IchHabRecht/my_skeleton/runs/350569574
The associated yml file can be found here https://github.com/IchHabRecht/my_skeleton/blob/e5722119639080b445c8550db8a115922e9b165c/.github/workflows/typo3-mysql.yml

**Expected behavior**
The composer installation for "🏃 tests with TYPO3 "^8.7" and PHP 7.0" should be executed without any error.

**Additional context**
Switching to ubuntu-16.04 everything runs as expected (https://github.com/IchHabRecht/my_skeleton/runs/350584548).

**Comment by shivammathur** [comment]
Now `xml` should be available when mentioned in `extensions` input.
Here is a [test workflow](https://github.com/shivammathur/test-setup-php/commit/dfe27df9aa3b23b877b00be2e6f80170acef821e/checks?check_suite_id=361510131)
```yml
uses: shivammathur/setup-php@v1
with:
  php-version: '7.0'
  extensions: xml
```

**Comment by IchHabRecht** [comment]
Thank you for this really fast support!
