### ISSUE TITLE
INTL php extension take very long time to install

### ISSUE THREAD

**Issue by Mystraht** [shivammathur/setup-php#130]
Hello,

When I run setup-php action with INTL extension, it take +1 minute more than without.
The total duration is 1m41s, which is really slow.

![image](https://user-images.githubusercontent.com/8995312/71372522-ea17f100-25b4-11ea-884e-dcd89de2f2f7.png)

Without INTL the step duration is OK.

Do you have any idea to resolve this problem? It looks like other extensions I use are already installed?

**Comment by shivammathur** [comment]
It takes the time it need to install `intl` extension using
```bash
apt-get install php7.1-intl
```
There is an issue requesting to pre-install `intl` extension on GitHub Actions - actions/virtual-environments#3 
So this will improve when this issue gets resolved.
