### ISSUE TITLE
Windows - PHP 7.4.1 not available on Windows

### ISSUE THREAD

**Issue by julien-boudry** [shivammathur/setup-php#132]
**Describe the bug**
PHP 7.4.1 is not available on Windows. Working on Unbuntu.

**To Reproduce**
https://github.com/julien-boudry/Condorcet/blob/dev-2.1/.github/workflows/execute_all_tests.yml

**Additional context**
7.4.1 fixes many important bugs, especially on Windows (Notably the fact that interactive shells don't work at all).

**Comment by shivammathur** [comment]
@julien-boudry Patched. Will be available in next release.

**Comment by shivammathur** [comment]
@julien-boudry 
Now `php-version: '7.4'` on windows will setup `PHP 7.4.1`
```yml
uses: shivammathur/setup-php@v1
with:
  php-version: '7.4'
```
