### ISSUE TITLE
intl Could not install intl on PHP 7.3.12

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#136]
**Describe the bug**
sporadically we see issues, that the `intl` extension could not be installed.
it seems this happens from time to time and is not 100% reproducible.

because of the then missing intl extension the build is not stable and our php static analysis tools run into "normalizer" class not found errors

**To Reproduce**
Please provide the GitHub Action `.yml` file:
https://github.com/redaxo/redaxo/blob/master/.github/workflows/push.yml

we see it in e.g. https://github.com/redaxo/redaxo/pull/3090/checks?check_run_id=372438603

**Expected behavior**
the intl extension should get installed properly 

**Screenshots**
example of a psalm build which errors.

![grafik](https://user-images.githubusercontent.com/120441/71730645-07657e80-2e43-11ea-906f-e230881c5d70.png)

we can see similar problems on phpstan builds.

**Comment by shivammathur** [comment]
Please reproduce this using the verbose tag `shivammathur/setup-php@verbose`.
I tested it twice and it installs `ext-intl` without any errors.
Test using `v1` - https://github.com/shivammathur/test-setup-php/runs/372664018
Test using `verbose` - https://github.com/shivammathur/test-setup-php/runs/372668523

**Comment by shivammathur** [comment]
I will close this, let me know if this occurs again, most likely this was a network issue while downloading the intl package file from `launchpad.net` servers and in such cases restarting the workflow should solve it.

**Comment by staabm** [comment]
We had this problem at least 10 times in the last 14 days.. I will report back

**Comment by shivammathur** [comment]
ok
