### ISSUE TITLE
narrowspark/automatic-composer-prefetcher as a alternative to prestissimo

### ISSUE THREAD

**Issue by prisis** [shivammathur/setup-php#137]
**Is your feature request related to a problem? Please describe.**
I want to provide a more feature richt alternative to prestissimo
unlike hirak/prestissimo, it doesn't require the curl extension and has zero extra dependencies. Instead, it reuses the existing code infrastructure in Composer to download packages.

And it has support for skipping legacy package tags, to reduce the resolve time on package finding in composer.

**Describe the solution you'd like**
adding automatic-composer-prefetcher to the tools options

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/narrowspark/automatic-composer-prefetcher

**Comment by shivammathur** [comment]
Merged #138

**Comment by shivammathur** [comment]
@prisis Let me know, when you upgrade `narrowspark/automatic-composer-prefetcher` to work with composer 2. Currently I have fixed composer's version to v1 when this plugin is specified.

**Comment by prisis** [comment]
Will do
