### ISSUE TITLE
Unclear coverage options

### ISSUE THREAD

**Issue by simPod** [shivammathur/setup-php#140]
There are 3 options for coverage:

- xdebug
- pcov
- none

1) What's the default? Seem's like xdebug is by default on when nothing is specified, is that correct behaviour? I'd not expect to have xdebug enabled by default.
2) Considering xdebug is not default it could then be reduced only to `xdebug` and `pcov`, `none` would be redundant.
3) What are the versions of xdebug nad pcov used by this action?

**Comment by shivammathur** [comment]
`Xdebug` is installed by default on GitHub Actions in `ubuntu`. [Please see](https://github.com/actions/virtual-environments/blob/95954b3f022a1c4626d112bd4fe82d0812fa6f4b/images/linux/scripts/installers/1804/php.sh#L173)

On `macOS` and `windows` Xdebug is not installed by default.

So the coverage input provides uniform end result across OS. 
- `coverage: xdebug` - Will setup Xdebug
- `coverage: pcov` - Will setup PCOV, removes `Xdebug`
- `coverage: none` - Removes both `Xdebug` and `PCOV`

**Comment by simPod** [comment]
@shivammathur Ah, now I get it. Thanks for the link, that explains it. I expected the runner to be more pure and thought it's rather issue in this action.
