### ISSUE TITLE
phpunit timeouts

### ISSUE THREAD

**Issue by nWidart** [shivammathur/setup-php#146]
**Describe the bug**
On the following setup:

```
 Set up job2s
Download action repository 'shivammathur/setup-php@master'
Current runner version: '2.160.2'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'shivammathur/setup-php@master'
```
Everything was running as expected.

However on:
```
Current runner version: '2.163.1'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v1'
Download action repository 'shivammathur/setup-php@master'
```
phpunit is timing out:
```
  [Symfony\Component\Process\Exception\ProcessTimedOutException]                                       
  The process "vendor/bin/phpunit -vvv --coverage-html coverage" exceeded the timeout of 300 seconds.  
```

**To Reproduce**
The actions file: https://github.com/nWidart/laravel-modules/blob/master/.github/workflows/php.yml

**Expected behavior**
The tests to pass, without timeouts. Locally they run.

**Additional context**
A failing build: https://github.com/nWidart/laravel-modules/commit/2e12c6149028b4e6bf4dd185330b129ea7fa6228/checks?check_suite_id=396488927

A successful build: https://github.com/nWidart/laravel-modules/commit/4151f9f42887524783385dce0f5bf8735b6b73a3/checks?check_suite_id=324493157

I'm not sure what could cause this. I've seen I could increase the timeout config but that wouldn't really solve the root cause.

Thank you,

**Comment by shivammathur** [comment]
Yes composer has a timeout limit of 300s.
You can disable it using any method given [here](https://github.com/composer/composer/blob/master/doc/articles/scripts.md#writing-custom-commands)

For example
```yml
- name: Run test suite
  run: |
    export COMPOSER_PROCESS_TIMEOUT=0
    composer run-script test-coverage
```

**Comment by nWidart** [comment]
Thanks I did that, but tests still take ~15minutes to run vs 4 before, and 3 in travis.

**Comment by shivammathur** [comment]
The `Xdebug` version in your GitHub Action run is `2.8.1`. It should be `2.9.0`.
It seems that old `ubuntu` runner image is being loaded for your repository which had the old version.

Please add this step before the test step as a temporarily workaround.
```yml
- name: Upgrade Xdebug
  run: sudo DEBIAN_FRONTEND=noninteractive apt install php-xdebug
```

Tests would finish in around a minute then. Here is a [test run](https://github.com/shivammathur/test-setup-php/commit/bcb6fdb7043a1720df2d9e7ec7c22c74b898324d/checks?check_suite_id=396633930)

**Comment by nWidart** [comment]
Oh ok weird. Added the step but it didn't install the latest version saying
```
php-xdebug is already the newest version (2.8.1+2.5.5-1+ubuntu18.04.1+deb.sury.org+1).
```

- [new build](https://github.com/nWidart/laravel-modules/commit/3112643550fed25964b4b34dc1810a1edd8c4271/checks?check_suite_id=396651659)

When looking at the travis logs, it runs `Xdebug 2.7.2`, that run finishes in [2min52](https://travis-ci.org/nWidart/laravel-modules/jobs/636079610?utm_medium=notification&utm_source=github_status).

**Comment by shivammathur** [comment]
@nWidart 
Submitted a PR with the fix nWidart/laravel-modules#901

**Comment by nWidart** [comment]
Thank you very much! 2m 53s for that build!

Thanks again. 👌

**Comment by shivammathur** [comment]
@nWidart 
Now you can remove the workaround `Xdebug` update step. It will be updated by the action if an older version is installed. 
Also the `process-timeout` limit in `composer` is set to 0 by the action, so you can remove that as well if you want.

**Comment by nWidart** [comment]
Thanks, removed the custom config and the workflow is still fast. 👍
