### ISSUE TITLE
PHP NTS support on Windows

### ISSUE THREAD

**Issue by sergeyklay** [shivammathur/setup-php#153]
Hello,

Are there any plans to provide PHP Non-Thread Safe (NTS) support? Right now we can't create a full featured build matrix due to PHP Thread Safe (TS) limitation.

Thank you

**Comment by shivammathur** [comment]
On `ubuntu` and `macos` all `NTS` versions are setup, on windows the builds are `TS` version are setup. Do you want `NTS` versions on windows.

**Comment by sergeyklay** [comment]
Yes, I need NTS version on Windows as well as TS

**Comment by ruudboon** [comment]
@shivammathur Is there an easy way to temporary workaround this and have NTS on windows?

**Comment by shivammathur** [comment]
@ruudboon Not with current code. Will add support in 1.7.4 for windows builds

**Comment by ruudboon** [comment]
@shivammathur That would be awesome. thnx

**Comment by ruudboon** [comment]
Btw. Looks like on 7.4 NTS is installed. https://github.com/ruudboon/cphalcon/runs/399772237#step:13:30

**Comment by shivammathur** [comment]
Yes the default version on the runner is `nts`, after 1.7.4 `nts` will be installed on all versions by default and you will be able to specify `ts` or `nts` in an environment variable named `PHPTS`.

[test workflow](https://github.com/shivammathur/test-setup-php/commit/69790986e290d57faaca58e9f97fe36a06c59a99/checks?check_suite_id=410647777), [test yml](https://github.com/shivammathur/test-setup-php/blob/69790986e290d57faaca58e9f97fe36a06c59a99/.github/workflows/test.yml)

**Comment by ruudboon** [comment]
Awesome. Can’t wait for the release to test it out

**Comment by ruudboon** [comment]
@shivammathur works nicely! Tested it on your devel branch.

**Comment by shivammathur** [comment]
Released `1.7.4` 🚀 
Please test using `v1` and let me know.

**Comment by ruudboon** [comment]
Running now :D https://github.com/phalcon/cphalcon/pull/14729/checks?check_run_id=401721776
Tests are failing. We're still working on that.
