### ISSUE TITLE
Add Symfony CLI suport

### ISSUE THREAD

**Issue by Aerendir** [shivammathur/setup-php#158]
Symfony CLI is a command line tool that makes possible to execute a lot of useful thing with Symfony and PHP development in general.

Among other things, ne is really useful in CI: `symfony security:check` command.

It checks that the `composer.json` deps are free of security vulnerabilities.

Originally this command was provided by `sensiolabs/security-checker` but now it is incorporated into Symfony CLI (https://github.com/sensiolabs/security-checker/issues/132#issuecomment-448673498 and https://github.com/sensiolabs/security-checker/pull/144/files#diff-04c6e90faac2675aa89e2176d2eec7d8R8-R13).

Here the installation info: https://symfony.com/download

**Comment by prisis** [comment]
I can provide you a alternative to `sensiolabs/security-checker` https://github.com/narrowspark/automatic-security-audit this is a composer plugin that runs on every composer install/update and shows if some security vulnerabilities, its use the same base like `sensiolabs/security-checker` + `Github security advisories db` so more up to date.

https://github.com/narrowspark/security-advisories this is the data source for automatic-security-audit

**Comment by Aerendir** [comment]
@prisis , thank you for the suggestion: I'll try it 💪
Anyway I think I will stay with the Sensio/Symfony tool as I run it on demand and in CI: this makes me more focused on the current task, instead of distracting me with alerts about outdated dependencies.

**Comment by shivammathur** [comment]
@Aerendir Added in `1.8.0`.

**Comment by Aerendir** [comment]
@shivammathur , many many thank you! I will update my workflows to test it!
