### ISSUE TITLE
Msgpack fails under 7.4

### ISSUE THREAD

**Issue by ruudboon** [shivammathur/setup-php#159]
The stable version of msgpack isn't 7.4 compatible and causing an install failure.

https://github.com/phalcon/cphalcon/runs/404587434#step:10:12

Suggesting to use the beta version for the time being.
https://pecl.php.net/package-changelog.php?package=msgpack&release=2.1.0beta1

**Comment by shivammathur** [comment]
@ruudboon You can now setup the beta version using `msgpack-beta`.

**Comment by ruudboon** [comment]
Still seeing issues using windows and osx. 
Windows
https://github.com/phalcon/cphalcon/runs/409735154?check_suite_focus=true#step:4:32
Osx
https://github.com/phalcon/cphalcon/runs/409729174?check_suite_focus=true#step:3:24
