### ISSUE TITLE
Add cs2pr support

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#161]
I recently published a tiny little script which allows to add github pull request annotations based on checkstyle formatted error reports.

see e.g.

![image](https://user-images.githubusercontent.com/120441/73077239-17abcf00-3ec0-11ea-899b-6c02f75976b8.png)

this is usefull in combination with phpstan, psalm, php-cs-fixer or any other tool which supports the checkstyle format.

my tool is only usefull in github actions context and I guess will mostly be used in the php world.

what do you think about bunling the script with this great setup-php github action?
that way people could use the script very easily.

what do you think?

https://github.com/staabm/annotate-pull-request-from-checkstyle

**Comment by shivammathur** [comment]
I will add this, what do you think about packaging it as `phar` archive and adding that to releases.

Also how does cs2pr work with already existing support for problem matchers for PHPUnit.
https://github.com/shivammathur/setup-php#problem-matchers
Does this create duplicate annotations when used together.

**Comment by staabm** [comment]
> I will add this, what do you think about packaging it as `phar` archive and adding that to releases.

not sure if this has a benefit. the script actual is a single file:
https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/master/cs2pr

do you see any advantages of having it as a phar?


> Also how does `cs2pr` work with already existing support for problem matchers for `PHPUnit`.

phpunit is not supported, because it does not support the checkstyle format.

I have already discussed it with sebastian, but he does not like the idea of having checkstyle-reports in phpunit:
https://github.com/sebastianbergmann/phpunit/issues/3162#issuecomment-577766003

there is a small tool though, which brings the same functionality with phpunit
https://github.com/mheap/phpunit-github-actions-printer

> [shivammathur/setup-php#problem-matchers](https://github.com/shivammathur/setup-php#problem-matchers)
> Does this create duplicate annotations when used together.

never heared of this feature.. this sounds interessting.. maybe phpunit-github-actions-printer is not required then.

how does this problem-matcher work? what content is expected in phpunit.json ? how to produce this file?

**Comment by shivammathur** [comment]
ok. I checked the script, I agree it does not need to packages as `phar`. But please add it as an asset to the releases. Then it will be easy for me to add support for this in [`tools`](https://github.com/shivammathur/setup-php#wrench-tools-support) input.

Creating annotations in GitHub Actions requires a `json` file which has regex matching the output.
It can be added using `run: echo "::add-matcher::path/to/json"`

Here is the [json file](https://github.com/shivammathur/setup-php/blob/master/src/configs/phpunit.json) for creating annotations for `PHPUnit`.
This file is copied to `${{ runner.tool_cache }}` directory by the action and can be used as described [here](https://github.com/shivammathur/setup-php#problem-matchers)

This comments explains each regex in the json file - https://github.com/shivammathur/setup-php/pull/84#issuecomment-560372992

**Comment by tristanbes** [comment]
It would be a HUGE improvement; ❤️

**Comment by staabm** [comment]
> Creating annotations in GitHub Actions requires a `json` file which has regex matching the output.
> It can be added using `run: echo "::add-matcher::path/to/json"`
> 
> Here is the [json file](https://github.com/shivammathur/setup-php/blob/master/src/configs/phpunit.json) [](/shivammathur/setup-php/blob/HEAD@{2020-01-24T17:42:22Z}/src/configs/phpunit.json)

thx for the additional info. wasnt aware that problem matches are a thing.

> ok. I checked the script, I agree it does not need to be packaged as `phar`. But please add it as an asset to the releases. Then it will be easy for me to add support for this in [`tools`](https://github.com/shivammathur/setup-php#wrench-tools-support) input.

just added the cs2pr file to the 1.0 release. can you work with that or do you need more?

https://github.com/staabm/annotate-pull-request-from-checkstyle/releases/tag/1.0

**Comment by shivammathur** [comment]
@staabm Thanks. will add support in next release.

**Comment by tristanbes** [comment]
If possible, provide some example @shivammathur in the documentation;

Thank you guys about this.

**Comment by shivammathur** [comment]
@staabm Now you can specify `cs2pr` in `tools` input. See [here](https://github.com/shivammathur/setup-php#other-tools) for an example.

**Comment by staabm** [comment]
Thank you

**Comment by staabm** [comment]
works like a charm <2. thanks again
