### ISSUE TITLE
Phpunit problem matcher

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#163]
Using the phpunit problem matcher as described in the readme reports annotations when tests are skipped.

This shouldnt be reported as a error though

![B1A42BD7-AC25-4EDC-A07E-9501E55EFA14](https://user-images.githubusercontent.com/120441/73123214-e39edf80-3f8d-11ea-8426-b38325c8f33c.png)

See example: https://github.com/rectorphp/rector/pull/2757/files

**Comment by staabm** [comment]
Ohh the problem actually occurs, because phpunit was running in verbose mode.

I guess  we should just document that

**Comment by shivammathur** [comment]
Fixed this in 8e5cc09. Now only failed tests will create annotations.
Will be part of next release `1.8.0`.
Will close #165
