### ISSUE TITLE
Php problem matcher

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#166]
Just an idea: would it make sense the action would auto add a problem matcher for php-src native warnings/errors?

Inspired by the matcher which get registered by the checkout action for git errors
![72218789-105A-4DDF-B0A7-3CDBDABBFBAA](https://user-images.githubusercontent.com/120441/73134720-24ecc900-403a-11ea-9cdd-8f8b121cc0ab.jpeg)

**Comment by korelstar** [comment]
I've written a problem matcher for `php -l`: https://github.com/marketplace/actions/phplint-problem-matcher

Is this what you mean? Maybe this can be integrated into `setup-php` action.

**Comment by shivammathur** [comment]
@korelstar Thanks will check this, does your action work correctly with different types like warnings, notices and errors.

**Comment by korelstar** [comment]
I'm not sure if `php -l` has different error levels. It's a syntax checker, so I don't think so. Do you have an example?

Maybe we have a misunderstanding. My problem matcher is for use with PHP's integrated syntax checker (`php -l` or `php --syntax-check`) only. It's not about runtime errors.

**Comment by staabm** [comment]
My initial request was about adding a problem matcher which will detect errors/warnings emitted by a php script beeing executed by the regular php interpreter. 

Yours is also interesting though a different use case :-)

**Comment by shivammathur** [comment]
@korelstar This issue is for runtime errors, so the solution has to handle different error types.
@staabm I have added this to `v2` and will be part of the release.

**Comment by korelstar** [comment]
Okay, thanks for clarification. Then, I misunderstood this.

**Comment by shivammathur** [comment]
@korelstar This will also cover the `php -l` errors as the format is same.

**Comment by shivammathur** [comment]
@staabm @korelstar Added support for PHP problem matchers - https://github.com/shivammathur/setup-php#problem-matchers
