### ISSUE TITLE
Support PHP 5.3, 5.4 and PHP 5.5

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#169]
Yii framework 2.0 and 1.1 have to support old versions of PHP. We've switched to GitHub actions (thanks to this project 👍) but are missing test runs for 5.4 and 5.5.

Would be great to have 5.4 and 5.6 officially supported.

**Comment by localheinz** [comment]
If we did, then we we could also add PHP 5.3 so `composer/composer` could switch over to using GitHub Actions.

That is, if @naderman, @seldaek, and @alcohol are interested.

**Comment by Seldaek** [comment]
Interested in principle yes, but haven't had time to play with it yet so not sure of the benefits vs travis (which tbh works quite well for us right now). If it's just gonna generate work to migrate for no gain then rather not :)

**Comment by localheinz** [comment]
@Seldaek 

I'd be happy to assist with switching over, and personally, I would highly recommend it.

**Comment by samdark** [comment]
@Seldaek almost no queue wait time, up to 25 parallel workers. For us it decreased feedback time more than 3 times.

**Comment by shivammathur** [comment]
@samdark @localheinz Added support for old PHP versions in `v2`. Let me know if there are any issues
https://github.com/shivammathur/setup-php#tada-php-support

`v2` features and changes - https://github.com/shivammathur/setup-php/pull/177

**Comment by localheinz** [comment]
@shivammathur 

Thank you for your work!
