### ISSUE TITLE
Support 7.4.2

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#170]
When specifying `7.4` as version, it installs `7.4.1` instead of `7.4.2`. Can this be bumped?

**Comment by shivammathur** [comment]
After 2.0.0. There will be a update input which will update to the latest patch. Currently on linux it does not update if for example 7.4.1 is found on the runner for 7.4.

**Comment by prisis** [comment]
So if you try 7.4.2 as version the 7.4.1 version is found, can i help you to get this fixed?

**Comment by shivammathur** [comment]
@prisis This can be done currently by adding a step after `setup-php` with `sudo apt-get update php7.4`. In v2 as I said, I will add an input `update`, when true it will update to the latest patch.

**Comment by shivammathur** [comment]
@ruudk @prisis Now the version on the runner is `7.4.2`

**Comment by shivammathur** [comment]
@ruudk @prisis 
Now you can force update to latest patch release
https://github.com/shivammathur/setup-php#force-update

**Comment by ruudk** [comment]
Thanks, will this slow down the builds?

**Comment by shivammathur** [comment]
Currently the latest release `7.4.2` is on the runner, so this is not useful. When the next version is released you can use this. It will take extra time then to update the version.

I would advise to use this only if the patch release has fixes which affect your project. It takes GitHub around 1-2 weeks to update the version on the runner after the release, so it is up to you if you want to wait or force update. The option is there now.
