### ISSUE TITLE
Installing Swoole, Grpc and protobuf extension is very slow with pecl

### ISSUE THREAD

**Issue by Webonaute** [shivammathur/setup-php#174]
Is it possible to add precompile Swoole, Grpc and protobuf extension?

**Comment by shivammathur** [comment]
@Webonaute in v2, you will be able to cache these extensions.

**Comment by Webonaute** [comment]
I know I could workaround with ci-pecl-install but I dont know how to configure the cache for that. 
in travis it would be simply : 
```
cache:
  directories:
    - $HOME/pecl_cache
```

**Comment by shivammathur** [comment]
Currently it a bit complicated to do this on GitHub actions, please wait for the `v2` which is the next release. I will document this

**Comment by shivammathur** [comment]
Now you can cache the extensions using `v2`
https://github.com/shivammathur/setup-php#cache-extensions

On first run extensions are installed and cached. On subsequent runs the cached extensions are enabled and will reduce the workflow time.
As per my testing It should reduce the time from 13-15 min down to around a minute or less.

Example workflow - https://github.com/shivammathur/test-setup-php/actions/runs/40407239/workflow

**Comment by Webonaute** [comment]
is it possible this is not working with tag? example :
```
name: Release Cycle
on:
  push:
    tags:
      - '*'

jobs:
  releasing:
    name: Releasing ${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3']
    env:
      extensions: mbstring, xml, ctype, iconv, mysql, curl, phar, json, gd, igbinary, intl, mysql, zip, swoole, grpc, protobuf
      key: extension-cache-v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMPOSER_GIT_HUB_TOKEN }}
      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}
      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          tools: pecl
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: none
`
``

**Comment by shivammathur** [comment]
@Webonaute currently for tags it does not work as each tag is a different ref and caches are not available across refs.

A workaround for this is to add this workflow on master branch with push event which then would cache the extensions. Master branch's cache would then be available for tag workflows.

I have created a issue to solve this - actions/cache#194
