### ISSUE TITLE
Cannot sponsor the project

### ISSUE THREAD

**Issue by romainnorberg** [shivammathur/setup-php#179]
**Describe the bug**
Cannot sponsor the project, there is an error

**To Reproduce**
Click on top-button "Sponsor"

**Expected behavior**
Donate

**Screenshots**
![Screenshot 2020-02-17 at 10 33 22](https://user-images.githubusercontent.com/7681951/74641167-2610a200-5171-11ea-8761-010b32dddc1e.jpg)

**Additional context**
/

**Comment by shivammathur** [comment]
GitHub Sponsor is not available in my country yet. Please use paypal to contribute. Thanks
