### ISSUE TITLE
PHP 5.5 with MySQL extension

### ISSUE THREAD

**Issue by simialbi** [shivammathur/setup-php#182]
**Describe the bug**
If you use PHP 5.5 with mysql extension there always is an error:
https://github.com/simialbi/yii2/runs/450521777?check_suite_focus=true

**To Reproduce**
https://github.com/simialbi/yii2/blob/master/.github/workflows/tests.yml

**Expected behavior**
Installation of mysql extension like in all other versions

**Screenshots**
![image](https://user-images.githubusercontent.com/3023342/74662628-94b62580-519a-11ea-8ef8-e6a1df7d6cdf.png)

**Additional context**
(none)

**Comment by shivammathur** [comment]
@simialbi Fixed, now `mysql` extensions should install correctly on PHP 5.5

**Comment by simialbi** [comment]
Thank you. Keep up the very good work!
