### ISSUE TITLE
PHP 5.5 works, but is really slow

### ISSUE THREAD

**Issue by simialbi** [shivammathur/setup-php#183]
**Describe the bug**
PHP 5.5 installation is extremly slow (3 times slower than 5.4), see:
https://github.com/simialbi/yii2/runs/452929598?check_suite_focus=true

**To Reproduce**
https://github.com/simialbi/yii2/blob/update-github-action/.github/workflows/tests.yml

**Expected behavior**
Nerby same speed as other versions

**Screenshots**
![image](https://user-images.githubusercontent.com/3023342/74752543-22634500-526f-11ea-995f-5895b8d99df7.png)
![image](https://user-images.githubusercontent.com/3023342/74752564-2b541680-526f-11ea-88d6-02d96543405f.png)

**Additional context**
(none)

**Comment by shivammathur** [comment]
@simialbi Fixed in #184 and shivammathur/php5-ubuntu@028ec7f.

Also please replace `sqlite` with `sqlite3` in your workflow.

**Comment by shivammathur** [comment]
@simialbi Both `5.4` and `5.5` builds should be under a minute now.
Here is a test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/41566981
