### ISSUE TITLE
Add support for WP-CLI as a tool.

### ISSUE THREAD

**Issue by kidunot89** [shivammathur/setup-php#187]
**Is your feature request related to a problem? Please describe.**
I need **[WP-CLI](https://wp-cli.org)** to be in the `bin` for [this](https://github.com/kidunot89/wp-graphql/blob/feature/github-workflows/.github/workflows/schema-linter.yml) workflow 

**Describe the solution you'd like**
Add the **wp-cli.phar** as **wp** in the `bin`.

**Describe alternatives you've considered**
I made [this](https://github.com/kidunot89/wp-cli-github-action) action ~ It didn't work :cry: 

**Additional context**
I've already devised a solution. See #188 .

**Comment by shivammathur** [comment]
@kidunot89 Released in `2.1.0`
