### ISSUE TITLE
Not recognizes extensions of php to install

### ISSUE THREAD

**Issue by IgorDePaula** [shivammathur/setup-php#19]
I try using to test laravel app, with pnctl and intl, but not recognizes from yesterday. =/

![Captura de tela de 2019-09-18 18-27-10](https://user-images.githubusercontent.com/2833993/65187306-ff273600-da41-11e9-9de3-9380d3da7b2a.png)
![Captura de tela de 2019-09-18 18-26-53](https://user-images.githubusercontent.com/2833993/65187307-ff273600-da41-11e9-949c-37f3e3f4472d.png)
![Captura de tela de 2019-09-18 18-26-21](https://user-images.githubusercontent.com/2833993/65187308-ff273600-da41-11e9-9930-911cdf743d4b.png)
![Captura de tela de 2019-09-18 18-26-08](https://user-images.githubusercontent.com/2833993/65187310-ff273600-da41-11e9-8198-f6b5b8f79113.png)

**Comment by shivammathur** [comment]
Fixed in #20 
Test Run - https://github.com/shivammathur/test-setup-php/commit/14ca2de4931063908762cfd9d8904c6a08919867/checks

Workflow - https://github.com/shivammathur/test-setup-php/blob/14ca2de4931063908762cfd9d8904c6a08919867/.github/workflows/test.yml

**Comment by IgorDePaula** [comment]
Now works fine.

Thank you very much.
