### ISSUE TITLE
Blackfire php-ext support

### ISSUE THREAD

**Issue by jaapio** [shivammathur/setup-php#191]
I would like to simplify the setup of my workflow that is using blackfire.io to profile my libraries. And since I'm already using this nice project to setup PHP in my workflow it would be very nice if we could add Blackfire as a supported extension. 

The Blackfire extension is supported on Windows, Linux, and OSX, so it could be part of this package to support the installation. I would understand if you are denying this request because Blackfire is a commercial product that is not free to use.

If you would accept this as a PR I will start implementing the installation on all operating systems with the required scripts.

**Comment by shivammathur** [comment]
I would love to see the PR.

**Comment by shivammathur** [comment]
@jaapio
Released blackfire support in `2.1.0`.
Also added support for `blackfire-agent` and `blackfire-player` tools.
