### ISSUE TITLE
Installs composer prerelease

### ISSUE THREAD

**Issue by ChristophWurst** [shivammathur/setup-php#192]
**Describe the bug**
We use this action to check for changes in vendored composer files when Dependabot pushes its PRs. This worked well but broke a few days ago. Some debugging has shown that the produced autoloading files are different locally versus the ones from the action. I narrowed it down to be an issue with a composer version mismatch. This action currently pulls the [1.10.0-RC](https://github.com/composer/composer/releases/tag/1.10.0-RC). Is there a way to prevent the installation of a prerelease?

**To Reproduce**
Our public repo with a failing check at https://github.com/nextcloud/3rdparty/pull/409

**Expected behavior**
Action installs latest *stable* composer binary.

**Screenshots**
N/a

**Additional context**
N/a

Cheers :v:

**Comment by shivammathur** [comment]
@ChristophWurst 
You can fix the `composer self-update` command permission error by prefixing it with `sudo`. update will switch it to stable.
```bash
sudo composer self-update
```

**Comment by ChristophWurst** [comment]
Yep, that does the trick for us. Thanks a lot. I was under the impression composer would complain when run as root.

**Comment by shivammathur** [comment]
@ChristophWurst After `2.1.0` release, stable version of composer will be setup and will not require sudo for any composer commands.

**Comment by ChristophWurst** [comment]
Cool, thanks a lot :heart:
