### ISSUE TITLE
PHP 5.3, 5.4 and 5.5 are failing composer

### ISSUE THREAD

**Issue by heddn** [shivammathur/setup-php#197]
**Describe the bug**
SSL errors from composer in older versions of PHP: https://github.com/drupal/php-signify/runs/479862575?check_suite_focus=true

I believe it was the ones recently added in https://github.com/shivammathur/setup-php/issues/169. When I first started implementing that project using php 5.3, it was working fine. So something has happened in the past week to break things.

**To Reproduce**
https://github.com/drupal/php-signify/blob/master/.github/workflows/php.yml

**Expected behavior**
It used to work. I expect it should work.

**Screenshots**
n/a

**Additional context**
It started to fail recently.

**Comment by shivammathur** [comment]
After 2.1.1 release, composer should with PHP 5.3 and 5.4 on `macOS` and your workflow should run successfully.
