### ISSUE TITLE
Add support for nikic/php-ast extension

### ISSUE THREAD

**Issue by drupol** [shivammathur/setup-php#198]
Hi,

I'm publishing a PHP package: [loophp/phptree](https://github.com/loophp/phptree).
I'm using your package to setup php on my CI.

I recently added the support for importing trees from [nikic/php-ast](https://github.com/nikic/php-ast) extension in my package.
Unfortunately, the extension is not available on your system and [tests are failing](https://github.com/loophp/phptree/runs/491385787?check_suite_focus=true).

Do you think adding support for that extension would be possible ?
I just noticed that builds are successful on macosx and the extension is available on that platform.
How can we do to have it on Linux and Windows machines ?

Thanks.

**Comment by shivammathur** [comment]
[nikic/php-ast](https://github.com/nikic/php-ast) is already supported. This being a `PECL` extension which is not available as a `ubuntu` package, you have to specify `pecl` in tools input.

Here is a test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/51077847/workflow

**Comment by drupol** [comment]
Amazing, thanks!
