### ISSUE TITLE
Bump Phalcon version to 4.0.5

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#204]
**Is your feature request related to a problem? Please describe.**
Current version is `4.0.4`, and there is new one which is `4.0.5`

**Comment by shivammathur** [comment]
On `windows` and `macOS` version should be `4.0.5`, for ubuntu please ask ondrej to upgrade `phalcon4` package to `4.0.5`. 

Until the upgrade, you can specify `phalcon-4.0.5` in ubuntu workflow to install it from PECL.

**Comment by Jeckerson** [comment]
OK, thanks.

**Comment by shivammathur** [comment]
@Jeckerson if you are using `phalcon-4.0.5` with the extension cache, specify `psr` before it in the extensions. On first run while the extensions will be installed, you will have warnings and errors as `psr` will be installed twice. but on second run `psr` will be enabled before `phalcon` from cache and it won't fallback to installing `phalcon` again.

Example
first run - https://github.com/shivammathur/test-setup-php/actions/runs/59199555/workflow
second run with cache - https://github.com/shivammathur/test-setup-php/actions/runs/59204306/workflow

**Comment by Jeckerson** [comment]
@shivammathur Seems to work - https://github.com/phalcon/migrations/commit/0d2dcd8131fe0f0aba9d0e9d442aaaa2e407908e
Thanks again!
