### ISSUE TITLE
Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in 

### ISSUE THREAD

**Issue by hughcube** [shivammathur/setup-php#207]
**Describe the bug**
The composer installation dependency occurs

The global memory limit is now modified, but is not appropriate
It is recommended that the composer command be added to  ```php -d memory_limit=-1```

**Comment by shivammathur** [comment]
If you want to set `memory_limit=-1`. Use `ini-values` input.

**Comment by hughcube** [comment]
I know this works, but it's a global setting, I just need it for composer install

**Comment by shivammathur** [comment]
Alternatives would be prefixing composer commands with `php -d memory_limit=-1` or `COMPOSER_MEMORY_LIMIT=-1`

Refer to this - https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by hughcube** [comment]
Php  -d memory_limit=-1 must know its path
COMPOSER_MEMORY_LIMIT=-1 is the best choice
Thank you very much
