### ISSUE TITLE
Doesn't work on self host runner

### ISSUE THREAD

**Issue by oleg-brizy** [shivammathur/setup-php#209]
I have two js/node projects and I migrated them successfully on self host runner.

The php project refuses to work https://pastebin.com/raw/LvUPq9ym

I allowed `sudo` for runner user without password, so the script can install the dependecies it needs. But in logs, after successfull php install, below it shows `php not found` (weird).

_All these github actions are new to me, I thought the migration to self hosted will take a few minutes (no config change) but it took all day and still not working._

Is it possible to use this setup on self hosted or it works only on github cloud?

My config https://pastebin.com/RKSG4e0w
Dockerfile https://pastebin.com/EpZzDfvg

**Comment by shivammathur** [comment]
currently does not support self hosted runners.

**Comment by oleg-brizy** [comment]
Thanks.

Can you explain briefly, why? (just curious)

**Comment by shivammathur** [comment]
@oleg-brizy It will work on self hosted runners on ubuntu, windows and macos after 2.2.0 release.

**Comment by oleg-brizy** [comment]
Will `sudo` access (without password) be required?

_(I have no idea how the dependencies are installed internally, system-wide or some sort of "containers")_

**Comment by shivammathur** [comment]
Yes, the action requires `sudo` to install dependencies.

**Comment by RemyyB** [comment]
Is 2.2.0 release or later already out? Can't seem to find it anywhere yet ;)

**Comment by oleg-brizy** [comment]
@RemyyB It's In Progress

![StaticShot_24-04-2020_20-39-15](https://user-images.githubusercontent.com/59368968/80241107-b4bb0700-866b-11ea-89d4-54ab593e1ce0.png)

**Comment by georgezim85** [comment]
Doesn't work in act too, for running GitHub Actions locally.
https://github.com/nektos/act

**Comment by shivammathur** [comment]
@georgezim85 There are some issues in using nektos/act with `setup-php` including the one in your screenshot and that it uses a Debian based image.

The solution would be to use `nektos/act` with a custom docker image over `ubuntu` which can run this action. I will have a look at this in a release after `2.2.0`.

**Comment by shivammathur** [comment]
@oleg-brizy Now you can use self-hosted runners. Refer to the docs [here](https://github.com/shivammathur/setup-php#self-hosted-setup).

@georgezim85 Added support for `nektos/act`. Refer to the docs [here](https://github.com/shivammathur/setup-php#self-hosted-setup).
