### ISSUE TITLE
Unable to load dynamic library 'mailparse.so'

### ISSUE THREAD

**Issue by ThomasTr** [shivammathur/setup-php#211]
**Describe the bug**
PHP Warning:  PHP Startup: Unable to load dynamic library 'mailparse.so' (tried: /usr/lib/php/20190902/mailparse.so (/usr/lib/php/20190902/mailparse.so: undefined symbol: mbfl_convert_filter_flush), /usr/lib/php/20190902/mailparse.so.so (/usr/lib/php/20190902/mailparse.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Mailparse must be loaded after mbstring.

mbstring seems already loaded by default. Is there a way to set the order?

**Comment by shivammathur** [comment]
@ThomasTr I'm unable to reproduce the error. Here is a test workflow and mailparse installs without any errors: https://github.com/shivammathur/test-setup-php/actions/runs/74589000/workflow

Please provide the `yml` of the workflow you have so that I can reproduce the error.

**Comment by ThomasTr** [comment]
@shivammathur thanks for investigating, setting mbstring explizit seems to work (thought it was enabled by default)
