### ISSUE TITLE
PHP 7.0 has no intl by default

### ISSUE THREAD

**Issue by Seldaek** [shivammathur/setup-php#215]
**Describe the bug**
As per https://github.com/composer/composer/pull/8803/checks?check_run_id=606395793 it seems that the PHP 7.0 install does not have the intl extension enabled by default, while all other versions do.

**To Reproduce**
https://github.com/composer/composer/blob/master/.github/workflows/continuous-integration.yml

**Expected behavior**
intl should be present on all versions by default

P.S. Thanks for the great work on this, it seems like a very complete way to install all things PHP!

**Comment by Seldaek** [comment]
Seems like maybe php 5.6 also doesn't https://github.com/composer/composer/pull/8817/checks?check_run_id=605571293  We're having issues with cancelling builds atm so it's a bit hard to tell which work and don't sorry.

**Comment by shivammathur** [comment]
@Seldaek composer/composer#8821 should fix it for now, after `2.2.0` release, intl will be available by default on both `5.6` and `7.0`.

**Comment by shivammathur** [comment]
@Seldaek Now `intl` will be installed by default with PHP `5.6` and `7.0` in your workflows.

**Comment by Seldaek** [comment]
Thanks!
