### ISSUE TITLE
Not global acces for tool installed with composer global require

### ISSUE THREAD

**Issue by Wtyd** [shivammathur/setup-php#216]
**Describe the bug**
I have to install another library not supported like [parallel-lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint). I install with `composer global require` but the only form to run the tool is with absolut path `/home/runner/.composer/vendor/bin/parallel-lint --version`. I have not global access.

**To Reproduce**
[feature.zip](https://github.com/shivammathur/setup-php/files/4570160/feature.zip)

**Expected behavior**
If I install a tool with global composer require I would like to have access to it globally.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13366202/80913061-cd00e500-8d41-11ea-934a-bfa16f8cba11.png)

**Additional context**
I tried to add to $PATH the composer global path (`/home/runner/.composer/vendor/bin`) but neither works.

**Comment by shivammathur** [comment]
Each step in your workflow runs as a separate process, so exporting PATH in one step has no effect on further steps.

GitHub Actions provides a syntax to add a folder to `$PATH`.

```diff
-  - name: Export path
-    run: export PATH=$PATH:/home/runner/.composer/vendor/bin
+  - name: Export path
+    run: echo "::add-path::$(composer -q global config home)/vendor/bin"
```

Here is a test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/94496048/workflow

**Comment by kasperg** [comment]
Have you considered adding this per default?

**Comment by shivammathur** [comment]
@kasperg Yes, in next release.

**Comment by shivammathur** [comment]
@kasperg @Wtyd Now composer bin directory will be in `PATH`.
