### ISSUE TITLE
macOS has no SNMP support

### ISSUE THREAD

**Issue by kiler129** [shivammathur/setup-php#218]
**Is your feature request related to a problem? Please describe.**
The PHP installed on macOS has no SNMP support. The SNMP support is [baked-in into core PHP](https://www.php.net/manual/en/snmp.installation.php) and not available as a shared module. 
[Some time ago SNMP was kicked](https://github.com/Homebrew/homebrew-php/pull/4798#issuecomment-377681986) out of the default `homebrew` install because of reported crashed while used with `Apache` caused by [linking order](https://github.com/Homebrew/homebrew-core/issues/26004#issuecomment-377834506). Since this is not a shared extension it [cannot be re-installed using `pecl`](https://pecl.php.net/package-search.php?pkg_name=snmp).

**Describe the solution you'd like**
macOS users most often simply add the [kabel/homebrew-php-ext](https://github.com/kabel/homebrew-php-ext) tap which contains extensions which were unstable for one reason or another (or conflicted with something more mainstream).
I think this tap should be included in macOS builds.

**Comment by shivammathur** [comment]
This can be added as a step after PHP setup in individual workflows as per the requirement of the project.

For example 
```yml
brew tap kabel/php-ext
brew install php@7.3-snmp
```

**Comment by kiler129** [comment]
Thank you, I didn't think about that :)
