### ISSUE TITLE
Can't install Phalcon + PSR with PHP 7.2.30

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#221]
**Describe the bug**
Can't install Phalcon + PSR with PHP 7.2.30

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
7.2.30

**To Reproduce**
* https://github.com/phalcon/migrations/runs/683450613
* https://github.com/phalcon/migrations/blob/master/.github/workflows/tests.yml

**Expected behavior**
Install Phalcon with PSR via `extensions` same way as with 7.3 and 7.4

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/3289702/82194561-ec297600-98ee-11ea-8c18-09f12b78f07d.png)

**Comment by shivammathur** [comment]
@Jeckerson Patched, both `phalcon4` and `phalcon-4.0.6` with now setup `phalcon-4.0.6` with `psr-1.0.0`
