### ISSUE TITLE
Enable pdo-pgsql php 8.0.0-dev

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#222]
**Describe the feature**
Enable pdo-pgsql for php 8.0.

**Underlying issue**
Do not run tests with pgsql.

![image](https://user-images.githubusercontent.com/42547589/82211457-db710400-98de-11ea-9c7e-98bfc49ea6ea.png)

**Comment by shivammathur** [comment]
Fixed in 18041fd, 3bffbad and shivammathur/php-builder@62869bc
