### ISSUE TITLE
How to install composer v2 instead of v1

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#227]
Is there a way to install composer 2.0-dev instead of 1.10?

**Comment by shivammathur** [comment]
@GrahamCampbell  I will add support in the next release to setup `composer 2.0-dev` via tools input. Till then please add a step to update it after this action

```yaml
- name: Update composer to snapshot
  run: composer self-update --snapshot
```

**Comment by validaide-mark-bijl** [comment]
Hi @shivammathur 

First of all: thanks for a great GitHub Action!

I am currently using your deployment to run our PHP Symfony application. However, as the latest version of Composer is installed by default, I am now experiencing errors as there is a new release of composer, but as it uses this by default, I now get issues with my dependencies that rely on a composer version 1.x instead of 2.x.

```
Run composer install --optimize-autoloader --prefer-dist --no-suggest --no-scripts
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - jean85/pretty-package-versions 1.2 requires ocramius/package-versions ^1.2.0 -> satisfiable by ocramius/package-versions[1.4.2].
    - jean85/pretty-package-versions is locked to version 1.2 and an update of this package was not requested.

Use the option --with-all-dependencies to allow upgrades, downgrades and removals for packages currently locked to specific versions.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
##[error]Process completed with exit code 2.
```

Now I was able to implement a workaround using your comment, though I had to add a ```sudo``` to make it work:

```
      - name: Update composer to version 1.9.3
        run: sudo composer self-update 1.9.3 --snapshot
```

Generally speaking it might help if the composer version is not the latest by default and you can configure it? Unless of course there are valid reasons why this is the case that I am not aware of :)

Thanks!
Mark

**Comment by GrahamCampbell** [comment]
If you upgrade `ocramius/package-versions`, it will work with composer 2.

**Comment by GrahamCampbell** [comment]
Indeed, the error message actually tells you this!

**Comment by shivammathur** [comment]
@validaide-mark-bijl

- As @GrahamCampbell mentioned, you need to update the packages as per the logs.
> If you upgrade `ocramius/package-versions` (to 1.8.0 or higher), it will work with composer 2.

- `composer` updates without `sudo`. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/123880785/workflow).
- If you are still facing problems, please create a new issue with a link to your workflow.
