### ISSUE TITLE
How to install Composer v1 instead of v2

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#229]
**Describe the bug**
Composer v2 is not out yet, but it seems to be in use:
```
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.6.2 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.6.2].
    - dealerdirect/phpcodesniffer-composer-installer v0.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-req=composer-plugin-api, but this may result in broken plugins and bigger problems down the line.
```

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
php 7.2 through 7.4

**To Reproduce**
```
**Expected behavior**
Composer v1 should be used as long as v2 is not released

**Actual behavior**

https://github.com/doctrine/coding-standard/pull/195/checks?check_run_id=735650146
```

**Expected behavior**
composer v1 should be installed unless required otherwise

**Screenshots/Logs**
https://github.com/doctrine/coding-standard/pull/195/checks?check_run_id=735650146

**Additional context**
composer 2.0.0-alpha1 was released today: https://github.com/composer/composer/releases/tag/2.0.0-alpha1

I wrongly posted this at https://github.com/actions/virtual-environments/issues/1000, originally

**Are you willing to submit a PR?**
Yeah why not?

**Comment by Jeckerson** [comment]
Try to run, to rollback to v1
```
composer self-update --1
```

**Comment by greg0ire** [comment]
Thanks for the workaround, but I'm more looking for a bugfix here… the title is more an attempt at humor than a real request :P, this isn't going to fly in code review I'm afraid :sweat_smile: 

![Screenshot_2020-06-03 shivammathur setup-php](https://user-images.githubusercontent.com/657779/83680305-1793ac80-a5e1-11ea-9e86-cb4e9d7287d8.png)

**Comment by shivammathur** [comment]
@greg0ire The version of composer currently being setup is `1.10.7`. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/124049143/workflow).
In next release you will have the option to specify `composer-v1` and `composer-v2` in tools input.

**Comment by shivammathur** [comment]
@greg0ire Change `setup-php` version to `2.2.2` or `v2` in your workflow and it will setup composer 1.x until 2.x becomes stable. Also in next release of the action you will have `composer-v1` and `composer-v2`

**Comment by greg0ire** [comment]
Good catch, thanks a lot!
