### ISSUE TITLE
libicui18n image not found

### ISSUE THREAD

**Issue by YaFou** [shivammathur/setup-php#230]
**Describe the bug**
The workflow fails when I want to get the Composer dependencies cache on MacOS. It couldn't find the `libicui18n` image.

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
- 7.1
- 7.2
- 7.3

**To Reproduce**
See [this workflow](https://github.com/YaFou/Container/actions/runs/124638043/workflow).

**Expected behavior**
The Composer dependencies cache folder should be store in the expected variable to use it in the cache action.

**Screenshots/Logs**
[Log](https://github.com/YaFou/Container/runs/737842584?check_suite_focus=true) (look at the 4th step)

**Comment by shivammathur** [comment]
@YaFou rebuilding

**Comment by shivammathur** [comment]
@YaFou It will setup without errors now. Please rerun your workflow.

**Comment by YaFou** [comment]
Thank you @shivammathur!
