### ISSUE TITLE
Aerospike PHP client

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#234]
**Describe the feature**
Have possibility to have Aerospike installed during pipeline

Installation guide - https://www.aerospike.com/docs/client/php/install/

**Version**
- [x] I have checked releases and the feature is missing in the latest patch version of `v2`.

**Comment by shivammathur** [comment]
@Jeckerson 
I'm not sure if many projects use this extensions, also it requires a custom setup, so it would not make sense to integrate it into the action. You can setup this in your workflow as required.

Add `pecl` in `tools` input and add a step after PHP setup to install the extension. I wrote a small [script](https://gist.github.com/shivammathur/c23dc3e5bc07c4bc3fb6becacf1611a5#file-install-ext-aerospike-sh) which you can use. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/139195923/workflow).
