### ISSUE TITLE
Self-hosted runner with services

### ISSUE THREAD

**Issue by stephanvierkant** [shivammathur/setup-php#236]
I'd like to have a self-hosted runner with services. I'm using the [symfony-mysql.yml](https://github.com/shivammathur/setup-php/blob/master/examples/symfony-mysql.yml) example and I can't find out how to run this example on a self-hosted runner.

Not sure if this should be considered as a feature request or that it just need some documentation.

**Comment by shivammathur** [comment]
Workflows with services work on Linux self-hosted runners. Docker is required for the services to run, I will specify this in the documentation.

**Comment by shivammathur** [comment]
Updated docs.
https://github.com/shivammathur/setup-php#self-hosted-setup
https://github.com/shivammathur/setup-php/wiki/Requirements-for-self-hosted-runners#linuxwsl
