### ISSUE TITLE
Update to latest patch release by default

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#245]
I think the fact that '7.3' will give you an old version on ubuntu-18.04 and the latest on ubuntu-20.04 is kinda an odd behaviour. I'd suggest changing the "update" param to true by default. Is there anything we can do to make fetching the latest patch release faster. Perhaps a nightly build like is done for PHP 8 could be used to instantly fetch latest version (latest tagged patch release)?

EDIT: It looks like GitHub are quite quick at updating, actually, however we still have the problem that PHP 7.3 takes quite some time to setup on Ubuntu 20.04.

**Comment by shivammathur** [comment]
`ubuntu:20.04` runner only has `PHP 7.4`, so all versions before it are installed fresh on each run and thus the setup seems slow for `PHP 7.3`. 
Also `ppa:ondrej/php` is added back again on `ubuntu:20.04` as it was removed, which adds 10-15 more seconds.
I would suggest using `ubuntu:18.04` or `ubuntu:16.04` unless it is required to upgrade to `20.04`.

It takes 1 to 2 weeks for every patch to be installed on the runners. Till that time after each patch release if update is mandatory, it would mean setup on `Ubuntu` taking 1 or 2 minutes for everyone, that is why updating is optional and should be done as per project requirement.

In future I will try to optimise the update process, but currently, I think the best way would be notifying `actions/virtual-environments` to update the versions on the runner after the patch releases.

**Comment by GrahamCampbell** [comment]
I was suggesting we make changes so that updating does not take 100 seconds or so, by similar means to how PHP 8 nightly is provided.

**Comment by GrahamCampbell** [comment]
Because ubuntu-20.04 is going to become the default soon, and is super slow because only PHP 7.4 is installed by default.

**Comment by shivammathur** [comment]
Yes, I will check if any improvements can be made. Repackaging the stable builds like `8.0` builds most likely will not work as then extension packages in `ppa:ondrej/php` would not work.
