### ISSUE TITLE
Enable curl extension by default

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#246]
This would be great, so that composer 2.0 can perform parallel downloads, without people needing to opt-in to curl. I think many people won't notice that they forgot to add curl, and will end up with slower builds.

**Comment by shivammathur** [comment]
@GrahamCampbell `ext-curl` is enabled by default on each configuration. Here is a test workflow https://github.com/shivammathur/test-setup-php/actions/runs/165638300/workflow

**Comment by GrahamCampbell** [comment]
Oh, where does that happen?

**Comment by shivammathur** [comment]
## Ubuntu

Runner - https://github.com/actions/virtual-environments/blob/c5c5d14fefa1b75d05c8191fef1ef7df8dbe7ca6/images/linux/scripts/installers/php.sh#L40

https://github.com/shivammathur/setup-php/blob/38731c6386cb82423176e3eaf878615515c3da70/src/scripts/linux.sh#L352-L353

## Windows
https://github.com/shivammathur/setup-php/blob/38731c6386cb82423176e3eaf878615515c3da70/src/scripts/win32.ps1#L358-L362

## macOS
Each formula for PHP 5.6 and above is built `--with-curl`
For example PHP 7.3 - https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%407.3.rb#L134

PHP 5.3 to PHP 5.5 builds have pre-built curl extension from macports project in the builds.

**Comment by GrahamCampbell** [comment]
Thanks for the detailed reply. Very helpful. :)
