### ISSUE TITLE
Blackfire CLI client should not be configured with sudo

### ISSUE THREAD

**Issue by lolautruche** [shivammathur/setup-php#247]
**Describe the bug**
On Linux, `blackfire config` is launched with `sudo`, which is not compliant with Blackfire documentation. Indeed, CLI commands such as `blackfire run` are launched by the current user, not by root. Hence, configuring with `sudo` leads to unexpected behavior, because client id/secret are registered by root, making the `.blackfire.ini` file unreadable by the current user.

PR incoming.

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [x] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

7.4

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
Yes

**Comment by shivammathur** [comment]
@lolautruche Released the changes in `2.4.0`. 

I have a request, would it be possible to add documentation of using blackfire on GitHub Actions using setup-php to the CI integrations section of the official documentation.

**Comment by shivammathur** [comment]
Use `shivammathur/setup-php@v2`. `v2` points to the latest 2.x.x release.
