### ISSUE TITLE
Request for `composer-require-checker` and `composer-normalize` tools

### ISSUE THREAD

**Issue by filips123** [shivammathur/setup-php#250]
**Describe the feature**

I want to request two tools to be available for global installation:

[`composer-require-checker`](https://github.com/maglnet/ComposerRequireChecker) is a tool which analyzes code to prevent "soft" dependencies:

> A CLI tool to analyze composer dependencies and verify that no unknown symbols are used in the sources of a package. This will prevent you from using "soft" dependencies that are not defined within your `composer.json` require section.

This is useful to prevent breakage from using dependencies of dependencies without requiring them in `composer.json`. It can be used as additional check in CI to make sure all commits and PRs are using dependencies as they should.

[`composer-normalize`](https://github.com/ergebnis/composer-normalize) is a tool (both as Composer plugin and standalone PHAR) for normalizing `composer.json`:

> * restructure `composer.json` according to the underlying JSON schema
> * sort entries in the `bin` section (by value)
> * sort entries in the `config`, `extra`, and `scripts-descriptions` sections (by key)
> * sort entries in the `conflict`, `provide`, `replace`, `require`, `require-dev`, and `suggest` sections (as you are used to from the `sort-packages` configuration)
> * normalize version constraints in `conflict`, `provide`, `replace`, `require`, and `require-dev` sections

This can be used either as CI check without changing `composer.json` or to automatically rewrite `composer.json` and push new changes to repository.

**Version**

- [x] I have checked releases and the feature is missing in the latest patch version of `v2`.

**Describe alternatives**

Installing tools manually.

**Are you willing to submit a PR?**

Both are publishing PHARs to GitHub Releases and from existing tools it seems it is not hard to get them from GitHub Releases, so I can probably submit PR.

**Comment by shivammathur** [comment]
@filips123 Both tools `composer-require-checker` and `composer-normalize` have been added in `2.4.0` release.
@localheinz Thanks for working on this.

**Comment by localheinz** [comment]
You are welcome, @shivammathur!

Thank you for suggesting it, @filips123!
