### ISSUE TITLE
PHP 8.0 Default Memory Limit

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#251]
The default memory limit set by your package for PHP 7.4 is -1 but 8.0 is 128M.

Could we make the default `-1` everywhere please?

PHP 7.4:

```
php -i | grep "memory_limit"
memory_limit => -1 => -1
```

PHP 8.0:

```
php -i | grep "memory_limit"
memory_limit => 128M => 128M
```

**Comment by shivammathur** [comment]
@GrahamCampbell Fixed on `Ubuntu`. Patch for `Windows` and `macOS` will be in next release.

**Comment by GrahamCampbell** [comment]
Awesome. 👍
