### ISSUE TITLE
Windows PHP 8.0 version old

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#261]
Is there any chance we could get the 8.0.0 alpha3 release available on Windows? The current version is a bit old: https://github.com/shivammathur/test-setup-php/runs/893897861?check_suite_focus=true. :)

**Comment by shivammathur** [comment]
@GrahamCampbell it will setup nightly builds now on `Windows`.

**Comment by GrahamCampbell** [comment]
🍻 🎉

**Comment by terabytesoftw** [comment]
@shivammathur hi, how to last version php 8.0 alpha 3.0.

**Comment by shivammathur** [comment]
@terabytesoftw The action does not support installing 8.0 alpha 3.0 specifically. The nightly PHP 8.0 build in all OS is newer than that.
