### ISSUE TITLE
Add ext cubrid its posible php 7.x

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#267]
Its posible install ext cubrid php 7.x,

Thks.

**Comment by shivammathur** [comment]
@terabytesoftw 
I will add support for `cubrid` on `Ubuntu` in the next release for all PHP versions.
Also I checked `pdo_cubrid`, it does not support `PHP 7.3` and `PHP 7.4`. So that will install for PHP 7.2 and lower.

**Comment by shivammathur** [comment]
@terabytesoftw Added in `2.4.2`
