### ISSUE TITLE
PHP 8.0 and extensions: sodium

### ISSUE THREAD

**Issue by heddn** [shivammathur/setup-php#268]
**Describe the bug**

Adding doesn't actually install libsodium on PHP 8.0

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu-latest

**PHP versions**

8.0

**To Reproduce**

https://github.com/php-tuf/php-tuf/runs/955734715?check_suite_focus=true

**Expected behavior**

Sodium should be available.

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Fixed in shivammathur/php-builder@fcf4bfb
