### ISSUE TITLE
PHP 8 on Windows - inet_pton not found

### ISSUE THREAD

**Issue by ondrejmirtes** [shivammathur/setup-php#273]
**Describe the bug**
When running PHP 8.0 version on Windows, the `inet_pton` function is not found.

* https://www.php.net/manual/en/function.inet-pton.php
* https://github.com/phpstan/phpstan/blob/894c59fcf79df09aba631ac52230efbcd15048e0/.github/workflows/build.yml#L15-L50

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Windows

**PHP versions**

8.0

**To Reproduce**

Run `composer update` with `composer:snapshot` on PHP 8.0 windows-latest

**Expected behavior**

**Screenshots/Logs**

https://github.com/phpstan/phpstan-src/runs/992276871?check_suite_focus=true

**Comment by shivammathur** [comment]
@ondrejmirtes it should be there
https://github.com/shivammathur/test-setup-php/runs/993405799?check_suite_focus=true

**Comment by ondrejmirtes** [comment]
Oh, sorry, looks like a Composer bug here then: https://github.com/composer/composer/blob/0eebdcf2e655f28107aa2c5c33f6d7a4c948457b/src/Composer/Repository/PlatformRepository.php#L128

**Comment by ondrejmirtes** [comment]
Reported here: https://github.com/composer/composer/issues/9128

**Comment by shivammathur** [comment]
Yes, it changed here https://github.com/composer/composer/commit/7e1ef19a5a544af35a3b063652659637c711fb2a
So it should work with `composer:v2`.

**Comment by ondrejmirtes** [comment]
Is it possible that composer:v2 on Windows has an older out of date version? I'm using `composer:snapshot` there.

**Comment by shivammathur** [comment]
`composer:v2` is `2.0.0-alpha3` release currently and this changed after that release.

**Comment by ondrejmirtes** [comment]
I'm using `composer:snapshot` - looks like on Linux it already has this change but on Windows it doesn't.

**Comment by ondrejmirtes** [comment]
I actually don't know if Linux or Windows have newer `composer:snapshot` - I'm not sure if the linked Composer commit fixes or introduces the bug.

**Comment by shivammathur** [comment]
Composer `snapshot` is same in both OS, The issue is in `composer` or `php-src`.

**Comment by shivammathur** [comment]
@ondrejmirtes Updated the composer builds cache after fix. The workflow should pass now.

**Comment by ondrejmirtes** [comment]
Thank you, it works!
