### ISSUE TITLE
Make ICU version configurable

### ISSUE THREAD

**Issue by ausi** [shivammathur/setup-php#282]
**Describe the feature**
Make it possible to select the underlying ICU version for the intl extension.
Something like `extensions: intl-icu58.1` or `extensions: icu-58.1`.

**Version**
- [x] I have checked releases and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
Running unit tests for the lowest supported ICU version. This is quite important for projects with heavy usage of the `intl` extension.

**Describe alternatives**
Somehow installing libicu manually before PHP is built (if this is possible?)

**Additional context**
N/A

**Are you willing to submit a PR?**
I’m very new to GitHub workflows and don’t know much about setting up a PHP build 🙈

**Comment by shivammathur** [comment]
@ausi Next release will have support for specifying `intl-<icu_version>`, for example `intl-67.1` in `Ubuntu` workflows for `PHP 5.6` to `PHP 7.4`.

**Comment by ausi** [comment]
That’s awesome, thank you!

**Comment by shivammathur** [comment]
@ausi This is now available in `v2`.
