### ISSUE TITLE
report versions of the used tools

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#288]
**Describe the feature**
would be great the build-output would show which version of the tools are used.

I guess we are currently running in one of the bugs the recent composer releases had, but were fixed in the subsequent release (we had 2 or 3 releases yesterday).

since I cannot see which version of composer the build is using I cannot confirm my thesis easily.

![grafik](https://user-images.githubusercontent.com/120441/92752841-9723db00-f389-11ea-9597-ba3796b73de1.png)

**Version**
using the latest v2 tag

**Comment by shivammathur** [comment]
@staabm By default it will always setup the latest release version.

I had not done this as some tools have a startup time and checking the version adds to the CI runtime. I will run some tests again.
Currently, I would recommend adding a step after `setup-php` step to check the tool version.
For `cs2pr` it will be `1.3.0` release. It shows the versions as `1.1.1-dev` though as it picks `$version` in the script.

```yml
- name: Check versions
  run: |
    composer -V
    cs2pr version
```

**Comment by staabm** [comment]
Thx for the headsup. Just created a cs2pr issue https://github.com/staabm/annotate-pull-request-from-checkstyle/issues/51
