### ISSUE TITLE
Make libxml version configurable

### ISSUE THREAD

**Issue by swissspidy** [shivammathur/setup-php#289]
**Describe the feature**

Similar to #282 for  `intl`, it would be amazing if the `libxml` extension version could be configured.

**Version**
- [x] I have checked releases and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Many hosting providers run a modern PHP version with an outdated libxml version. There are many strange combinations in the wild.

With this feature we'd be able to run unit tests against various combinations.

**Describe alternatives**
N/A

**Additional context**
N/A

**Are you willing to submit a PR?**

If this requires an additional repo like https://github.com/shivammathur/icu-intl, then this is probably a bit over my head.

**Comment by shivammathur** [comment]
`libxml` extension is not a shared extension, but is statically linked in the PHP binary. So unlike `intl` this would require compiling PHP with different releases of `libxml2` and would be unmaintainable.

**Comment by swissspidy** [comment]
@shivammathur Thanks for your quick feedback! Didn't realize that :/ That makes my endeavour more difficult it seems. If I need to compile PHP myself for that, I assume I cannot use this GH action?

**Comment by shivammathur** [comment]
You can, Add a step before `setup-php` step to install and link your compiled PHP and `setup-php` will use that php, you will be able to add `ini-values`, add tools and install extensions from `PECL`.
