### ISSUE TITLE
Upgrade to @actions/core >= v1.2.6 & avoid `add-path`

### ISSUE THREAD

**Issue by elrido** [shivammathur/setup-php#297]
I started getting annotations on a workflow pointing me to the following Github changelog:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

As far as I can tell I am not using any of those features in that workflow myself and it only occurs in the jobs related to running PHPunit using this php action. Since I do note that this actions' master currently depends on @actions/core v1.2.5, I suspect the annotations show up because of that?
https://github.com/shivammathur/setup-php/blob/8f0cfca4551ccb8a70f7ba594312431f67b1ddc2/package.json#L27

We may also have to change the following line somehow, but I haven't yet figured out with what:
https://github.com/shivammathur/setup-php/blob/8f0cfca4551ccb8a70f7ba594312431f67b1ddc2/src/scripts/linux.sh#L255
Maybe we [now would need to set the path like this](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)?
```bash
echo "/home/$USER/.composer/vendor/bin" >> $GITHUB_PATH
```

For your reference, this is the workflow I encountered this on:
https://github.com/PrivateBin/PrivateBin/blob/master/.github/workflows/tests.yml

**Comment by shivammathur** [comment]
Fix is in develop branch, will be in release tomorrow.

**Comment by elrido** [comment]
Awesome! Thank you very much
