### ISSUE TITLE
AST fails to install for PHP 7.2

### ISSUE THREAD

**Issue by olsi-qose** [shivammathur/setup-php#305]
**Describe the bug**
Hi! 

We are using this action to setup php to run code analysis on our repos. But lately the `ast` extension fails to install on PHP 7.2.33 .
Can this be checked?

Thanks! 

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [x ] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
7.2

**To Reproduce**

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/44775916/95757535-f12cfe80-0caf-11eb-80e3-f033438ef522.png)

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@olsi-qose Which version of Ubuntu are you using?

**Comment by shivammathur** [comment]
Added a patch, it should work now.
