### ISSUE TITLE
Add a way to turn off graceful logging

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#306]
**Describe the feature**

I would like a way to make sure failing to install an extension fails the build

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Not being able to figure out what is going wrong

**Describe alternatives**

No alternatives considered

**Additional context**

See confused people at https://github.com/sonata-project/exporter/pull/394#issuecomment-707068630

**Are you willing to submit a PR?**

I'm not planning to, but I guess I could.

**Comment by shivammathur** [comment]
Extension `mongodb` does not support PHP 8 yet.

Workflows do not fail for failing extensions and tools to make sure setup can be cross platform as some are platform specific.

Currently you can ensure the workflows fail on a project basis by adding a step after `setup-php` to fail the workflow.

For example
```yml
name: Check mongodb
run: php -r "if(! extension_loaded('mongodb')) {throw new Exception('mongodb not found');}"
```

or fail for multiple extensions, check - https://github.com/shivammathur/setup-php/issues/194#issuecomment-591983087

**Comment by greg0ire** [comment]
Ok, I see the use case, but IMO by default it should fail. It would be great to have something like this:

```
extensions: mongodb
mandatory_extensions: oci8,gd
```

If the whole point of a job is to test Oracle, and tests for Oracle are in fact skipped because the install silently failed, things are needlessly hard to troubleshoot.

**Comment by shivammathur** [comment]
I'm adding a env variable in next release, when set will change the behaviour to failing by default.

**Comment by ocean90** [comment]
This should also apply to tools. For example the installation of deployer is current failing [due to missing downloads](https://github.com/deployphp/deployer/issues/2204) and it took a while to understand what the issue was because the action didn't fail thus the log was collapsed by default.

**Comment by shivammathur** [comment]
@ocean90 Yes, it will work for both extensions and tools

**Comment by shivammathur** [comment]
@ocean90 @greg0ire 
Now you should be able to set `fail-fast: true` which will fail the workflow when an extension or a tool fails to setup.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7,4'
    tools: deployer
  env:
    fail-fast: true
```

**Comment by greg0ire** [comment]
Thanks a lot!
