### ISSUE TITLE
mongodb Could not installed..............

### ISSUE THREAD

**Issue by qazz92** [shivammathur/setup-php#308]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
php 7.4.10

**To Reproduce**
`    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, pecl
        extensions: mongodb-1.8.0`

**Expected behavior**
mongodb........should be installed.....

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/13778725/95847169-5c95cf80-0d87-11eb-9a83-cd070a00f10b.png)

**Additional context**
plz.....

**Comment by shivammathur** [comment]
@qazz92 Patched in #310. It should work now.
