### ISSUE TITLE
Fail pdo_sqlsrv.

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#309]
![image](https://user-images.githubusercontent.com/42547589/95866313-26802d80-0d3e-11eb-9c38-47c5d044a66b.png)

It would be great if it could also be installed in PHP 8.0, https://pecl.php.net/package/pdo_sqlsrv/5.9.0preview1,

Thks for all your work,

**Comment by shivammathur** [comment]
@terabytesoftw Patched in #310. It should work now.
