### ISSUE TITLE
Missing PHP 8 in matrix

### ISSUE THREAD

**Issue by OskarStark** [shivammathur/setup-php#319]
Hi, I checked https://github.com/shivammathur/setup-php#cloud-osplatform-support and would propose to add PHP 8.0

WDYT?

**Comment by shivammathur** [comment]
Those are PHP versions which are pre-installed on the runners, PHP 8 is not.

**Comment by OskarStark** [comment]
But I can use PHP `8.0` even if its not pre-installed on the runner? Same for `5.6`?

**Comment by shivammathur** [comment]
Yes, you can currently use from `PHP 5.3` to `PHP 8.1`. If the version is not pre-installed `setup-php` installs it.
https://github.com/shivammathur/setup-php#tada-php-support

**Comment by OskarStark** [comment]
Thank you!
