### ISSUE TITLE
When build extensions in PHP7.2, it will be broken.

### ISSUE THREAD

**Issue by limingxinleo** [shivammathur/setup-php#323]
**Describe the bug**

https://github.com/limingxinleo/swow/runs/1335375564?check_suite_focus=true

```
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
/usr/bin/m4:aclocal.m4:20433: ERROR: end of file in string
autom4te: /usr/bin/m4 failed with exit status: 1
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

7.2
**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@limingxinleo I have added a patch. Re-run your workflow, it should build correctly now.
