### ISSUE TITLE
sqlsrv Could not install sqlsrv-5.9.0preview1

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#325]
**Describe the bug**

`sqlsrv-5.9.0preview1` fails to install

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
This fails on at least PHP 7.3.24

**To Reproduce**
https://github.com/doctrine/dbal/blob/2.12.x/.github/workflows/continuous-integration.yml

**Expected behavior**
The extension should install just fine, like it did before

**Screenshots/Logs**
Logs are available at https://github.com/doctrine/dbal/pull/4393/checks?check_run_id=1335803773#step:4:21

**Are you willing to submit a PR?**
No, this time I have no idea what the issue could be.

**Comment by shivammathur** [comment]
@greg0ire I added a patch, can you test if it installs correctly now.

**Comment by greg0ire** [comment]
@shivammathur it does not seem to work better: https://github.com/doctrine/dbal/pull/4393/checks?check_run_id=1336098530#step:4:20

**Comment by shivammathur** [comment]
@greg0ire Issue is in upstream builds https://github.com/oerdnj/deb.sury.org/issues/1478. `pecl` is only working for `PHP 7.4`. 
Till there is a fix upstream, try switching to `ubuntu-18.04`.

**Comment by shivammathur** [comment]
@greg0ire Fixed upstream and I have updated the builds cache. It should now work on `ubuntu-20.04` as well.

**Comment by greg0ire** [comment]
I can confirm, thanks, I can now move on to the next issue :)
