### ISSUE TITLE
32 bits builds of PHP

### ISSUE THREAD

**Issue by stof** [shivammathur/setup-php#326]
**Describe the feature**
Consider providing 32bit builds of PHP

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
Most CI setups of libraries are currently using PHP 64 bits builds. And then, from time to time, they receive issues like https://github.com/scssphp/scssphp/issues/51 reporting bugs affecting only the 32 bits version of PHP.
Being able to have a CI running on a 32 bits build would help avoiding such cases (and preventing regressions).

**Describe alternatives**
- Make php 32 bit die => not something we can do as library maintainers (even though it would simplify our issue...). That's something that the PHP core team would have to do, and I'm not aware of any plan to mandate 64 builds.
- Maintain our own build of PHP for a 32 bits job. Symfony went with this option by using a 32 bit build in its Appveyor setup (but testing 32 bits and Windows at the same time might not be the best choice as we might need a matrix instead). But that requires more work.

**Additional context**

**Are you willing to submit a PR?**
I'm not familiar with the way this project works and where it takes PHP from, so not sure I can help.

**Comment by shivammathur** [comment]
Duplicate #302 
Please refer to https://github.com/shivammathur/setup-php/issues/302#issuecomment-705528321

**Comment by stof** [comment]
@shivammathur sorry, I missing that in the search.
What about including some doc about that rather than relying on a comment in a closed issue ?

**Comment by shivammathur** [comment]
Yes, you are right.
I will add this to the documentation.

**Comment by stof** [comment]
@shivammathur should this issue be re-opened until the doc gets updated so that it does not get forgotten ?

**Comment by shivammathur** [comment]
@stof 
This is now documented in the README.
https://github.com/shivammathur/setup-php#multi-arch-setup
