### ISSUE TITLE
Document default extensions

### ISSUE THREAD

**Issue by stof** [shivammathur/setup-php#327]
**Describe the feature**
It would be great if the doc could show which PHP extensions are enabled by default, when you don't pass anything special in `extensions`.

For instance, I'm unable to tell whether `mbstring` is enabled by default. the readme uses `mbstring` as an example, but my own usages tend to indicate that it is already here by default (I don't include it in my extension list in my work project which has a `ext-mbstring` requirement, and it works).

**Comment by shivammathur** [comment]
Added to wiki
https://github.com/shivammathur/setup-php/wiki
