### ISSUE TITLE
composer-normalize: Permission denied

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#330]
Ping @localheinz 

https://github.com/Slamdunk/laminas-log-extensions/runs/1340047442?check_suite_focus=true

**Comment by localheinz** [comment]
@Slamdunk 

On it!

**Comment by localheinz** [comment]
@Slamdunk  

Should be fixed now, see https://github.com/ergebnis/composer-normalize/releases/tag/2.10.0:

![CleanShot 2020-11-02 at 09 58 05](https://user-images.githubusercontent.com/605483/97848877-05ce4680-1cf2-11eb-9fc9-4b54b1434f10.png)

**Comment by shivammathur** [comment]
@localheinz Thanks for fixing this.

**Comment by localheinz** [comment]
@shivammathur 

You are welcome! I apologize for causing these issues in the first place!

**Comment by Slamdunk** [comment]
I can confirm, bug is fixed now, thanks.
