### ISSUE TITLE
Github oauth token with composer 2

### ISSUE THREAD

**Issue by soyuka** [shivammathur/setup-php#332]
**Describe the bug**
Hi,

I'm trying to setup php (lol) on API Platform. First of all, I love your action workflow it saved me lots of time already! 
I've been observing this error with composer 2:

```
 "Error: Could not authenticate against github.com"
```
[see the phpunit 7.3 run](https://github.com/api-platform/core/runs/1348057191?check_suite_focus=true).

When switching to composer 1, I don't have any errors anymore. Note that I used the recommended `COMPOSER_TOKEN` environment variable and I have this at the root of my `ci.yml` file:

```
env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

(Note that I tried to set this on the `setup-php` section as well).

By the way, on windows I'm reaching token limits and the error is more verbose [see the windows phpunit job on the same run](https://github.com/api-platform/core/runs/1348058247?check_suite_focus=true). I have the impression that the token is not set when using windows. Note that for this error, switching to composer 1 had no effects [see last run](https://github.com/api-platform/core/pull/3814/checks?check_run_id=1348136650).

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows and ubuntu

**PHP versions**
Not really related to php versions, we use all of them but problem occurs for 7.4.

**To Reproduce**
Meh, I guess that this is hard to reproduce. You could setup a big composer, using custom github repositories, without cache and call `composer update` a bunch of time. Note that we're using cache and almost all the packages are read from the cache (except some forked dependencies when we need to maintain pending patches). 

**Expected behavior**
For the github auth token to be used ? 

**Are you willing to submit a PR?**
Of course. I'll look for composer 2 issues regarding authentication, maybe that something is broken there ? On windows though this should be "fixable" as I don't think that the token is read from the environment at all. 

Edit:

Waited for the token to be authorized again (based on time instructions +1 hour?) on windows and I could install.

**Comment by shivammathur** [comment]
@soyuka I have verified that GitHub OAuth token (`github-oauth.github.com`) is set correctly when `COMPOSER_TOKEN` is specified when using composer 2.
Instead of `GITHUB_TOKEN`, please try with a [personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) if the error is there again.
Otherwise might be an issue in composer 2.

**Comment by soyuka** [comment]
Hi, I see that there are lots of issues regarding token authentication with composer 2 on their repository. I'll assume that the issue is on there side and will report if I find a solution. I'll use composer 1 for now.

Thanks!
