### ISSUE TITLE
Sqlite 3.22 instead of desired 3.26

### ISSUE THREAD

**Issue by heddn** [shivammathur/setup-php#333]
**Describe the feature**
The sqlite version installed/bundled seems to be 3.22.0. For Drupal 9, this need to be 3.26+

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
To install Drupal 9, we need to have 3.26 installed.

**Describe alternatives**
I can switch to mysql. Not ideal

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@heddn 
The version of `php-sqlite` extension would be same as the PHP version as it is part of PHP core.

What you are checking is the `sqlite3` library version which is `3.22.0` on `ubuntu-18.04/ubuntu-latest`. I would suggest you use `ubuntu-20.04` which has sqlite3 `3.33.1`.

**Comment by heddn** [comment]
Perfect, that info helps a lot. In my case, it was the solution.
