### ISSUE TITLE
Support for pcntl & posix on Windows

### ISSUE THREAD

**Issue by FoksVHox** [shivammathur/setup-php#334]
**Describe the feature**
I would like to see support for `posix` & `pcntl` extensions on Windows

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
As composer needs `posix` & `pcntl` it would make sense to add support for this. It's already a feature on Ubuntu.

**Describe alternatives**
I have not considered other alternatives 

**Additional context**
The reason why I found this, is that I test my code on both Windows & Linux to make sure that the codebase is compliant with my goal of easy transfer from one OS to another

**Are you willing to submit a PR?**
Yes, if I got a guide on how to do it.

**Comment by shivammathur** [comment]
`posix` and `pcntl` are not supported on `Windows` as they are not designed for it. If you have a php codebase which requires these extensions, it won't be compatible with Windows php. 

On windows users can use WSL to run your code with these extensions and testing on ubuntu then would be okay.
