### ISSUE TITLE
Default xdebug version

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#345]
I think xdebug 3 should be the default on PHP 7.3 or higher (but not 7.2, because it doesn't work with the latest version of phpunit which still supports PHP 7.2).

**Comment by shivammathur** [comment]
@sebastianbergmann Currently there is this error with PHP 7.2 and Xdebug 3. Will a future release of 8.5.x fix this?

```
Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)
```

**Comment by GrahamCampbell** [comment]
I don't think any releases of 8.5.x are planned, other than to fix any security issues (but security issues are few and far between on local dev stuff).

**Comment by GrahamCampbell** [comment]
That said, I would be in support of an additional 8.x release to backport the code-coverage and phpunit changes needed to support xdebug 3.

**Comment by GrahamCampbell** [comment]
Not only would I support it, but I offer my help to get that done.

**Comment by shivammathur** [comment]
@GrahamCampbell After `2.9.0`, it should setup `Xdebug 2.9.8` on `PHP 7.2`.
Please test and let me know

**Comment by GrahamCampbell** [comment]
PHPUnit 8.5 has now been patched to work with Xdebug 3.0. I don't know if we want to change the default back to 3.0.0, or leave it on 2.9.8, since PHPUnit 7.5 still won't work properly.

**Comment by shivammathur** [comment]
Will test this before next release and if it is working on `PHP 7.2`,  I will remove the workaround I added to setup Xdebug 2. 

The `php7.2-xdebug` version on the ubuntu runner will anyway change to Xdebug 3 once it is updated on the PPA. Then the workaround will add 30-40 sec to the runtime for everyone on PHP 7.2, if not removed. Instead I add a `coverage: xdebug2` option for users for PHPUnit 7.

**Comment by GrahamCampbell** [comment]
Cool. :)
