### ISSUE TITLE
Dynamic install extension failed.

### ISSUE THREAD

**Issue by limingxinleo** [shivammathur/setup-php#349]
**Describe the bug**
When I use `sudo sh -c "extension=swoole > /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"` install swoole, it does not works.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

https://github.com/limingxinleo/feishu-sdk/actions/runs/388064548

**Comment by limingxinleo** [comment]
`sudo sh -c "echo extension=swoole >> /etc/php/${{ matrix.php-version }}/cli/php.ini"`

works.

**Comment by shivammathur** [comment]
Yes, the syntax to write to INI file in wrong in your test, you have to echo and then pipe the output to file.
I would recommend
```
echo "extension=swoole" | sudo tee "$(php --ini | grep additional | sed -e "s|.*: s*||")/swoole.ini"
```

**Comment by limingxinleo** [comment]
Thanks
