### ISSUE TITLE
[8.0] The extension is not installed in default directory

### ISSUE THREAD

**Issue by heyanlong** [shivammathur/setup-php#357]
**Describe the bug**
The extension is not installed in the `/usr/lib/php/20200930/` directory

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu 18.04

**PHP versions**

8.0

**To Reproduce**

https://github.com/SkyAPM/SkyAPM-php-sdk/blob/issue-312/.github/workflows/ci.yml

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
`/usr/lib/php/PHP_API_VERSION` for extension directory is not a PHP default but a convention that `ppa:ondrej/php` packages follow.
For PHP 8, `setup-php` will shift to `ppa:ondrej/php` packages once it is pre-installed on the runner.
Also in next release I will add support to install `php-fpm` in setup-php. Till then you can make the following changes

- Install `php-fpm` only when it is not there.
```diff
- sudo apt-get install -y php${{ matrix.php-version }}-fpm
+ if ! [ -e /usr/bin/php-fpm ]; then
+  sudo apt-get install -y php${{ matrix.php-version }}-fpm
+  sudo cp /usr/sbin/php-fpm${{ matrix.php-version }} /usr/bin/php-fpm
+ fi
```
- Do not hard code `conf.d` scan directories.

```diff
- sudo cp e2e/99-skywalking.ini /etc/php/${{ matrix.php-version }}/cli/conf.d/
- sudo cp e2e/99-skywalking.ini /etc/php/${{ matrix.php-version }}/fpm/conf.d/
+ sudo cp e2e/99-skywalking.ini $(php -i | grep additional | sed -e "s|.*=> s*||")
+ sudo cp e2e/99-skywalking.ini $(php-fpm -i | grep additional | sed -e "s|.*=> s*||")
```

**Comment by heyanlong** [comment]
```php
$(php -i | grep additional | sed -e "s|.*=> s*||")
```
Got
```
/etc/php/7.3/cli/conf.d 1
```
So.
```
cp: target '1' is not a directory
```

**Comment by shivammathur** [comment]
After we added pdo_sqlsrv, that adds `pdo_sqlsrv.report_additional_errors` to phpinfo which broke this.
Change it to 
```bash
sudo cp e2e/99-skywalking.ini $(php -i | grep 'additional .ini' | sed -e "s|.*=> s*||")
sudo cp e2e/99-skywalking.ini $(php-fpm -i | grep 'additional .ini' | sed -e "s|.*=> s*||")
```
