### ISSUE TITLE
ZTS builds for linux/macOS

### ISSUE THREAD

**Issue by dktapps** [shivammathur/setup-php#363]
**Describe the feature**
As per title. This action doesn't support ZTS on Unix.

**Version**
2.9.0
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
My project requires threading extensions which require ZTS.

**Are you willing to submit a PR?**
If I had any idea where to start, sure ...

**Comment by shivammathur** [comment]
I'm really sorry, but unless someone funds the following work. I won't be able provide `zts` support on `linux` and `macos`.

- Creating a workflow to build zts PHP.
- Creating a homebrew tap for zts PHP.
- Maintaining these for every patch release of PHP.
