### ISSUE TITLE
PHP8 ldap extension

### ISSUE THREAD

**Issue by alecpl** [shivammathur/setup-php#365]
Sorry, if it's not the proper place to ask. I just started using Github Actions.

I noticed that there is no ldap extension for PHP8 (on ubuntu-latest). Ubuntu has it, and Travis has it, so it shouldn't be a problem to add it?

Here's my job that failed: https://github.com/roundcube/roundcubemail/runs/1541580694

**Comment by shivammathur** [comment]
@alecpl Fixed in https://github.com/shivammathur/php-builder/commit/fe9de0e7bfa7bd9f7a1efa3041a52848dff2a513
Test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/418688590/workflow

**Comment by alecpl** [comment]
Thank you. Confirmed working.
