### ISSUE TITLE
Support for GEOS extension

### ISSUE THREAD

**Issue by BenMorel** [shivammathur/setup-php#367]
**Describe the feature**

Hi, it would be nice to provide support for the [GEOS](https://github.com/libgeos/php-geos) extension!
Thanks for your consideration.

*(note that this extension is not compatible with PHP 8)*

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/setup-php/commit/fd9aae59b05b30e3c6a3c26ffb9dc36c2ed901b8

**Comment by BenMorel** [comment]
Thanks, a lot!

Just out of curiosity: did you update the `2.9.0` tag? I can see that this tag is 18 days old, but contains the latest commits.
Do you update existing tags instead of tagging new releases?

**Comment by shivammathur** [comment]
Yes, I updated the `2.9.0` and `v2` tags. Did not want to create a new release as that would trigger a lot of PRs across projects and with GitHub Actions announcing a four day maintenance, many would have been stuck.

**Comment by BenMorel** [comment]
Makes sense, thanks for your reply!

TIL, I didn't even know you could modify a tag.
