### ISSUE TITLE
Trying to install a non-existent version of PHP does not give an error

### ISSUE THREAD

**Issue by timhunt** [shivammathur/setup-php#368]
**Describe the bug**
Action reports success even if the version of PHP you ask for does not exist.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest (Ubuntu 18.04.5)

**PHP versions**
I was trying to use 7.5, which does not currently exist in the Ubuntu 18.04.5 images.

**To Reproduce**
```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.5
          extensions: mbstring, pgsql, mysqli
```

**Expected behavior**
Either I get PHP 7.5, or the Step fails with a clear error message, so it is easy to see why my build failed.

**Actual behavior**
Script tries to continue with PHP 8.0.0, and then fails later because that is not yet supported, but the error message is not very obvious.

**Screenshots/Logs**
```
Run shivammathur/setup-php@v2
  with:
    php-version: 7.5
    extensions: mbstring, pgsql, mysqli
/bin/bash /opt/hostedtoolcache/linux.sh 7.5 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
/home/runner/work/_actions/shivammathur/setup-php/v2/dist/../src/scripts/common.sh: line 250: php7.5: command not found
✓ PHP Installed PHP 

==> Setup Tools
✓ composer Added composer 2.0.8

==> Setup Extensions
✓ mbstring Enabled
✓ pgsql Enabled
✓ mysqli Enabled

==> Support this project
✓ setup-php https://setup-php.com/support
```

Note, in particular, the like that says `✓ PHP Installed PHP` which is not really right. (The line above is a helpful message.)

**Additional context**
Thank you very much for making this step and sharing it. Obviously, now that I see what the problem is, i can work around it (don't ask for PHP 7.5 when it does not exist!) so fixing this is not urgent. I just wanted to make you aware of the issue I had spotted.

**Are you willing to submit a PR?**
Sorry, I am quite new to GitHub actions. I am unlikely to try to submit a fix any time soon.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/ce02569aea1cd6a8e466c1b108631baca269c4d2

**Comment by timhunt** [comment]
Brilliant! Thank you very much.
