### ISSUE TITLE
Symfony workflow enhancement

### ISSUE THREAD

**Issue by smoqadam** [shivammathur/setup-php#376]
Hi and thanks for this action.

The first time when you run `php bin/phpunit` it tries to install phpunit dependencies which it messes the tests log.
 
![image](https://user-images.githubusercontent.com/1223848/102686012-aedbec80-421f-11eb-844a-a5875cf0d9b7.png)

to avoid that, we should add `php bin/phpunit install` command to `Install Composer Dependencies` step to install dependencies first then run the tests.

**Comment by shivammathur** [comment]
@smoqadam Will you be willing to submit a PR to improve this.

**Comment by shivammathur** [comment]
Fixed in #377
