### ISSUE TITLE
PHP 7.4 unstable?

### ISSUE THREAD

**Issue by glensc** [shivammathur/setup-php#378]
**Describe the bug**

Something changed recently that made PHP 7.4 builds unstable?

Segfaults:
- https://github.com/perftools/xhgui/pull/387/checks?check_run_id=1584843697

Weird pdo_pgsql connect errors:
- https://github.com/perftools/xhgui/runs/1584616273?check_suite_focus=true

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Linux

**PHP versions**

PHP 7.4

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@glensc Please try the following
- Run your tests with `phpunit --verbose`
- Run `phpunit` directly and not through `composer`.
- Run with `xdebug` disabled, you can specify `coverage: none` in setup-php inputs to do this.
- If you are still getting seg faults, try installing debugging symbols and run `phpunit` with `gdb` locally to get the backtrace.

```bash
echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu $(lsb_release -cs) main/debug" | sudo tee /etc/apt/sources.list.d/php-debug.list
sudo apt-get update && sudo apt-get install php7.4 php7.4-dbgsym -y
gdb --args php ./vendor/bin/phpunit --verbose
```

**Comment by glensc** [comment]
@shivammathur but the pipelines worked fine before 2020-12-20, that's why I'm asking has something changed in the packages installed...

**Comment by shivammathur** [comment]
`Xdebug` is now xdebug3. Try with `extensions: xdebug-2.9.8`.

**Comment by glensc** [comment]
and today the pgsql errors are gone, same run, no code changes:
- https://github.com/perftools/xhgui/runs/1584514943

so, must have been a temporary issue in Actions GitHub Runners
