### ISSUE TITLE
PHP 8.0.1

### ISSUE THREAD

**Issue by keradus** [shivammathur/setup-php#394]
Hey,

forgive me if I'm asking a silly question, but I'm new to `shivammathur/setup-php`.

How can I configure shivammathur/setup-php to use 8.0.1 ?

I tried like [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5415/commits/00fa4625f41cc57f5bc9e11b7e38eb7ef0118007) , but it installed 8.0.0 instead

**Comment by shivammathur** [comment]
Patch versions are truncated in the `php-version` input as GitHub Actions images releases automatically update PHP to the latest versions. It usually takes 1-2 weeks for GitHub Actions to update PHP versions to latest patches in their images.

By default setup-php does not upgrade PHP versions installed on the images as it adds to the runtime, so to always get latest patch releases you can set `update` env variable to true.

```
name: Setup PHP
uses: shivammathur/setup-php@v2
with:
  php-version: '8.0'
env:
  update: true
  ```
  
  Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/486340897/workflow

**Comment by keradus** [comment]
big thanks, appreciating the reason and provided solution. works like a charm indeed!
