### ISSUE TITLE
Choose only major ver, like 7.x

### ISSUE THREAD

**Issue by justanotheranonymoususer** [shivammathur/setup-php#395]
As far as I can see, only explicit php version can be chosen, like 7.4.
There's also latest, but it can be of any major version.
It would be nice to be able to say 7.x.

For example, actions/setup-python allows to do this:
`    python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax`
https://github.com/actions/setup-python#usage

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/setup-php/commit/fbc8407035054ffdd2d305af6bd038a3367f1405
`5.x`, `7.x` and `8.x` will now setup PHP `5.6`, `7.4` and `8.0` respectively.
