### ISSUE TITLE
PCOV seems not installed on WINDOWS & PHP 8.0.1

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#398]
https://github.com/paratestphp/paratest/pull/580/checks?check_run_id=1728163264#step:12:20

It seems to me a regression between 8.0.0 and 8.0.1 since it worked on 8.0.0:

https://github.com/paratestphp/paratest/runs/1638994212

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/a83d4379b1200b3d0d19ad4fe0d7a440e00749c1
