### ISSUE TITLE
Composer authentication (Could not authenticate against github.com)

### ISSUE THREAD

**Issue by w00fz** [shivammathur/setup-php#404]
**Describe the bug**

We are constantly getting the infamous ` "Error: Could not authenticate against github.com"` like appears in https://github.com/shivammathur/setup-php/issues/332

I think the problem is that `composer config global` is being used to authenticate as seen for example in https://github.com/shivammathur/setup-php/blob/develop/src/scripts/common.sh#L197 - However as per documentation it should be `composer config --global` ([reference](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth)).

I also think I know why the confusion, and that is because the command `composer global` is legitimate but not related with `composer config --global`.

Does this make sense? Am I on the right track here? We have spent so much time trying to figure out why our commits/PRs constantly fail due to authentication and this is right now the only logical explanation I found.

Places where this is an issue:

1. https://github.com/shivammathur/setup-php/blob/d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e/src/scripts/common.sh#L194
2. https://github.com/shivammathur/setup-php/blob/d2f58713aaf7809d0c4d11e827c9e9dbbc55b34e/src/scripts/common.sh#L197
3. https://github.com/shivammathur/setup-php/blob/a83d4379b1200b3d0d19ad4fe0d7a440e00749c1/src/scripts/win32.ps1#L204
4. https://github.com/shivammathur/setup-php/blob/a83d4379b1200b3d0d19ad4fe0d7a440e00749c1/src/scripts/win32.ps1#L207

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Linux, Ubuntu

**PHP versions**
* 7.3
* 7.4
* 8.0

**Are you willing to submit a PR?**
Of course, I want to make sure this is the right problem.

**Comment by shivammathur** [comment]
@w00fz 
The difference between the 2 commands is, by default:
- `composer global config` updates the `composer.json` in `COMPOSER_HOME`. [Reference](https://github.com/composer/composer/blob/master/src/Composer/Command/GlobalCommand.php#L25)
- `composer config --global` updates the `config.json` in `COMPOSER_HOME`. [Reference](https://github.com/composer/composer/blob/master/src/Composer/Command/ConfigCommand.php#L69)

Upon testing, you are right as `composer` does not use the config in `composer.json` file, but it uses the `config.json` file. So I will change the commands.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/46fc8a2fd7cba50512858026dc8f0947c8a7a0e8

**Comment by w00fz** [comment]
Thank you for the quick fix @shivammathur
