### ISSUE TITLE
PHP 7.3: Missing PDO drivers

### ISSUE THREAD

**Issue by gharlan** [shivammathur/setup-php#406]
**Describe the bug**

In our builds with PHP 7.3, `pdo_mysql` is missing.
Here you can see the output for `php -i | grep pdo`:
- php 7.3 (drivers missing): https://github.com/redaxo/redaxo/pull/4393/checks?check_run_id=1830309908#step:8:1
- php 7.4 (drivers available): https://github.com/redaxo/redaxo/pull/4393/checks?check_run_id=1830309940#step:8:1

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

PHP 7.3 (and 7.4/8.0 without problems)

**To Reproduce**

https://github.com/redaxo/redaxo/blob/f7685d9e88c476892582fdca4c3cbbc8e06a249c/.github/workflows/tests.yml

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Please specify extensions you need in extensions input.
```yml
- name: Setup PHP 
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.3'
    extensions: mysql, pdo_mysql
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/537020472/workflow
