### ISSUE TITLE
Configure extension

### ISSUE THREAD

**Issue by TheLevti** [shivammathur/setup-php#419]
**Describe the feature**

Some extensions are configurable so that non default functionality can be enabled or added. One example is the phpredis extension. When installed from pecl, it asks one whether support for igbinary, msgpack and lzf should be enabled. In addition via build configuration options one can enable additional support for lz4 and zstd via:

```bash
./configure [--enable-redis-igbinary] [--enable-redis-msgpack] [--enable-redis-lzf [--with-liblzf[=DIR]]] [--enable-redis-zstd] ...
```

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

I recently added a pull request to laravel/framework (https://github.com/laravel/framework/pull/36412) to add support for phpredis's serialization/compression support, but could not find the possibility to configure phpredis on installation for the test stage in the pipeline. So now all tests that require this functionality are skipped, because these features are disabled by the default phpredis extension.

**Describe alternatives**

Add the possibility to specify the options when `./configure` is run.

**Additional context**

Already described in detail my concern :).

**Are you willing to submit a PR?**

Unfortunately I see this project the first time and it is a bit overwhelming to understand how it works. I can help of course :)

**Comment by shivammathur** [comment]
@TheLevti 

This feature will be likely in next release.

It can be tracked here - https://github.com/shivammathur/setup-php/discussions/418

**Comment by TheLevti** [comment]
> @TheLevti
> 
> This feature will be likely in next release.
> 
> It can be tracked here - #418

Awesome, thank you!

**Comment by shivammathur** [comment]
Added in `2.11.0`.
Please refer to this [guide](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source) for more details.
