### ISSUE TITLE
Behind the proxy support?

### ISSUE THREAD

**Issue by kevincobain2000** [shivammathur/setup-php#421]
**Describe the feature**

Does it support behind the proxy? 
I have setup on self-hosted ``FROM shivammathur/node`` and workflow is ok when I don't use extensions.

Am I missing something or does it not support behind the proxy?

```
Run shivammathur/setup-php@verbose
/bin/bash /opt/hostedtoolcache/linux.sh 7.4 /home/docker/actions-runner/_work/_actions/shivammathur/setup-php/verbose/dist
..
..
Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 cron amd64 3.0pl1-128.1ubuntu1
  Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
..
```

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Question about behind the proxy and how to set it up

**Describe alternatives**

**Additional context**

I have checked the following items 

- [x] Proxy also added to the Dockerfile for self-hosted for the user `runner` and also tried with global on the env
- [x] Proxy is set properly on the `~/.docker/config.json`
- [x] Setup Job also displays correct proxy

```sh
Runner is running behind proxy server 'http://myproxy......:PORT' for all HTTP requests.
Runner is running behind proxy server 'http://myproxy.....:PORT' for all HTTPS requests.
```

**Are you willing to submit a PR?**
Yes

**Comment by shivammathur** [comment]
@kevincobain2000 
I think you might have to set the proxy for apt in your Dockerfile.
```Dockerfile
RUN echo "Acquire::http::proxy \"$HTTP_PROXY\";\nAcquire::https::proxy \"$HTTPS_PROXY\";" > /etc/apt/apt.conf
```
And then pass `HTTP_PROXY=http://<host>:<port>` and `HTTPS_PROXY=http://<host>:<port>` as build-arg.

https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-the-proxy-for-apt-for-ubuntu-18-04/

Let me know if that helps.

**Comment by kevincobain2000** [comment]
Thanks so much.
I was just doing that as my final attempt and your comment came too. Yes, I can confirm. It's all good now.
