### ISSUE TITLE
phpts env seems not work in unix

### ISSUE THREAD

**Issue by dixyes** [shivammathur/setup-php#429]
**Describe the bug**
phpts env seems not work in unix(macos-latest, ubuntu-latest)

**Version**
all version (v1 v2 master)

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
macos-latest, ubuntu-latest

**PHP versions**
not related

**To Reproduce**
ceshici2 (last job) on https://github.com/dixyes/ghactionsplay/blob/main/.github/workflows/mian.yml#L108

**Expected behavior**
installed PHP cli should be zts version

**Screenshots/Logs**
see: https://github.com/dixyes/ghactionsplay/actions/runs/631344469

**Additional context**
nope

**Are you willing to submit a PR?**

not yet

**Comment by shivammathur** [comment]
Only nts is supported on linux and macOS
https://github.com/shivammathur/setup-php#thread-safe-setup

This may change in future, but I currently have no plans of adding zts support for Linux and macOS.
Please refer to https://github.com/shivammathur/setup-php/issues/363#issuecomment-742884304
