### ISSUE TITLE
Show Git revision of PHP nightly builds

### ISSUE THREAD

**Issue by sebastianbergmann** [shivammathur/setup-php#433]
In situations such as https://github.com/sebastianbergmann/phpunit/issues/4622 it would be nice to know which Git revision of PHP's `master` branch was used to build `8.1`.

For example, instead of
```
==> Setup PHP
✓ PHP Installed PHP 8.1.0
```
the following could be printed
```
==> Setup PHP
✓ PHP Installed PHP 8.1-dev (d5a15d2c919d2ba8f2e81afc0b77f0455d140fbe)
```

**Comment by shivammathur** [comment]
@sebastianbergmann Added in https://github.com/shivammathur/setup-php/commit/0ce7328fd7ef2e70f616a6367689a818f35dec78

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann Added in [0ce7328](https://github.com/shivammathur/setup-php/commit/0ce7328fd7ef2e70f616a6367689a818f35dec78)

Thank you, @shivammathur.
