### ISSUE TITLE
Syntax typo 2.8.0 relnotes

### ISSUE THREAD

**Issue by rvvincelli** [shivammathur/setup-php#438]
**Describe the bug**
In the relnotes of 2.8.0 (see [here](https://github.com/shivammathur/setup-php/releases/tag/2.8.0)) there is a little typo, it should be `tools: composer:1.10.1`, so no space between the tool name and requested version. Thanks for adding this feature!

**Version**
- [ 2.8.0 ]

**Comment by shivammathur** [comment]
@rvvincelli Thanks for reporting this. Fixed :)
