### ISSUE TITLE
Intl sometimes isn't installed despite being reported as installed

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#441]
https://github.com/yiisoft/validator/runs/2237818592

PHP install:

```
==> Setup Extensions
✓ intl Enabled
```

Run tests:

```
1) Yiisoft\Validator\Tests\Rule\GroupRuleTest::testErrorMessage
RuntimeException: In order to use IDN validation intl extension must be installed and enabled.
```

See https://github.com/yiisoft/validator/issues/128

**Comment by shivammathur** [comment]
@samdark 
I was able to reproduce this, but `intl` seems to be loaded correctly after setup-php.
https://github.com/shivammathur/test-setup-php/runs/2271014708?check_suite_focus=true#step:4:40

When the tests run, it fails randomly.
For example, In this workflow run, tests run correctly 3 times and then failed on the 4th run.
https://github.com/shivammathur/test-setup-php/runs/2271014708?check_suite_focus=true

**Comment by shivammathur** [comment]
Seems to be related to the mocked `function_exists` in `UrlTest.php`.
Add `setUp` function which sets `idnFunctionException` to `false` in `RulesTest` and `GroupRuleTest`.

**Comment by samdark** [comment]
OK. Will check that. Thanks!
