### ISSUE TITLE
Generic composer tool support

### ISSUE THREAD

**Issue by SamMousa** [shivammathur/setup-php#442]
**Describe the feature**
Currently all tools need to be manually registered in the code (`tools.ts`) of this package.

**Version**
Feature is not in master

**Underlying issue**
Function `addTools` uses a large switch statement and exact matching.

**Describe alternatives**
I propose adding a prefix for composer; for example: `composer/scrutinizer/ocular` would install the `scrutinizer/ocular` tool.

**Additional context**
This feature would reduce load because specific tools don't need to be added if they are available as composer package.

**Are you willing to submit a PR?**
Yes!

**Comment by shivammathur** [comment]
What would be the advantage in your opinion of adding this feature as compared to adding a step to install composer packages after setup-php.

I think composer prefix would be redundant, `scrutinizer/ocular` or anything matching `user/tool` can be passed to composer.

**Comment by SamMousa** [comment]
Good point on the redundancy of a prefix. My main reason for this feature request is that I need to install global composer package x and don't want to create a PR in this repo for every package.

I'm definitely flexible in the way we organise it, being a part of the tools syntax or a separate part of the config both will work fine and is up to your preference I guess

**Comment by SamMousa** [comment]
https://github.com/shivammathur/setup-php/commit/23393c46d74251fd7b49308b53458d89673adc31

**Comment by shivammathur** [comment]
Added in `2.11.0`.
