### ISSUE TITLE
Support tools: none

### ISSUE THREAD

**Issue by szepeviktor** [shivammathur/setup-php#446]
**Describe the feature**

Please consider supporting `tools: none` when not even Composer is installed.

Currently there is a message with "unknown tool".
https://github.com/shivammathur/setup-php/blob/master/src/tools.ts#L536

Thank you.

**Comment by shivammathur** [comment]
@szepeviktor 
I can add `tools: none`. 

Although, updating composer phar takes only around 100ms... so I kept it as a default, since that is what most workflows did before installing packages.

**Comment by szepeviktor** [comment]
I do some weird run Composer scripts on PHP 7.3 then revert to PHP 7.0 and:
![kép](https://user-images.githubusercontent.com/952007/115520157-2717f480-a28a-11eb-849c-8243cbb9d024.png)

**Comment by shivammathur** [comment]
This is because `TypistTech/imposter` was installed with PHP 7.3. It has a php requirement `php: ^7.3 || ^8.0`.

and reverting to PHP 7.0 gives error, as line 14 of the package is
`protected const DEFAULT_EXCLUDES = ['typisttech/imposter'];`
and class constant visibility modifiers are only supported on PHP 7.1 and above.

So remove `TypistTech/imposter` before running setup-php again with PHP 7.0 and if you need it again with PHP 7.0 try the `0.3.0` version of the package which supports PHP 7.0

**Comment by szepeviktor** [comment]
I need the fruit of `TypistTech/imposter` on PHP 7.0.
Of course I never run Composer on PHP 7.0 again.

Could you help?

**Comment by shivammathur** [comment]
Removing composer won't help here as when you use `TypistTech/imposter` with PHP 7.0, you will get the error.

Downgrading the package using rector might help
**Test workflow**: https://github.com/shivammathur/test-setup-php/actions/runs/770373521/workflow
**rector.php**: https://github.com/shivammathur/test-setup-php/blob/e8bcbf5c101bf97629cdeb7047c65c0e9964e708/rector.php

**Comment by szepeviktor** [comment]
> Removing composer won't help here as when you use `TypistTech/imposter` with PHP 7.0, you will get the error.

I've stated that I will not start Composer again after the PHP downgrade.
And the application does not call imposter.

**Comment by szepeviktor** [comment]
And we could spare 100 ms! 😄

**Comment by shivammathur** [comment]
Added in develop, please test and let me know.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@develop
  with:
    php-version: '7.0'
    tools: none
```

**Comment by szepeviktor** [comment]
It works.
Thank you.

![kép](https://user-images.githubusercontent.com/952007/115552057-242dfb80-a2ac-11eb-91e0-edd3aa0a46d5.png)

**Comment by shivammathur** [comment]
Added in `2.11.0`.

**Comment by szepeviktor** [comment]
Thank you.
