### ISSUE TITLE
macOS builds fail after upgrading from 2.10.0 to 2.11.0

### ISSUE THREAD

**Issue by rogervila** [shivammathur/setup-php#447]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

macOS

**PHP versions**

7.1, 7.2, 7.3, 7.4

**To Reproduce**

https://github.com/rogervila/php-sonarqube-scanner/actions/runs/788373895

**Expected behavior**

The project actions have been triggered after upgrading setup-php from 2.10.0 to 2.11.0
No changes have been made to the GH action's configuration but now it fails because of some missing libraries.

I have re-run the jobs to make sure it was not a corner case.

Maybe the error comes from Homebrew, but I do not have any additional log than the screenshot attached in the next section. 

**Screenshots/Logs**

![image](https://user-images.githubusercontent.com/6053012/116208734-802bd080-a741-11eb-8055-4b7e6e9286e3.png)

**Additional context**

The GitHub project is open-sourced, you might review the past actions.

https://github.com/rogervila/php-sonarqube-scanner 

**Are you willing to submit a PR?**

Yes, if necessary

**Comment by shivammathur** [comment]
@rogervila Fixed in https://github.com/shivammathur/homebrew-php/commit/296fc5bcdcbbce4612f7ad2328951a80452387ca
Please restart your workflow.

**Comment by rogervila** [comment]
Thank you, it works now.
