### ISSUE TITLE
pdo_mysql is no longer installed on windows

### ISSUE THREAD

**Issue by alexander-schranz** [shivammathur/setup-php#448]
**Describe the bug**

It seems like since the latest `2.11` release the pdo extension seems not longer be installed on windows https://github.com/sulu/sulu/runs/2445821141

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1` // not tested

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Windows
 
**PHP versions**

Tested on PHP 7.4

**To Reproduce**

https://github.com/sulu/sulu/pull/5968/files#diff-97081780ba6b676e25ca4729b13035dd4d3fd5f010dd76151028ae821707d3cd (the change here did not fix it we tried to add pdo additional but still errors with that the driver could not be found now)

**Expected behavior**

PDO Driver should be available

**Screenshots/Logs**

> Doctrine\DBAL\Exception\DriverException: An exception occurred in driver: could not find driver

**Additional context**

Run before with 2.10 did work without problems: https://github.com/sulu/sulu/actions/runs/785914450

**Are you willing to submit a PR?**

I did have a look at the changes between the versions but could not find out where the issue could be there where many changes about pdo but couldn't see where the bug could exist. Only line I could think of is that the following check `https://github.com/shivammathur/setup-php/compare/2.10.0...2.11.0#diff-259b230114ff7f4ee1ca525b80925d1fcf8cbea0c841a4cab122dc788e369c4fR92-R95` is now not longer enabling the pdo extension on windows which was done before.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/15c43e89cdef867065b0213be354c2841860869e
Please restart your workflow.

**Comment by alexander-schranz** [comment]
@shivammathur That was fast, the CI works now! Thank you 👍
