### ISSUE TITLE
Can't install imagick on Windows with extension cache

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#455]
**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Windows.

**PHP versions**

PHP 5.6

**To Reproduce**

https://github.com/yiisoft/yii2-app-basic/blob/master/.github/workflows/build.yml#L12

**Expected behavior**

I expect imagick to be available.

**Screenshots/Logs**

- https://github.com/yiisoft/yii2-app-basic/runs/2513275015#step:5:24
- https://github.com/yiisoft/yii2-app-basic/runs/2513275015#step:9:163

**Are you willing to submit a PR?**

No, have no idea how to fix that. Sorry :(

**Comment by shivammathur** [comment]
@mlocati is it possible to call `Install-PhpExtensionPrerequisite` in `Enable-PhpExtension` as well to ensure dependencies are installed before enabling the extension.

**Comment by shivammathur** [comment]
@samdark 

Fixed in https://github.com/shivammathur/setup-php/commit/9882bed06691b3a085010c1602ce43ef18f15c5b and https://github.com/mlocati/powershell-phpmanager/pull/79

Please bump your cache key from `cache-v1` to `cache-v2`, so that imagick dependencies are cached in the next run.
