### ISSUE TITLE
Support for specifying PHP patch versions

### ISSUE THREAD

**Issue by Danon** [shivammathur/setup-php#456]
**Describe the feature**
Specify PHP version to the patch version, like `7.3.36`.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

I have logic that depends on the PHP patch versions, would like to test that.

**Are you willing to submit a PR?**

I don't know how.

**Comment by shivammathur** [comment]
Duplicate #453
