### ISSUE TITLE
Imagick not longer installed correctly

### ISSUE THREAD

**Issue by alexander-schranz** [shivammathur/setup-php#457]
**Describe the bug**

Not sure since when but currently our windows php setup fails with:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\tools\php\ext\imagick (The specified module could not be found.), C:\tools\php\ext\php_imagick.dll (The specified module could not be found.)) in Unknown on line 0
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows

**PHP versions**

7.4

**To Reproduce**

Can be found here: https://github.com/sulu/skeleton/blob/6852160969429b0bc9ff138a50491af237bc4de2/.github/workflows/test-application.yaml#L194

**Expected behavior**

Imagick should correclty be installed.

**Screenshots/Logs**

https://github.com/sulu/skeleton/runs/2566855280

>  !!  PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\tools\php\ext\imagick (The specified module could not be found.), C:\tools\php\ext\php_imagick.dll (The specified module could not be found.)) in Unknown on line 0

**Additional context**
Seems for me it has not todo with changes in in setup-php as there was no release and in at `May 10, 2021` (2 days ago) the pipeline did work like expected. Maybe there were changes in github actions or windows itself that cause now the problem

**Are you willing to submit a PR?**
Would need help to target the issue.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/cache-extensions/commit/470b94d722859ea87e31ec6a93a3773900d6352f

**Comment by alexander-schranz** [comment]
@shivammathur Thx seems like this was already released, is there something we need to change that it is actually used?

**Comment by alexander-schranz** [comment]
Thank you for the quick fix 👍

**Comment by alexander-schranz** [comment]
@shivammathur Do you know if we need to change something, I did restart the CI and it seems still outputting:

>  PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\tools\php\ext\imagick (The specified module could not be found.), C:\tools\php\ext\php_imagick.dll (The specified module could not be found.)) in Unknown on line 0

**Comment by shivammathur** [comment]
This should now be fixed in https://github.com/shivammathur/setup-php/commit/00f360b99d827fc1a61b651240a7cd449a6ddb03, Please re-run your workflow.

The issue in your workflow seems to be coming from `ramsey/composer-install` action which changes the system PATH and broke imagick dependencies after recent changes in how extension dependencies were installed. 

I have changed the setup from adding dependency directory to PATH, to symlinking dependencies in the PHP directory itself. So this should work now.

Test workflow: https://github.com/shivammathur/test-setup-php/runs/2568765241?check_suite_focus=true#step:6:1

**Comment by alexander-schranz** [comment]
@shivammathur Restart did [work now](https://github.com/sulu/skeleton/runs/2582302746) thank you 👍
