### ISSUE TITLE
Odd iconv behavior converting from utf8 to ascii

### ISSUE THREAD

**Issue by KorvinSzanto** [shivammathur/setup-php#459]
**Describe the bug**
I'm trying to get my internationalization/multibyte conversion tests working in github actions using `select-php` and I'm running into a snag where `iconv` is throwing a notice `PHP Notice:  iconv(): Detected an illegal character in input string in Command line code on line 1` when it should be handling the string just fine given the configuration.

I've narrowed this down to a minimal example here: 
- [Workflow](https://github.com/KorvinSzanto/odd-iconv/blob/main/.github/workflows/test-iconv.yml)
- [Example run](https://github.com/KorvinSzanto/odd-iconv/runs/2624719265?check_suite_focus=true)

If I run this workflow locally in what I'd expect to be the same setup I get:
```
❯ php -r '$r = iconv("UTF-8", "ASCII//TRANSLIT", "a 日本人"); echo $r; die($r ? 0 : 1);'
a ???% 
```
with a 0 exit code which is exactly what I'd expect.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest / ubuntu-18.04

**PHP versions**
Tried with PHP 7.2, 7.3, and 7.4

**To Reproduce**
See the example workflow linked above, iconv returns "null" and throws a notice.

**Expected behavior**
I expect `iconv("UTF-8", "ASCII//TRANSLIT", "a 日本人");` to return the string `a ???` without any errors.

**Additional info**
It looks like this particular error is being thrown in response to a `EILSEQ` in the iconv php extension, running iconv directly with the same input seems to raise the same exception with different words: `iconv: illegal input sequence at position 2` so there must be something configured differently in iconv in actions than on my other ubuntu machines.

**Are you willing to submit a PR?**

I'd definitely be willing to fix it, I just haven't narrowed down the issue quite yet.

**Comment by KorvinSzanto** [comment]
Interesting discovery thanks to @wordish it seems that this is an edge case related to the ubuntu based actions shipping with `C.UTF-8` as their default locale. Specifying `LANG=en_US.UTF-8` when running php makes it work like my local machine which just has `en_US.UTF-8` by default.

**Comment by KorvinSzanto** [comment]
If anyone runs into this issue again you can see the fix here: https://github.com/KorvinSzanto/odd-iconv/compare/main..fixed

Given that it's an edge case and something at a higher level than PHP I figure it's not something that should be done as part of `setup-php` so I'm going to close this issue for now.

**Comment by shivammathur** [comment]
The default locale on `ubuntu-20.04` and `ubuntu-18.04` is `C.UTF-8`. So yes, the fix should be to specify `LC_ALL` as required.
More details here https://github.com/actions/virtual-environments/issues/3120#issuecomment-815492874

**Comment by ThorstenSuckow** [comment]
I just ran into the same issue and the suggested fix helped to solve the problem.
What strikes me odd, though, is that my docker container has the same locale (`C.UTF-8`) set and all tests using `iconv` and `\\TRANSLIT` work without any issue.
If anyone can shed some light on this...
