### ISSUE TITLE
New release that supports Composer 2.1.1

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#462]
Composer 2.1.0 contains an annoying bug that doesn't dump the autoloader for dev dependencies when `composer install --no-scripts` is used.

It just released a new version https://github.com/composer/composer/releases/tag/2.1.1. 

When I re-run my jobs, `setup-php` still picks 2.1.0:
```
✓ composer Added composer 2.1.0
```

Will this version be automatically picked up or is it backed in some kind of image? If so, can a new image be created?

**Comment by shivammathur** [comment]
Updated
https://github.com/shivammathur/composer-cache/releases/tag/versions

**Comment by ruudk** [comment]
⚡ ❤️ 🙌

**Comment by 7ochem** [comment]
With my job it still keeps picking 2.1.0:

```
==> Setup Tools
✓ composer Added composer 2.1.0
```

What should I configure to force it to pick 2.1.1?

**Comment by 7ochem** [comment]
Hee! Now it's picking 2.1.1 all of a sudden 😄  Just pressed re-run jobs again and now it works.

```
==> Setup Tools
✓ composer Added composer 2.1.1
```
