### ISSUE TITLE
Modules dir output

### ISSUE THREAD

**Issue by iBotPeaches** [shivammathur/setup-php#463]
**Describe the bug**
Just seeing some output that I assume isn't normal.

```
==> Setup Extensions
find: ‘modules_dir’: No such file or directory
✓ dom Enabled
find: ‘modules_dir’: No such file or directory
✓ curl Enabled
find: ‘modules_dir’: No such file or directory
✓ libxml Enabled
find: ‘modules_dir’: No such file or directory
✓ mbstring Enabled
find: ‘modules_dir’: No such file or directory
✓ zip Enabled
find: ‘modules_dir’: No such file or directory
✓ pcntl Enabled
find: ‘modules_dir’: No such file or directory
✓ gd Enabled
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
```
php-version: 7.4
extensions: dom, curl, libxml, mbstring, zip, pcntl, gd
coverage: none
```

**Expected behavior**
No output warnings

**Screenshots/Logs**
![bug](https://user-images.githubusercontent.com/611784/120784637-4c8b5580-c4fa-11eb-89d8-a16c13c9e42f.PNG)

**Comment by shivammathur** [comment]
@iBotPeaches 
FIxed in https://github.com/shivammathur/setup-php/commit/bb0acc63133a4a64eb0cafb16c403cf8578c3ca5
