### ISSUE TITLE
add 7-zip to windows based php setups

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#465]
**Describe the feature**
since composer 2.1.x the package manager supports [parallel archive extraction when 7 zip is present](https://github.com/composer/composer/pull/9875) on the machine.

would it be possible to make 7z available in the PATH of the system, or at the default location `C:\Program Files\7-Zip`, so composer would by default utilize this parallel extraction capabilities?

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

performance on windows could be improved.

per composer PR the parallel exectution leads to [major performance improvements](https://github.com/composer/composer/pull/9875#pullrequestreview-656591260) 👍 

> Installing the deps of Symfony goes from 49s to 14s with this patch.

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

no idea what needs to be done. I have no experience with this setup.

**Comment by shivammathur** [comment]
7-Zip is pre-installed on the GitHub Runners and is in PATH.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/924351139/workflow
