### ISSUE TITLE
Specify the version of PHP-CS-Fixer

### ISSUE THREAD

**Issue by mlocati** [shivammathur/setup-php#467]
**Describe the feature**
It'd be very useful to specify the version of PHP-CS-Fixer to be used.
People may want to specify the major version (`tools: php-cs-fixer:v2`) or the full version ((`tools: php-cs-fixer:v2.2.20`).

So, we'd have 3 cases:
- `tools: php-cs-fixer` -> setup-php should fetch ` https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/latest/download/php-cs-fixer.phar`
- `tools: php-cs-fixer:v2` -> setup-php should fetch `https://cs.symfony.com/download/php-cs-fixer-v2.phar`
- `tools: php-cs-fixer:v2.3.4` -> setup-php should fetch ` https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.3.4/php-cs-fixer.phar`

**Version**
- [X] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
PHP-CS-Fixer rules and rule sets change across PHP-CS-Fixer versions: we should have a way to be sure about the version we fetch.

**Describe alternatives**
We now have to fetch the PHAR file of PHP-CS-Fixer with a curl call.

**Additional context**

**Are you willing to submit a PR?**
No, sorry :wink:

**Comment by shivammathur** [comment]
@mlocati 
specifying the exact version is already supported.
https://github.com/shivammathur/test-setup-php/actions/runs/942254049/workflow

I will add support for specifying major versions for php-cs-fixer in the next release.

**Comment by mlocati** [comment]
You are very great, @shivammathur !

**Comment by shivammathur** [comment]
@mlocati 
I added support to specify the `major` or `major.minor` version for all tools hosted on GitHub in `2.12.0` release. 

While using this you would have to provide a GitHub OAuth token to avoid getting rate limited when setup-php fetches the exact tag release matching the input. You can use the default [`GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) secret for this.

```yml
- name: Setup PHP with tools
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
    tools: php-cs-fixer:2
  env:
    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1029853981/workflow
