### ISSUE TITLE
PHP 8.1 / Nightly: update status ?

### ISSUE THREAD

**Issue by jrfnl** [shivammathur/setup-php#469]
I have a feeling there's something iffy going on with the PHP 8.1 / nightly version.

## Project 1

When running tests for a particular project locally on PHP 8.1.0-alpha1 as released two weeks ago, I can see a number of tests failing. However, when I run the same tests on GH Actions against PHP 8.1, the tests pass.

If I look at the "Set up PHP" step, it refers to the commit hash https://github.com/php/php-src/commit/e748dcacadd54fa6713076e48bced27992da41f0 of the latest commit to PHP src, so that _seems_ okay.

The failing tests all relate to the PHP 8.1 "passing null to non-nullable internal functions" change and the changes to PHP core for this have gone in a while back, so I would **expect** to see the tests fail on GH Actions too.

## Project 2

Similarly, for another project, when running the project locally on PHP 8.1.0-alpha1, I see a "SomeClass::jsonSerialize() should be compatible with JsonSerializable::jsonSerialize(): mixed" error.

However, when I run the same on GH Actions against PHP 8.1, no such error is displayed, while I would expect it to show (and would hope it would as that's the reason to run against PHP 8.1 - early detection of issues).

**Comment by jrfnl** [comment]
@shivammathur If you like, I can provide you with links to the projects mentioned and test runs and such. Please do let me know whatever information you'd find useful. Also happy to set up test runs with debug settings enabled and such. Just let me know how I can help figure out what's going on.

**Comment by shivammathur** [comment]
@jrfnl

The build is from yesterday's commit https://github.com/php/php-src/commit/e748dcacadd54fa6713076e48bced27992da41f0. I have verified this.

The first error is a deprecation warning [`(E_DEPRECATED)`](https://github.com/php/php-src/blob/e748dcacadd54fa6713076e48bced27992da41f0/Zend/zend_API.c#L462).
By default setup-php uses the production `php.ini` which has `error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT`
Specifying `error_reporting=E_ALL` in `ini-values` should trigger the error.

It might be the same issue with the second one. Please try this and let me know.

**Comment by jrfnl** [comment]
@shivammathur Thanks for getting back to me.

That ini setting is sneaky. I hadn't realized that and wasn't expecting it either as CI is generally used for testing (i.e. dev), so I'd expected `E_ALL`.

I can confirm the other issue is also a deprecation (at least for now).

I guess I'll be updating all workflows for projects I'm involved with to set `error_reporting=E_ALL` for all "experimental" builds.

Thanks for clearing this up!

**Comment by shivammathur** [comment]
@jrfnl Yes, with `setup-php` v3 release, we will shift to the development `php.ini`. Changing it before will be a breaking change. https://github.com/shivammathur/setup-php/issues/450

**Comment by jrfnl** [comment]
@shivammathur I understand and I agree, changing this now would have to be done in a major release. Very happy to see that it will be changed in the future though.
