### ISSUE TITLE
Self-hosted runners fail composer setup if not root user

### ISSUE THREAD

**Issue by lucasmdrs** [shivammathur/setup-php#477]
When using the setup-action on a self-hosted runner, the composer setup fails (without exiting) due to lack of permission. 

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

Docker/Ubuntu

**PHP versions**

Tested with 8.0.8, probably happening with every version

**To Reproduce**

Try to setup-php in a self-hosted agent without root user:
```yaml
- name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          ini-values: memory_limit=-1
          tools: composer:v2
          extensions: apcu, mongodb, redis, sockets, sodium
```

**Expected behavior**

Setup composer properly
```

==> Setup PHP
✓ PHP Installed PHP 8.0.8

==> Setup Tools
✓ composer Added composer 2.1.3

==> Setup Extensions
✓ apcu Enabled
✓ mongodb Enabled
✓ redis Enabled
✓ sockets Enabled
✓ sodium Enabled

==> Add php.ini values
✓ memory_limit=-1 Added to php.ini

==> Support this project
✓ setup-php https://setup-php.com/support
```

**Screenshots/Logs**

```

==> Setup PHP
✓ PHP Installed PHP 8.0.8

==> Setup Tools
tee: /home/runner/.composer/composer.json: Permission denied
chmod: cannot access '/home/runner/.composer/composer.json': No such file or directory

                                                                                               
  [ErrorException]                                                                             
  touch(): Unable to create file /home/runner/.composer/config.json because Permission denied  
                                                                                               

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--] [<setting-key>] [<setting-value>]...

✓ composer Added composer 2.1.3

==> Setup Extensions
✓ apcu Enabled
✓ mongodb Enabled
✓ redis Enabled
✓ sockets Enabled
✓ sodium Enabled

==> Add php.ini values
✓ memory_limit=-1 Added to php.ini

==> Support this project
✓ setup-php https://setup-php.com/support
```

**Additional context**

There's a missing `sudo` in the `tee` command on `commons.sh`
https://github.com/shivammathur/setup-php/blob/0b33ef444fd672ee683e20491b7798d937c69f8c/src/scripts/common.sh#L235-L238
 
But that might not solve the problem, not using `sudo` at all or ensuring that the folder is accessible by the current user would be a better approach.

**Are you willing to submit a PR?**

Yes, once agreed with one of the suggestions above.

**Comment by shivammathur** [comment]
@lucasmdrs 
Fixed in https://github.com/shivammathur/setup-php/commit/36cb9fb0fccf887130d6c5a3d40a3b3479310026
Now the composer's home directory will be owned by the current user, and that should fix this issue.
