### ISSUE TITLE
Support for Blackfire v1 will be dropped on September 1, 2021

### ISSUE THREAD

**Issue by shivammathur** [shivammathur/setup-php#478]
Blackfire `v1` will sunset on September 1, 2021, so `setup-php` will drop support for it and switch to Blackfire `v2`.

The main difference in Blackfire `v2` is that both `agent` and `client` are unified into a single executable `blackfire`. Therefore there is no `blackfire-agent` executable.

No changes will be required in your workflow to set up backfire v2 using `setup-php`. But, if after the `setup-php` step you call specific `backfire` commands, you can refer to this [upgrade guide](https://blackfire.io/docs/up-and-running/agent-upgrade) to make the necessary changes.

**Comment by shivammathur** [comment]
@lolautruche Whenever you have some time, please test the `Blackfire v2` setup using the `blackfire-v2` branch? Also, please check if any changes will be required in the backfire [GitHub Actions docs](https://blackfire.io/docs/integrations/ci/github-actions).

**Comment by lolautruche** [comment]
Hello @shivammathur 

Sorry, I was on vacation so I can review what you already did just now.
Why not merging the `blackfire-v2` branch now? There is no BC break according to what you already implemented.

I only noticed a small mistake in the service start for Linux (gonna do a PR right away).

**Comment by lolautruche** [comment]
https://github.com/shivammathur/setup-php/pull/483

**Comment by shivammathur** [comment]
Awesome, I will merge this in the next release.

**Comment by lolautruche** [comment]
Cool ! Thank you 🙂

**Comment by shivammathur** [comment]
Added in 2.13.0
