### ISSUE TITLE
Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.

### ISSUE THREAD

**Issue by heyanlong** [shivammathur/setup-php#486]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu

**PHP versions**

7.0

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/php-ubuntu/commit/aa5f74dd198545d620b3a8ab60aec5f9492298db
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1161366505/workflow
