### ISSUE TITLE
Allow enabling required PHP extensions only instead of disabling a long list of unwanted PHP extensions

### ISSUE THREAD

**Issue by localheinz** [shivammathur/setup-php#487]
**Describe the feature**

In https://github.com/sebastianbergmann/phpunit/issues/4747, @sebastianbergmann suggests enabling only required PHP extensions for GitHub Actions, in order to have a clear sense of which PHP extensions are required. By default, `shivammathur/setup-php` has a wide range of PHP extensions enabled, and while it is possible to disable and enable extensions at will, disabling extensions can become quite tedious. 

For an example, see https://github.com/sebastianbergmann/phpunit/pull/4759.

Can you think of a way that would keep everything as it is right now (for users who currently use `shivammathur/setup-php` while implicitly depending on PHP extensions), and adding an option of some kind that 

- disables all PHP extensions as far as possible
- allows specifying required PHP extensions only

?

**Version**

- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

This would solve the problem where a project has hidden dependencies on PHP extensions in a specific GitHub Actions workflow.

**Describe alternatives**

We could specify a list of extensions, in the hope that it is exhaustive, and disable and enable at will (see https://github.com/sebastianbergmann/phpunit/pull/4759). 

**Additional context**

n/a

**Are you willing to submit a PR?**

I might try!

Alternatively, I am happy to send some some money your way, if it helps!

**Comment by shivammathur** [comment]
@localheinz 
Currently while removing extensions it does not consider that extensions can depend on other extensions, this somehow skipped my mind while implementing this. 

I will try to fix this - when an extension on which other extensions depend has to be removed, it will be removed along with all the dependent extensions.

Your suggestion about removing all extensions except ones specified is also good. Specifying `none` in extensions input followed by the extensions you need. This will remove all shared extensions except those after none.

Let me know your thoughts.

> Alternatively, I am happy to send some some money your way, if it helps!

That always helps 😀

**Comment by localheinz** [comment]
@shivammathur 

Sounds like a perfect solution for us!

**Comment by williamdes** [comment]
I was thinking `none` was released 😄 
https://github.com/phpmyadmin/sql-parser/runs/3519242419#step:4:15
Early tester it will be ^^

**Comment by shivammathur** [comment]
@williamdes I was a bit busy. Will release this week.

**Comment by shivammathur** [comment]
Released in [`2.14.0`](https://github.com/shivammathur/setup-php/releases/tag/2.14.0)
