### ISSUE TITLE
Installing PHP-FPM fails

### ISSUE THREAD

**Issue by mnapoli** [shivammathur/setup-php#488]
**Describe the bug**

Installing PHP-FPM fails. It used to work until yesterday.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu latest

**PHP versions**

PHP 7.3

**To Reproduce**

https://github.com/brefphp/bref/blob/fed2e89ff8ffe7133235352148ae35cb2134facf/.github/workflows/ci.yml#L41-L49

**Expected behavior**

PHP-FPM installs successfully.

**Screenshots/Logs**

https://github.com/brefphp/bref/pull/1005/checks?check_run_id=3452316902

```
Run sudo apt-get install -y php$version-fpm
Reading package lists...
Building dependency tree...
Reading state information...
php7.3-fpm is already the newest version (7.3.30-1+ubuntu20.04.1+deb.sury.org+1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1f-1ubuntu2.8) but 1.1.1f-1ubuntu2.5 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Additional context**

It started failing since yesterday.

**Are you willing to submit a PR?**

Yes.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/php-ubuntu/commit/da4518ff7c5301c4991e34def1174ecf76ba4045

**Comment by mnapoli** [comment]
Thank you, that fixed the build :)
