### ISSUE TITLE
Windows builds fail for PHP 8.1

### ISSUE THREAD

**Issue by driesvints** [shivammathur/setup-php#489]
**Describe the bug**
Windows builds are currently failing for the PHP 8.1 nightly builds at the setup PHP step with this library. The following error is thrown:

![Screen Shot 2021-09-02 at 10 30 27](https://user-images.githubusercontent.com/594614/131810695-00251212-e1d1-46e1-b6d0-bc5dcf068159.jpg)

It seems a non existing PHP 8.1.0RC2-dev version is used even though that's not been released yet. We're at PHP 8.1.0 Beta3 right now: https://www.php.net/archive/2021.php#2021-08-19-1

You can see the builds fail here: https://github.com/laravel/framework/pull/38404/checks?check_run_id=3493365859

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Microsoft Windows Server 2019

**PHP versions**
PHP 8.1 nightly builds

**To Reproduce**
This part of our GitHub Actions setup: https://github.com/laravel/framework/blob/fa1c2f51a69cbe759ffcd16ad8250ef045a6537b/.github/workflows/tests.yml#L89-L118

**Expected behavior**
I expect PHP 8.1 Beta 3 to be loaded but it tries to setup a non existing PHP 8.1.0RC2-dev

**Additional context**
I discovered this while working on a PR to fix PHP 8.1 issues in the Laravel framework's 8.x branch: https://github.com/laravel/framework/pull/38404 

**Are you willing to submit a PR?**
I'm afraid I don't know enough about this library to submit a PR.

**Comment by driesvints** [comment]
Right after seeing this I tried re-running the main build on 8.x and it seems that all of our PHP 8.1 builds across all branches are now failing. I'll revert our PHP 8.1 builds for now so pull requests from community members etc don't fail.

https://github.com/laravel/framework/runs/3493571398

**Comment by shivammathur** [comment]
@driesvints I have reported the bug to `powershell-phpmanager` package that setup-php uses for Windows.
https://github.com/mlocati/powershell-phpmanager/issues/87

**Comment by driesvints** [comment]
Thanks @shivammathur. I was in doubt where the issue was present but since it was happening in the shivammathur/setup-php step I reported it here. Thanks for finding the correct location.

**Comment by shivammathur** [comment]
@driesvints No worries, Till there is a fix in `powershell-phpmanager`, I have built PHP 8.1 with the PHP version patched to `8.1.0-dev`, which is parsed correctly. So, it should work again.

**Comment by driesvints** [comment]
Seems like @mlocati is already on it 🙂

**Comment by mlocati** [comment]
I should have fixed the issue. Please keep me updated.

**Comment by shivammathur** [comment]
@mlocati Thanks, works now.
