### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#490]
Is it possible to have PHP 8.1 enable PHP 8.1.0-RC1, and 8.2 enable the nightly builds from the master branch? I think this now makes the most sense out of the box. NB The master branch of php/php-src are now PHP 8.2, with PHP 8.1 now spun off to its own branch.

**Comment by shivammathur** [comment]
8.1 is a nightly from PHP-8.1 branch already and should be more stable than the tagged RC1.

8.2 should work now, I have added builds for all OS. Updated docs will be in the next release.

**Comment by GrahamCampbell** [comment]
Is there a way to get the RC builds without having to hard code RC1 in the tests? I'd rather get those than the 8.1 nightlies (and then have the same code get the stable builds once they are out)

**Comment by shivammathur** [comment]
@GrahamCampbell specifying `php-version: 8.1` right now gives RC builds, you do not have to specify RC. When stable 8.1 will be released it will start setting up the stable version.

**Comment by GrahamCampbell** [comment]
Perfect. 👌
