### ISSUE TITLE
a terminal is required to read the password

### ISSUE THREAD

**Issue by jay-oswald** [shivammathur/setup-php#493]
**Describe the bug**
When running on a github runner everything works, however when I moved over to a self-hosted runner it threw this error, logs from github action below

```
Run shivammathur/setup-php@v2
  with:
    php-version: 7.4
/usr/bin/bash /home/github/actions-runner/_work/_tool/linux.sh 7.4 /home/github/actions-runner/_work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
✗ PHP Could not setup PHP 7.4
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [x] Self Hosted
Works on GitHub Hosted, errored on Self Hosted

**Operating systems**
Self Hosted runner is running on Ubuntu 20.04

**PHP versions**
7.4 - Only one I've tried, since it works well for GitHub runners, and is the company I work for current version

**To Reproduce**
The only step above this one is: actions/checkout@v2
Later down we do have burnett01/rsync-deployments@4.1 however it runs its build before checkout

**Comment by shivammathur** [comment]
Please configure password-less sudo on your self-hosted runner as documented in this guide

https://github.com/shivammathur/setup-php/wiki/Requirements-for-self-hosted-runners#linuxwsl

**Comment by jay-oswald** [comment]
I had done that originally, and I must have missed a step, I re-did it and that specific error has gone away, but its still failing, this time with no real error

```
/usr/bin/bash /home/github/actions-runner/_work/_tool/linux.sh 7.4 /home/github/actions-runner/_work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
✗ PHP Could not setup PHP 7.4
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Comment by jdaiv** [comment]
As a quick follow up, we've fixed the sudoers file for the runner. But we're still getting just a `Could not setup PHP 7.4` error.

Below are the raw logs:
```
2021-09-15T03:33:41.5490601Z [command]/usr/bin/bash /home/github/actions-runner/_work/_tool/linux.sh 7.4 /home/github/actions-runner/_work/_actions/shivammathur/setup-php/v2/dist
2021-09-15T03:33:41.5494350Z 
2021-09-15T03:33:41.5496894Z [90;1m==> [0m[37;1mSetup PHP[0m
2021-09-15T03:33:43.1077093Z [31;1m✗ [0m[34;1mPHP [0m[90;1mCould not setup PHP 7.4[0m
2021-09-15T03:33:43.1114464Z ##[error]The process '/usr/bin/bash' failed with exit code 1
```

**Comment by jdaiv** [comment]
I did a bit of digging on this and looks like we're missing a package. I edited the action to log errors and this was the result:

```
==> Setup PHP
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
python3: can't open file '/usr/sbin/merge_status': [Errno 2] No such file or directory
update-alternatives: error: update-alternatives: error: update-alternatives: error: update-alternatives: error: update-alternatives: error: alternative path /usr/bin/php7.4 doesn't existupdate-alternatives: error:
alternative path /usr/bin/phar7.4 doesn't exist
alternative path /usr/bin/phar.phar7.4 doesn't exist
alternative path /usr/bin/php-cgi7.4 doesn't exist
alternative path /usr/bin/phpdbg7.4 doesn't exist
alternative path /usr/bin/php-config7.4 doesn't exist
update-alternatives: error: alternative path /usr/bin/phpize7.4 doesn't exist
update-alternatives: error: alternative path /usr/lib/cgi-bin/php7.4 doesn't exist
✗ PHP Could not setup PHP 7.4
```

One `apt install zstd` later and we're fixed!

**Comment by shivammathur** [comment]
Please specify runner as `self-hosted`.
https://github.com/shivammathur/setup-php#self-hosted-setup

```
  - name: Setup PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: 7.4
    env:
      runner: self-hosted # Specify the runner.
```

**Comment by jdaiv** [comment]
Ah, whoops, missed that. Crazy that they don't let you automatically detect what environment you're running on. For what it's worth it was running smoothly without that now.

Thanks for the help!
