### ISSUE TITLE
Setup tools: php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by chintandave-simformsolutions** [shivammathur/setup-php#495]
**While using laravel-mysql.yml with act throws error** 

[Testing Laravel with MySQL/Laravel (PHP 7.2)-1]   ❗  ::error::The process '/usr/bin/bash' failed with exit code 1
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
[Testing Laravel with MySQL/Laravel (PHP 7.2)-1]   ❌  Failure - Setup PHP, with composer and extensions
[PHP Lint/PHP Lint                             ]   ⚙  ::set-output:: php-version=
| ✓ PHP Installed PHP 
| 
| ==> Setup Tools
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
[Testing Laravel with MySQL/Laravel (PHP 7.4)-3]   ⚙  ::set-output:: php-version=
| ✓ PHP Installed PHP 
| 
| ==> Setup Tools
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| ✓ composer Added composer 2.1.8
| 
| ==> Setup Extensions
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
| /run/act/actions/shivammathur-setup-php@master/dist/../src/scripts/common.sh: line 107: ext_dir: parameter null or not set

**Version**

- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted using act

**Operating systems**

Ubuntu 20.4

**PHP versions**

php-7.2, php7.3, php-7.4

**To Reproduce**
Use the yml file [laravel-mysql.yml](https://github.com/shivammathur/setup-php/blob/master/examples/laravel-mysql.yml)

**Comment by shivammathur** [comment]
@chintandave-simformsolutions 
Duplicate #494

It is recommended to use shivammathur/node images for running setup-php on act.
https://hub.docker.com/r/shivammathur/node
```bash
act -P ubuntu-latest=shivammathur/node:latest
```
Refer to: https://github.com/shivammathur/setup-php#local-testing-setup

for other images, you will have to specify the runner as self-hosted.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  env:
    runner: self-hosted
  with:
    php-version: '8.0'
```
