### ISSUE TITLE
PDO_OCI for PHP8

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#496]
**Describe the feature**

Could not install pdo_oci on PHP 8.0.10

**Version**

- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Comment by samdark** [comment]
https://github.com/yiisoft/db/pull/238/checks?check_run_id=3641368345

**Comment by shivammathur** [comment]
@samdark
I could not reproduce the issue.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1249207383/workflow

Extensions `pdo_oci` and `oci8` should install correctly for all PHP versions. Might be a temporary issue.

Can you switch to `shivammathur/setup-php@verbose`, and if it fails again, provide me the logs.

**Comment by terabytesoftw** [comment]
> @samdark
> I could not reproduce the issue.
> Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1249207383/workflow
> 
> Extensions `pdo_oci` and `oci8` should install correctly for all PHP versions. Might be a temporary issue.
> 
> Can you switch to `shivammathur/setup-php@verbose`, and if it fails again, provide me the logs.

When I put the verbose version it works perfectly, when I put the normal version it doesn't work, here you can see it. 

`Verbose work:`

https://github.com/terabytesoftw/db/runs/3641761681?check_suite_focus=true

`No verbose:`

https://github.com/terabytesoftw/db/runs/3641793839?check_suite_focus=true

**Comment by shivammathur** [comment]
@samdark @terabytesoftw Recent release broke cache support. Fixing it now.

**Comment by shivammathur** [comment]
Fixed in 48aac87d46a6be92606792479960dc0bbb325532
Please test and let me know.

**Comment by samdark** [comment]
Worked. Thank you very much for fixing it so fast 👍 

https://github.com/yiisoft/db/runs/3644169663
