### ISSUE TITLE
Refactor: Use parameterised testing using `jest.it.each`

### ISSUE THREAD

**Issue by shivammathur** [shivammathur/setup-php#506]
`jest.it.each` reduces the boilerplate test code and improves the readability and maintainability.
Currently `config`, `tools` and `coverage` tests use `jest.it.each`. The same can be done for `utils`, `extensions` and `install` tests.

Ref:
- https://www.npmjs.com/package/jest-each
- https://elfi-y.medium.com/reduce-boilerplate-test-code-with-jest-it-each-30a0eec9776d

**Comment by aneeshrelan** [comment]
Can you please assign this to me? I'll try to put something up for this

**Comment by shivammathur** [comment]
Awesome, assigned.

**Comment by aneeshrelan** [comment]
Have raised #516 for `install.test.ts`

**Comment by aneeshrelan** [comment]
Yup. I can. But I won't have time this weekend. Next week I can spend some time
