### ISSUE TITLE
ext-sockets failing

### ISSUE THREAD

**Issue by njgreb** [shivammathur/setup-php#512]
**Describe the bug**
Our project uses "php-amqplib/php-amqplib" which requires the sockets extension.  I have enabled it using `extensions: sockets` and I see the logging showing "sockets enabled".  When the system gets to doing a composer install though, I get the following error:
```
Problem 1
    - php-amqplib/php-amqplib is locked to version v3.0.0 and an update of this package was not requested.
    - php-amqplib/php-amqplib v3.0.0 requires ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.
```

**Version**
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu

**PHP versions**

v8

**To Reproduce**

Make sure your project requires: "php-amqplib/php-amqplib": ">=3.0"
runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: sockets
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v5
    - name: Generate key
      run: php artisan key:generate
      run: vendor/bin/phpunit

**Expected behavior**

Tests will run

**Screenshots/Logs**

Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - php-amqplib/php-amqplib is locked to version v3.0.0 and an update of this package was not requested.
    - php-amqplib/php-amqplib v3.0.0 requires ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.

To enable extensions, verify that they are enabled in your .ini files:

**Additional context**

**Are you willing to submit a PR?**

Yes

**Comment by shivammathur** [comment]
Setup PHP installs PHP directly on the GitHub Actions container, so other actions which spin up their own containers are not compatible with it. Please run composer directly instead of using `php-actions/composer`. That would work and also actually use the composer dependency cache you set up in the above step.

```yml
- name: Composer Install
  run: composer install --prefer-dist
```

**Comment by njgreb** [comment]
That worked perfectly.  Thank you.
