### ISSUE TITLE
Problem DST Root CA X3 php 5.6-7.1. in windows-latest.

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#517]
**Describe the feature**
Problems with the certificate in PHP from 5.6 to 7.1, from 7.2 to 8.0, i could solve it, I know it is not a problem of your great extension but if you could help solve it or some suggestion would be great, from 7.2 onwards it works without problems greetings and really thanks for helping the whole community PHP.

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/yii2-app-basic/runs/3775140526?check_suite_focus=true

**Comment by shivammathur** [comment]
@terabytesoftw 

Thanks for reporting this,

This should be fixed in https://github.com/shivammathur/setup-php/commit/a7f90656b3be3996d1ec5501e8e25d5d35aa9bb2

Please re-run your workflow.
