### ISSUE TITLE
PHPUnit declared in matrix not used for phpunit tests

### ISSUE THREAD

**Issue by afragen** [shivammathur/setup-php#529]
**Describe the bug**
I have a matrix for php version and phpunit versions. https://github.com/afragen/git-updater-gitea/blob/main/.github/workflows/wp-phpunit.yml

In reviewing the Actions on a commit. It seems that the correct version of phpunit is loaded, however it isn't used in the phpunit tests.

What am I missing?

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-18.04

**PHP versions**

7.2, 7.3, 7.4

**To Reproduce**

https://github.com/afragen/git-updater-gitea/blob/main/.github/workflows/wp-phpunit.yml

**Expected behavior**
I expect the phpunit version in the matrix is used for testing. I'm not certain where the version of PHPUnit is pulled from.

**Screenshots/Logs**

<img width="919" alt="screenshot_128" src="https://user-images.githubusercontent.com/1296790/141854735-9c43aa27-db87-4461-b0e1-6cbeeb39d09b.png">

<img width="919" alt="screenshot_129" src="https://user-images.githubusercontent.com/1296790/141854787-bdfa1e38-26b2-46a1-b3e6-5b4233c5df77.png">

**Comment by shivammathur** [comment]
Should be fixed by https://github.com/afragen/git-updater-gitea/pull/2
