### ISSUE TITLE
PHPUnit Polyfills appear to no longer be loading properly with this action

### ISSUE THREAD

**Issue by Crabcyborg** [shivammathur/setup-php#531]
First of all, thank you for this action! It generally works really well. I'm not sure what the issue is, and I'd love your insight here.

**Describe the bug**
I haven't seen anyone else reporting recent issues but it seems like this broke overnight.

I'm seeing the error:
```
Error: The PHPUnit Polyfills library is a requirement for running the WP test suite.
If you are trying to run plugin/theme integration tests, make sure the PHPUnit Polyfills library (https://github.com/Yoast/PHPUnit-Polyfills) is available and either load the autoload file of this library in your own test bootstrap before calling the WP Core test bootstrap file; or set the absolute path to the PHPUnit Polyfills library in a "WP_TESTS_PHPUNIT_POLYFILLS_PATH" constant to allow the WP Core bootstrap to load the Polyfills.
```

When our action runs. I have yoast/phpunit-polyfills listed under tools and it was previously working for nearly two months prior to this without changes to our workflow.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-18.04

**PHP versions**
I have the following matrix and both are failing.

```
          - php: 7.3
            wordpress: master
            phpunit: 7.5.20
            multisite: 0
          - php: 7.2
            wordpress: master
            phpunit: 7.5.20
            multisite: 1
```

I haven't confirmed if it's breaking because something changed in WordPress master. I'm thinking that might be it.

**To Reproduce**
My phpunit.yml includes:
```
- uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit:${{ matrix.phpunit }}, yoast/phpunit-polyfills
```

**Expected behavior**
That PHPUnit runs

**Comment by shivammathur** [comment]
@Crabcyborg 

Please test with only `phpunit-polyfills` in the tools input as it will install the required PHPUnit version.
```yml
`tools: phpunit-polyfills`
```

**Comment by jrfnl** [comment]
@Crabcyborg Is you workflow public ? If so, would you mind posting a link to it ?

**Comment by Crabcyborg** [comment]
> Please test with only `phpunit-polyfills` in the tools input as it will install the required PHPUnit version.
> 
> ```yaml
> tools: phpunit-polyfills
> ```

@shivammathur thank you, that works great and simplifies the matrix a bit too, nice to know!

> @Crabcyborg Is you workflow public ? If so, would you mind posting a link to it ?

@jrfnl yes, the file is here https://github.com/Strategy11/formidable-forms/blob/v5.0.13.1/.github/workflows/phpunit.yml

I'll close this. Not sure why it just started breaking out of the blue though, if there is some sort of bug to still fix somewhere. I'm good though!

Thank you!! 🥳

**Comment by jrfnl** [comment]
@Crabcyborg You may have missed the blogpost which announced changes to the WP Core test suite. These changes also apply to plugins/themes running integration tests.

I'd highly recommend reading the blogpost and following the advise given there on how to upgrade your test suite. If you still have questions after that, feel free to ping me (here or in WP Slack).

https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/

**Comment by jrfnl** [comment]
@Crabcyborg Oh and you may also want to have a read through this blogpost as the branch name for the WP git default branch has changed: https://make.wordpress.org/core/2021/11/10/default-git-branch-for-wordpress-wordpress-develop/

**Comment by Crabcyborg** [comment]
> @Crabcyborg Oh and you may also want to have a read through this blogpost as the branch name for the WP git default branch has changed: https://make.wordpress.org/core/2021/11/10/default-git-branch-for-wordpress-wordpress-develop/

That's useful to know, thanks @jrfnl!

As for the polyfill issue that broke for us September 24, 3 days before that blog post. I had implemented the code you see above then, that worked at the time. It only broke again a second time today, ha.

**Comment by jrfnl** [comment]
> As for the polyfill issue that broke for us September 24, 3 days before that blog post. I had implemented the code you see above then, that worked at the time. It only broke again a second time today, ha.

Yeah, well, we had to do a very closely coordinated effort to try and do the backports and publish the post around the same time. The whole project took over two months to get approved & committed 😂 

Not sure why it broke a second time, may have something to do with the branch rename, may have something to do with a change in your tests only now exposing that the other changes needed hadn't been made yet.

Hope the blogpost clarifies things and will help you get it all working properly again.

**Comment by jrfnl** [comment]
P.s.: one thing I already noticed which you'll need to change is the loading order in your test bootstrap: load the `vendor/autoload.php` first and only load the WP test `bootstrap.php` file _after_ that.
Other than that, at the very least, the fixtures will need updating.

**Comment by Crabcyborg** [comment]
> load the vendor/autoload.php first and only load the WP test bootstrap.php file after that.

@jrfnl got it, I've changed that around now!

Thanks for your advice here!
