### ISSUE TITLE
sqlsrv installation stopped working on PHP 7.3

### ISSUE THREAD

**Issue by hrach** [shivammathur/setup-php#536]
**Describe the bug**
Suddenly installation on sqlsrv extension stopped working on PHP 7.3

**Version**
- [x] `v2`

**Runners**
- [x] GitHub Hosted

**Operating systems**
Linux.

**PHP versions**
7.3

**To Reproduce**
https://github.com/nextras/orm/blob/main/.github/workflows/build.yml

**Expected behavior**
sqlsrv driver is installed

**Screenshots/Logs**
```
✗ sqlsrv-5.10.0 Could not install sqlsrv-5.10.0 on PHP 7.3.33
```
https://github.com/nextras/orm/runs/4433963038?check_suite_focus=true#step:7:25

**Additional context**
It worked before.

**Are you willing to submit a PR?**
No idea how to fix.

**Comment by shivammathur** [comment]
@hrach 
PECL extension versions do not have hyphen in them, so `sqlsrv-5.10.0-beta2` should be `sqlsrv-5.10.0beta2`
Ref: https://pecl.php.net/package/sqlsrv

That aside, I have added a patch to handle this typo in https://github.com/shivammathur/setup-php/commit/a274bd910ac3c4911b8c7859409efa4059fdd2a4

Please restart your workflow, it should work correctly now. [Test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/1551710409/workflow)
If you want you can remove the hyphen in `5.10.0-beta2` to be `5.10.0beta2`.

**Comment by hrach** [comment]
Thanks a lot. What I didn't understand:
- why it previously worked: https://github.com/nextras/orm/runs/4110054736?check_suite_focus=true
- why it worked everywhere but PHP 7.3
