### ISSUE TITLE
The term 'Get-Php' is not recognized as a name of a cmdlet, function, script file, or executable program

### ISSUE THREAD

**Issue by driesvints** [shivammathur/setup-php#537]
**Describe the bug**

We sometimes get the following error on Windows:

> The term 'Get-Php' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

See https://github.com/laravel/framework/runs/4457465095?check_suite_focus=true

I found https://github.com/shivammathur/setup-php/issues/129 but the above seems directly related to setup-php if I'm correct?

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
windows server 2019: https://github.com/laravel/framework/blob/8.x/.github/workflows/tests.yml#L98

**PHP versions**
PHP 8.0 in the GHA although I don't think it matters?

**To Reproduce**
https://github.com/laravel/framework/blob/8.x/.github/workflows/tests.yml#L97-L123

**Expected behavior**
I expect the build to succeed.

**Additional context**
Another issue we're facing: https://github.com/shivammathur/setup-php/issues/538

**Are you willing to submit a PR?**
I don't know how to solve this.

**Comment by shivammathur** [comment]
GitHub releases is failing intermittently, so on Windows setup-php is not able to download PhpManager, and that causes the `Get-Php is not recognised` error.

I have created a support ticket, and there is a GitHub discussion thread about this here: https://github.com/github/feedback/discussions/8535

https://status.setup-php.com/incidents/v4v919x59y6q

**Comment by driesvints** [comment]
Thanks a lot for pointing that out @shivammathur 👍

**Comment by shivammathur** [comment]
I have pushed a patch https://github.com/shivammathur/setup-php/commit/bbba8d75a6d5a197ff362b93c18c9a7174cf8c2d to fix this until it is fixed upstream.

Please restart your workflows and let me know if there are any errors.

**Comment by shivammathur** [comment]
This should be fixed now, let me know if you get the errors again.

**Comment by driesvints** [comment]
A retrigger showed that it's now passing. Thanks @shivammathur!

**Comment by mfn** [comment]
ho.ly.shoe: you did set up a status page for `setup-php` 😱
