### ISSUE TITLE
setup-php seems to ignore PECL package version constraints?

### ISSUE THREAD

**Issue by asgrim** [shivammathur/setup-php#542]
Our build depends on a PECL package that does not yet have a PHP 8.1 release ( see http://pecl.php.net/package/scoutapm ), but somehow the action is installing the PECL package, e.g.:

```
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.1"
          tools: pecl
          extensions: scoutapm
```

Manages to install the `scoutapm` library:

```
Run shivammathur/setup-php@v2
/usr/bin/bash /opt/hostedtoolcache/linux.sh 8.1 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
✓ PHP Found PHP 8.1.0

==> Setup Tools
✓ composer Added composer 2.1.14
✓ PECL Added PECL 1.10.12

==> Setup Extensions
✓ scoutapm Installed and enabled

==> Setup Coverage
✓ none Disabled Xdebug and PCOV

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

If I try to install it locally (running PHP 8.1), I am met with an expected error:

```
$ sudo pecl install scoutapm
pecl/scoutapm requires PHP (version >= 7.1.0, version <= 8.0.99), installed version is 8.1.0
No valid packages found
install failed
```

**Comment by shivammathur** [comment]
Yes, setup-php does ignores the PHP versions warnings. We install extensions by force for the following reasons
- Downgrading an extension when a newer version is already installed requires installing by force.
- To support extensions with pre-release versions of PHP.

In the next release, I will try to think of ways to avoid this for stable PHP versions. Currently, you can fix this in 2 ways for your use case.
- You can change your workflow matrix to only install `scoutapm` for PHP 8.0 and lower until you add support for 8.1.
- or you can add a check for PHP version in your config.m4 similar to how [Xdebug](https://github.com/xdebug/xdebug/blob/master/config.m4#L16) does it and hard-fail to compile when not supported.

**Comment by asgrim** [comment]
That makes sense - thank you!
