### ISSUE TITLE
Disable coverage by default

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#544]
**Describe the feature**
First of all, thank you for this amazing action 🙌 

Xdebug and PCOV are enabled by default causing a lot of jobs to run slower than needed. This can easily be disabled with `coverage: none`. But the problem is, most people copy the default snippet and don't realize it.

I just discovered that my phpunit job runs 3 minutes faster, composer-require-checker 3 minutes faster and probably more tools as well. 

Now multiply this by ±50-100 builds / day a year long for our organization. That's a lot of wasted CPU time and thus CO2 emissions 🌏 . 

I understand you cannot just change the default value, but maybe good to change this for the next major version?  🙏 

And maybe we can update the readme so that every snippet has `coverage: none`? If people need coverage, they know how and what to alter.

**Comment by shivammathur** [comment]
Yes, this is planned for `v3` and is noted in the to-do list we have for it.
https://github.com/shivammathur/setup-php/projects/1#column-6419035 

Xdebug is enabled by default in the GitHub Action Ubuntu images, not something that setup-php enables. If you would like that to change, please create an issue in [actions/virtual-environments](https://github.com/actions/virtual-environments). 
With v3 if this is not changed on the images, setup-php will disable Xdebug.

Adding `coverage: none` to every snippet is not a good idea as those snippets might be used in workflows that collect code coverage and this would cause confusion. I have tried to improve the coverage section and make this more clear in https://github.com/shivammathur/setup-php/commit/7dadf1bf21e925ed3ae1f75c9849ad283eba735.
