### ISSUE TITLE
More fine-grained support for picking the composer version

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#545]
**Describe the feature**

Pin to a specific major.minor.patch version of composer, or major.minor. Composer 2.2.0 has some regressions, so I'd like to stick with the latest 2.1.x series version.

**Version**
- [ ] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@GrahamCampbell 

This is already supported.
https://github.com/shivammathur/setup-php#wrench-tools-support

You can specify the composer's exact semver version `tools: composer:2.1.14` or `major.minor` version `tools: composer:2.1`.
If you use `major.minor` notation for the version, please specify `COMPOSER_TOKEN` environment variable using the `GITHUB_TOKEN` secret to avoid rate GitHub API rate limiting.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1612081597/workflow

**Comment by GrahamCampbell** [comment]
So it is! Thanks. ❤️
