### ISSUE TITLE
The action is a lot slower on macOS than on Linux or Windows

### ISSUE THREAD

**Issue by stof** [shivammathur/setup-php#546]
**Describe the bug**
The setup-php runs a lot slower on macOS than on Windows and Linux.
The setup-php action took a few seconds on Ubuntu, 28s on Windows and 1m27s on macOS.

It might make sense to investigate whether the performance can be improved there.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
macos-latest, ubuntu-latest and windows-latest

**PHP versions**
php 8.0

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
See https://github.com/scssphp/scssphp/runs/4621856124?check_suite_focus=true for an example job

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Yes, there are 2 reasons for that
- The macOS runners are hosted on 3-core 64-bit Ivybridge which is around 2012 hardware and is very slow, if you use a self-hosted runner on newer hardware, it can be a lot faster.

- We use a cache for PHP builds on Ubuntu, so the setup turns into a single fetch, extract and configure operation which is a lot faster than installing all the packages using `apt`. Implementing a similar cache for macOS is planned for `v3`, but this would add more maintenance work and for that, the project needs more sponsorship.
