### ISSUE TITLE
Incorrect openssl.cnf location for PHP 7.3 images

### ISSUE THREAD

**Issue by stronk7** [shivammathur/setup-php#564]
**Describe the bug**
PHP with openssl comes with the following default paths to locate the (mandatory for some operations), openssl.cnf file:

* PHP 7.4 and up:
    * C:\Program Files\Common Files\SSL\openssl.cnf (x64)
    * C:\Program Files (x86)\Common Files\SSL\openssl.cnf (x86)
* prior to PHP 7.4.0, C:\usr\local\ssl\openssl.cnf.

(source: [PHP Manual: OpenSSL >Installing/Configuring](https://www.php.net/manual/en/openssl.installation.php))

And those are the values, that the snapshots built here have. From [this run](https://github.com/stronk7/moodle/actions/runs/1826460088), that is plenty of var_dump() information, I can see that:
* The 7.3 job shows (phpinfo): `Openssl default config => C:\usr\local\ssl/openssl.cnf`
* The 8.0 job shows (phpinfo): `Openssl default config => C:\Program Files\Common Files\SSL/openssl.cnf`

So, all right so far.

The problem is that the `C:\usr\local\ssl/openssl.cnf` file DOES NOT exist in the 7.3 environment, only the `C:\Program Files\Common Files\SSL/openssl.cnf` is there. The [job above](https://github.com/stronk7/moodle/actions/runs/1826460088) also tries to `var_dump()` the contents of the 2 files and only the later is there, both in the 7.3 and 8.0 snapshots.

And that leads to all sort of failures with various openssl operations requiring a valid openssl.cnf, for example:
```
PHP Warning:  openssl_pkey_export(): cannot get key from parameter 1 in ....
``` 

In theory, that problem can be workaround by setting some env variable (`OPENSSL_CONF`, ...)pointing to the later file but, ideally, it should work without requiring that.

So, somehow, that default `Openssl default config` should be pointing to the existing (later) file or, alternatively, that file should be copied to the former location so PHP 7.3 is able to find it.

**Version**
- [x] PHP 7.3 verified (and maybe also older versions).

**Operating systems**
- Github Actions Environments windows-latest (2019 right now).

**To Reproduce**
- Using the PHP and OS specified above, try any simple openssl script in PHP, for example:
```
<?php

$config = [
   "digest_alg" => "sha256",
   "private_key_bits" => 2048,
   "private_key_type" => OPENSSL_KEYTYPE_RSA,
];
$res = openssl_pkey_new($config);
openssl_pkey_export($res, $privatekey);
var_dump($privatekey);
```

**Expected behavior**
A private key is generated and printed, without any PHP Warning

**Screenshots/Logs**
output / error log shows: `PHP Warning:  openssl_pkey_export(): cannot get key from parameter 1 in...`

**Are you willing to submit a PR?**
Sorry, I'm not able to help with that... in fact I was not sure if this issue corresponds to this, to `setup-php` or to the environments themselves, noob here, specially with Windows stuff.

If I can help with anything else, glad to help. Ciao :-)

**Comment by shivammathur** [comment]
@stronk7 I transferred this issue to `setup-php`. 

This is fixed in https://github.com/shivammathur/setup-php/commit/9ed025ec54f58ef5fbcdbf0a199ccb1524a84dda. 
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1830819859/workflow

It will be in the next setup-php release.

**Comment by mlocati** [comment]
PS: I also am working on it: https://github.com/mlocati/powershell-phpmanager/commits/fix-openssl_conf-path

(No ETA though)

**Comment by shivammathur** [comment]
@mlocati That looks great, will use it once released.

**Comment by stronk7** [comment]
Heap thanks, @shivammathur & @mlocati !

**Comment by mlocati** [comment]
I've just published a new version of Powershell PhpManager (1.26.0).
It comes with a new function (`Set-OpenSSLConf`) that can be used to set the `OPENSSL_CONF` environment variable, with the value of the path to a `openssl.cnf` file.

```
PS C:\> Get-Help Set-OpenSSLConf -Detailed

NAME
    Set-OpenSSLConf

SYNOPSIS
    Persist/fix the path of the openssl.cnf file by settng the OPENSSL_CONF environment variable


SYNTAX
    Set-OpenSSLConf [[-Path] <String>] [[-Target] <String>] [<CommonParameters>]


DESCRIPTION


PARAMETERS
    -Path <String>
        The path to the openssl.cnf file (if not provided we'll try to detect it)

    -Target <String>
        'Process' [default] to set the OPENSSL_CONF environment variable for the current process only
        'User' to set the OPENSSL_CONF environment variable for the current process and the current user
        'Machine' to set the OPENSSL_CONF environment variable for the current process and the local machine

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).

    -------------------------- EXAMPLE 1 --------------------------

    PS > Set-OpenSSLConf C:\Path\to\openssl.cnf
```

PS: PHP comes with a sample `openssl.cnf` file. If you omit the `Path` parameter, and if the directory containing the installed `php.exe` is listed in the `PATH` environment variable, `Set-OpenSSLConf` will use that `openssl.cnf` file ([see here](https://github.com/mlocati/powershell-phpmanager/pull/97/files#diff-4f5f083bc37ebc415350b13d8ed1b3b9f28ba1431fa1df269e3b95d90468656bR31-R41) for the paths where `Set-OpenSSLConf` looks for `openssl.cnf`).

**Comment by shivammathur** [comment]
Added support in 7ad352e12a8456ffb4b93ed8bcccff35b8738fe8

**Comment by shivammathur** [comment]
Added in `2.17.1`.

**Comment by stronk7** [comment]
I can confirm that, now, previous PHPUnit runs affected by this (PHP 7.3) are now passing perfectly.

Link: https://github.com/stronk7/moodle/runs/5378218227
(note that there are still a couple of failures there, but they are unrelated, the SSL ones are now gone)

Heap thanks!
