### ISSUE TITLE
Could not setup PHP 7.0 on Ubuntu

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#565]
**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
7.0

**To Reproduce**
https://github.com/zephir-lang/php-zephir-parser/runs/5169829161?check_suite_focus=true

**Comment by shivammathur** [comment]
@Jeckerson Please try restarting the workflow, must be a network issue in fetching the build.
