### ISSUE TITLE
Issues with PHP 5.6: unable to load library sqlsrv.so

### ISSUE THREAD

**Issue by jeherve** [shivammathur/setup-php#567]
**Describe the bug**

When setting PHP 5.6 via the action, one runs into the following error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/sqlsrv.so' - /usr/lib/php/20131226/sqlsrv.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

This started happening less than 24 hours ago, this wasn't an issue before.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [x] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

* ubuntu-latest

**PHP versions**

* PHP 5.6

**To Reproduce**

Here is an example action run, with 3 different PHP versions. As you can see the failures only happen with PHP 5.6:
https://github.com/jeherve/test-actions/runs/5287070943?check_suite_focus=true

Here is the workflow for that action:
https://github.com/jeherve/test-actions/blob/2850b6139f4e698e441d2271178278d224cd7b50/.github/workflows/test.yml

```
Run shivammathur/setup-php@v2
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/[20](https://github.com/jeherve/test-actions/runs/5287070943?check_suite_focus=true#step:3:20)131[22](https://github.com/jeherve/test-actions/runs/5287070943?check_suite_focus=true#step:3:22)6/pdo_sqlsrv.so' - /usr/lib/php/20131226/pdo_sqlsrv.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/sqlsrv.so' - /usr/lib/php/20131226/sqlsrv.so: cannot open shared object file: No such file or directory in Unknown on line 0
✓ PHP Installed PHP 5.6.40
```

**Additional context**

Possibly related to #61.

**Comment by shivammathur** [comment]
@jeherve 

`sqlsrv` and `pdo_sqlsrv` are not supported on PHP 5.6
Ref: https://github.com/microsoft/msphpsql/issues/819

**Comment by jeherve** [comment]
Thanks for the quick response! 

Do you happen to know why `shivammathur/setup-php@v2` did not throw such errors when installing PHP 5.6 yesterday, but does today?

**Comment by shivammathur** [comment]
@jeherve Fixing this, the builds cache was misconfigured to add these extensions to PHP 5.6.

**Comment by jeherve** [comment]
It works for me too, thanks a lot for the quick fix!
