### ISSUE TITLE
Running again with older PHP version doesn't rewrite php in PATH

### ISSUE THREAD

**Issue by ondrejmirtes** [shivammathur/setup-php#574]
**Describe the bug**

I need to run setup-php multiple times in a single pipeline. I first need to downgrade code with Rector which requires PHP 8.0 and then I need to test that downgraded version on the actual supported PHP version 7.x.

Somewhere between March 6th and 7th, this stopped working. The `php` version is still 8.0 even after running `setup-php` for a lower PHP version.

I've created a branch to reproduce this issue (the master branch is unrelated): https://github.com/ondrejmirtes/composer-issue/commit/73143b751784b59906c7835dca9992d1348a2508

In the results you can see that on some PHP versions it works and some it doesn't: https://github.com/ondrejmirtes/composer-issue/runs/5464085596?check_suite_focus=true

Installing PHP 7.1, PHP 7.2, and PHP 7.3 after 8.0 is installed doesn't work. But installing 7.4 after 8.0 works and `php` reports 7.4 again.

On Windows it always seems to work.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu

**Comment by shivammathur** [comment]
@ondrejmirtes 
Sorry for the regression.
Fixed in https://github.com/shivammathur/php-ubuntu/commit/5f9565dc6490c163d94bb8187990d2670dd216d7

**Comment by ondrejmirtes** [comment]
Thank you. I confirm it works now :)
