### ISSUE TITLE
php 8.0 version  gave migration error 

### ISSUE THREAD

**Issue by ru90** [shivammathur/setup-php#586]
**Describe the bug**
``` Illuminate\Database\QueryException: could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)```
Though SQLite tension is installed properly. also, it works well with PHP 8.1

![image](https://user-images.githubusercontent.com/12201673/163128646-c3702a3c-2879-41a8-a221-83a741b1375c.png)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**PHP versions**

8.0

**To Reproduce**
```name: Run Tests

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: bcmath, curl, fileinfo, gmp, mbstring, soap, xml, zip, sqlite
        tools: phpunit
        coverage: none
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      working-directory: app
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
      working-directory: app
    - uses: actions/cache@v1
      id: cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install Dependencies
      run: composer install -n --prefer-dist --no-scripts
      working-directory: app
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/paratest -p4
      working-directory: app
    - name: Slack Notification
      uses: lazy-actions/slatify@v2.1.2
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Run Tests*'
        channel: '#deployments'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by shivammathur** [comment]
Try adding `pdo_sqlite` to the `extensions` input.

**Comment by ru90** [comment]
add it
![image](https://user-images.githubusercontent.com/12201673/163143536-56377868-9b37-44fc-aa69-bc14a9560803.png)

Still same error:
![image](https://user-images.githubusercontent.com/12201673/163143894-bacb9d6d-7e9b-4c1d-bb40-a7ae334903ef.png)

**Comment by shivammathur** [comment]
Please provide the fields in your env file with the prefix `DB_`

**Comment by ru90** [comment]
DB_CONNECTION=sqlite

**Comment by ru90** [comment]
Hello, I switched to the 8.1 version which works well.
 Sorry to bother you. Thank you for your help

Rushabh Doshi
