### ISSUE TITLE
cURL 60 Error using ubuntu-20.04 and PHP 8.1.4

### ISSUE THREAD

**Issue by justanotheranonymoususer** [shivammathur/setup-php#590]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest => ubuntu-20.04

**PHP versions**

8.1 => 8.1.4

**To Reproduce**

Using `curl_exec` on my website with a valid cert returns error:
`SSL certificate problem: unable to get local issuer certificate`
The cert was updated yesterday, but my local cURL doesn't show this error.
I can provide the URL privately.

**Expected behavior**

No error.

**Screenshots/Logs**

**Additional context**

Maybe similar to this:
https://github.com/shivammathur/setup-php/issues/511

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
I ran a test and curl seems to be working correctly
https://github.com/shivammathur/test-setup-php/actions/runs/2219439658/workflow

If this is happening on a private repo, please create a minimal public repo to reproduce this, or send me the logs and your workflow details at contact@shivammathur.com

**Comment by justanotheranonymoususer** [comment]
https://github.com/justanotheranonymoususer/setup-php-repro/runs/6156443488

**Comment by shivammathur** [comment]
This has got nothing to do with setup-php

The certificate chain on your server is incomplete
https://www.ssllabs.com/ssltest/analyze.html?d=students.technion.ac.il
https://stackoverflow.com/questions/47290165/ssl-servers-certificate-chain-is-incomplete

**Comment by justanotheranonymoususer** [comment]
This is not my server, any tips except disabling the validation?

**Comment by justanotheranonymoususer** [comment]
I appreciate your help. I preferred not to disable validation completely. I solved it with option 2 from here:
https://stackoverflow.com/a/70011298/2604492
