### ISSUE TITLE
Unable to load dynamic library 'memcached' on Windows

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#591]
**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows2019

**PHP versions**
7.4 and 8.0

**To Reproduce**
* https://github.com/phalcon/cphalcon/blob/57a2dfd05e50672b6b95c251f54865fd11397780/.github/workflows/main.yml#L75
* https://github.com/phalcon/cphalcon/runs/6286151672?check_suite_focus=true#step:4:41

**Comment by shivammathur** [comment]
@Jeckerson 
Fixed in https://github.com/mlocati/powershell-phpmanager/pull/100
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/2269311221

Please re-run your workflows.
