### ISSUE TITLE
php -c {custom php.ini} doesn't work

### ISSUE THREAD

**Issue by ttskch** [shivammathur/setup-php#595]
**Describe the bug**

```shell
$ cat php.ini
date.timezone=Asia/Tokyo

$ php -c php.ini | grep timezone
Default timezone => UTC
date.timezone => UTC => UTC # This should be overwritten with Asia/Tokyo
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest (Ubuntu 18.04 LTS)

**PHP versions**

8.1

**To Reproduce**

```
name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - uses: actions/checkout@v2

      - name: debug
        run: |
          echo " "
          echo "$ php -i | grep php.ini"
          php -i | grep php.ini
          echo " "
          echo "$ php -i | grep timezone"
          php -i | grep timezone
          echo " "
          echo "$ cat php.ini"
          cat php.ini
          echo " "
          echo "$ php -c php.ini -i | grep php.ini"
          php -c php.ini -i | grep php.ini
          echo " "
          echo "$ php -c php.ini -i | grep timezone"
          php -c php.ini -i | grep timezone
```

Result of the `debug` step of above workflow is following.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/4360663/170288236-f5d993fe-2624-447a-a38e-7d42a4391ead.png">

`Loaded Configuration File` is correctly overwritten with `/home/runner/work/{repo}/{repo}/php.ini`, but `date.timezone` is not changed🤔

**Expected behavior**

```shell
$ php -c php.ini -i | grep timezone
Default timezone => UTC
date.timezone => Asia/Tokyo => Asia/Tokyo
```

**Screenshots/Logs**

See above.

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@ttskch I pushed a fix, instead of `v2` can you test with the `develop` branch and let me know.
```yml
- uses: shivammathur/setup-php@develop
  with:
    php-version: 8.1
```

**Comment by ttskch** [comment]
@shivammathur It works well!!👍

**Comment by shivammathur** [comment]
Release 2.19.0 with the fix.
https://github.com/shivammathur/setup-php/releases/tag/2.19.0
