### ISSUE TITLE
find: /usr/local/bin/../Cellar/imagick@7.4: No such file or directory

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#615]
**Describe the bug**
Could not install imagick extension.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
All

**To Reproduce**
https://github.com/phalcon/cphalcon/runs/7291219945?check_suite_focus=true#step:4:32

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/homebrew-extensions/commit/07daaddd0ab4c60f908b169c58bf9a315e4b1569

Please re-run your workflow
