### ISSUE TITLE
apt --fix-broken install libpcre2-dev

### ISSUE THREAD

**Issue by heyanlong** [shivammathur/setup-php#619]
**Describe the bug**
libpcre2-dev : Depends: libpcre2-8-0 (= 10.39-3+ubuntu20.04.1+deb.sury.org+2) but 10.40-1+ubuntu20.04.1+deb.sury.org+1 is to be installed

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
https://github.com/SkyAPM/SkyAPM-php-sdk/runs/7403830696?check_suite_focus=true
- [x] GitHub Hosted
- [ ] Self Hosted

**Comment by shivammathur** [comment]
@heyanlong 
I refreshed the cache we have. Please re-run your workflow and let me know if this is fixed.
