### ISSUE TITLE
xmlrpc-beta extension stopped working recently

### ISSUE THREAD

**Issue by stronk7** [shivammathur/setup-php#625]
**Describe the bug**
Since 24h ago (aprox) we have started to get failures in all our PHP 8.0 jobs. The failure is about the xmlrpc extension not being detected as installed, when we always add it via [extensions: xmlrpc-beta](https://github.com/moodle/moodle/blob/master/.github/workflows/push.yml#L61-L64).

All jobs were passing until 24h ago and we have verified that all the stack has not changed at all:
- GH environments version.
- PECL xmlrpc extensions (RC3 is the latest since months ago).
- PHP releases
- ...

And the only piece that has changed is the new release of setup-php 2.21.1.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
PHP 8.0 and PHP 8.1

**To Reproduce**
I've created this dummy repo with a simple workflow that verifies the "xmlrpc" installation over all PHP versions and, also with php-setup versions 2.20.1 (old) and 2.21.1 (actual). Here it is the workflow:

https://github.com/stronk7/xmlrpc-dummy-test/blob/main/.github/workflows/push.yml

**Expected behavior**
All the jobs and steps of that workflow should pass, specifically the xmlrpc-beta ones have stopped working.

**Screenshots/Logs**
You can see the workflow above running @ https://github.com/stronk7/xmlrpc-dummy-test/actions/runs/2755723909

Notes:

1. PHP 7.2, 7.3 and 7.4 are not affected, they come with xmlrpc bundled.
2. Curiously "xmlrpc" (without "-beta") is working, I'm near sure it was not in the past.
3. When using "xmlrpc-beta", fails with setup-php 2.21.1, but passes with setup-php 2.20.1. 
4. The 2.20.1 passing "xmlrpv-beta" runs say `xmlrpc-1.0.0 Installed and enabled`. I'm not sure from where that 1.0.0 comes. All the other runs, failing or passing just say: `xmlrpc Enabled`.

**Additional context**
For us, the fix seems to be easy, just change `xmlrpc-beta` by `xmlrpc` and done. Aka, point 2 in the notes above. Just guessing it `xmlrpc` is going to remain working.

But what seems clear is that `xmlrpc-beta` has stopped working with last setup-php release (point 3) and that there is something strange around with that 1.0.0 version (that doesn't seem to come from PECL).

**Are you willing to submit a PR?**
Sorry, I don't have idea about what to fix! For curiosity I looked to the changes between 2.21.0 and 2.21.1... to see if there was something obvious... but no idea.

Ciao :-)

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/7e03c76ef2aa9cc1deb5b9c2395e7f0be6bd3160. Currently in develop branch right now, will in the next release.

**Comment by stronk7** [comment]
Cool, thanks!

Q: and that “mysterious” xmlrpc-1.0.0 that got when using older 2.20.1 was also caused because of the bug?

**Comment by shivammathur** [comment]
Yes, the regex to parse the releases was wrong earlier. it worked because pecl fallbacks to the latest version when a wrong version is specified. 

In the previous release I tried to fix this, but only considered the stability in the version. Now it checks for stability in the version (`RC` in this case), if no version is found matching that, it checks for the pecl stability.

**Comment by stronk7** [comment]
Aha, thanks for the clarification (and for the quick reply and fix) !

Looking forward the next setup-php release, then, yay!

Ciao :-)

**Comment by shivammathur** [comment]
Released [2.21.2](https://github.com/shivammathur/setup-php/releases/tag/2.21.2) with the fix.

**Comment by stronk7** [comment]
Thanks,

jobs are back to green here, yippee! 🥳
