### ISSUE TITLE
"Setup PHP" has stopped working on Windows

### ISSUE THREAD

**Issue by jasonvarga** [shivammathur/setup-php#628]
**Describe the bug**

The "Setup PHP" step fails.

```
==> Setup PHP 
✗ PHP Could not setup PHP 7.4 
```

We have a workflow that uses PHP 7.4 on `windows-latest`.

2 hours earlier in the day, it worked fine.

Failing job: https://github.com/statamic/cms/runs/7795642025
Successful job 2 hours earlier: https://github.com/statamic/cms/runs/7793322532
The only change was a commit to a changelog markdown file, so it's not the code.

When using PHP 7.4 on ubuntu, it's fine.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
windows-latest (Microsoft Windows Server 2022 10.0.20348)

**PHP versions**
7.4

**To Reproduce**
https://github.com/statamic/cms/blob/49fe67824803f73d657e6dcc4d2f662bad1a50ca/.github/workflows/tests.yml#L45-L50

**Expected behavior**

**Screenshots/Logs**

![CleanShot 2022-08-11 at 17 58 29](https://user-images.githubusercontent.com/105211/184249663-00ae2160-bf86-480a-aa35-5ea048f5f46a.png)

**Additional context**
I would have also expected that failure to setup PHP would make that step in the workflow fail. It took me a while to figure out why my tests were failing. Didn't notice it was the wrong PHP for a while.

**Are you willing to submit a PR?**
Not within my ability unfortunately.

Thanks!

**Comment by shivammathur** [comment]
@jasonvarga 
https://windows.php.net/ is down

**Comment by jasonvarga** [comment]
Hah ok that'll do it I guess. Thanks!

**Comment by shivammathur** [comment]
It is back up online. It should work now

**Comment by jasonvarga** [comment]
Yup, works. Thanks.
