### ISSUE TITLE
Add support for debug builds

### ISSUE THREAD

**Issue by kocsismate** [shivammathur/setup-php#634]
**Describe the feature**
I'm a PHP extension maintainer and core contributor, so it would make my work much easier if setup-php would support using debug builds (`./configure --enable-debug`).

**Underlying issue**
Debug builds have additional error checks and validations enabled, and these are essential for extension development.

**Are you willing to submit a PR?**
I cannot submit a PR because I prefer working on PHP core in my free time.

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/setup-php/commit/7ff9ac44b48fdef736028ef6d4a0a651f9160cda
It will be in the next release

**Comment by kocsismate** [comment]
This is awesome news! Thank you very much!
