### ISSUE TITLE
PHP ZTS Support

### ISSUE THREAD

**Issue by flavioheleno** [shivammathur/setup-php#649]
**Describe the feature**
As per https://github.com/shivammathur/setup-php/issues/363#issuecomment-742884304, I'd like to chip in and create/maintain the workflow for building PHP ZTS for Linux.

I just need some guidance on where things should go and what is the expected flow.

**Comment by shivammathur** [comment]
Thanks.

Please see https://github.com/shivammathur/php-builder for building PHP for Ubuntu. Currently, it builds PHP 8.0 and above in release and debug modes. This will have to be extended to build PHP 5.6 to 7.4 as well as zts builds for all versions.

**Comment by shivammathur** [comment]
@flavioheleno I was free this week, so I added zts builds, so `phpts` env should now work on Ubuntu for PHP 5.6 and above.

**Comment by flavioheleno** [comment]
awesome! thanks!
