### ISSUE TITLE
PHP 8.1.11 version support

### ISSUE THREAD

**Issue by lrynek** [shivammathur/setup-php#650]
**Describe the feature**
Make the `setup-php` able to build images with latest PHP 8.1.11 version for GitHub Actions where it's being used.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
I will allow the usage of the latest PHP version in the repositories where the action is being leveraged to prevent pipeline failures.

**Describe alternatives**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/36886649/193353423-7cf2c9c3-c410-43b6-b24e-67d46c0ed5c6.png)

**Are you willing to submit a PR?**
Yes but I will need some guidance 🙂

**Comment by shivammathur** [comment]
Please specify `update: true` as the env variable to get the lastest PHP patch releases.
https://github.com/shivammathur/setup-php#force-update-setup

**Comment by lrynek** [comment]
> Please specify `update: true` as the env variable to get the lastest PHP patch releases. https://github.com/shivammathur/setup-php#force-update-setup

Thank you! Done and working ❤️
