### ISSUE TITLE
Fail build step if tools installation fails

### ISSUE THREAD

**Issue by kevinpapst** [shivammathur/setup-php#652]
**Describe the feature**
I am currently in a situation where symfony-cli installation fails out of nowhere.
In that case obviously something in the later build steps will fail, but the cause is hidden, as Setup-PHP reports being successful.

I would prefer if Setup PHP fails, if any of the requested installations steps fail.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
Something went wrong with symfony-cli.

**Describe alternatives**
Manual check all steps for the cause of the failure

**Additional context**
<img width="869" alt="Bildschirmfoto 2022-10-09 um 13 18 11" src="https://user-images.githubusercontent.com/533162/194754196-3d0fbd97-0422-4861-9d4f-124cf9e7b268.png">

Here is the build link: 
https://github.com/kevinpapst/kimai2/actions/runs/3213939983/jobs/5253975481

Btw: I don't want to make this issue about the symfony-cli, but I think it fails since the latest release of Symfony-Cli one hour ago. See https://github.com/symfony-cli/symfony-cli/releases - maybe there is something broken now?

**Comment by shivammathur** [comment]
You can specify `fail-fast: true` environment variable to make it fail.
https://github.com/shivammathur/setup-php#fail-fast-optional

`symfony-cli` is failing because they keep changing how they release this tool, this time the Linux release artifacts without the version are missing. I will fix it in the next release to use the versioned ones.

**Comment by kevinpapst** [comment]
Tried `fail-fast` - works 👍 
Thanks for helping me to find the right place in the docs.

As now my CI pipeline is broken, and from tomorrow one a lot more: I guess you are releasing soon?!

**Comment by shivammathur** [comment]
It should work now as the change was reverted upstream

**Comment by kevinpapst** [comment]
Awesome, I can confirm: the broken builds do work after a "Re-run".
Thank you @shivammathur for taking the action, you do an amazon job 👍
