### ISSUE TITLE
tests failed on the PHP8.2.0-dev@Windows with `Undefined constant "OPENSSL_SSLV23_PADDING"` message

### ISSUE THREAD

**Issue by TheNorthMemory** [shivammathur/setup-php#658]
**Describe the bug**

please take a look [this actions](https://github.com/TheNorthMemory/wechatpay-php/actions/runs/3359634900/jobs/5567868623#step:14:33)

```
1) Error
The data provider specified for WeChatPay\Tests\Crypto\RsaTest::testCrossEncryptDecryptWithDifferentPadding is invalid.
Error: Undefined constant "OPENSSL_SSLV23_PADDING"
D:\a\wechatpay-php\wechatpay-php\tests\Crypto\RsaTest.php:290
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Windows-latest

**PHP versions**

`8.2.0-dev (22f25532ed11b6508872926d7b7be0ae7552c3dd) `

**To Reproduce**

```php
<?php
use const OPENSSL_SSLV23_PADDING;

var_dump(OPENSSL_SSLV23_PADDING);
```

see https://www.php.net/manual/en/openssl.padding.php

**Expected behavior**

may works as other OS, such as `ubuntu-latest` and `macOS-latest`

**Screenshots/Logs**

```
PHPUnit 9.5.26 by Sebastian Bergmann and contributors.

...............................................................  63 / 528 ( 11%)
............................................................... 126 / 528 ( 23%)
............................................................... 189 / 528 ( 35%)
............................................................... 252 / 528 ( 47%)
..........E.................................................... 315 / 528 ( 59%)
............................................................... 378 / 528 ( 71%)
............................................................... 441 / 528 ( 83%)
............................................................... 504 / 528 ( 95%)
........................                                        528 / 528 (100%)

Time: 00:00.554, Memory: 12.00 MB

There was 1 error:

1) Error
The data provider specified for WeChatPay\Tests\Crypto\RsaTest::testCrossEncryptDecryptWithDifferentPadding is invalid.
Error: Undefined constant "OPENSSL_SSLV23_PADDING"
D:\a\wechatpay-php\wechatpay-php\tests\Crypto\RsaTest.php:290

ERRORS!
Tests: 528, Assertions: 2747, Errors: 1.
Error: Process completed with exit code 1.
```

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
PHP 8.2 on Windows is built using OpenSSL 3.

OPENSSL_SSLV23_PADDING is only available if `RSA_SSLV23_PADDING` is present and that was removed in OpenSSL 3
https://github.com/php/php-src/blob/PHP-8.2/ext/openssl/openssl_arginfo.h#L590
https://github.com/openssl/openssl/issues/14283

Other OS will also upgrade to use OpenSSL 3 in the future while building PHP 8.2, so I would not rely on it.

**Comment by TheNorthMemory** [comment]
Thanks for the feedback. A little concern is about that, the current `windows-latest` runner pre-installed the [openssl 1.1.1](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)(real 1.1.1q). 

Does the `PhpManager` need a choice to install the `ext-openssl` with `1.1.1`?
