### ISSUE TITLE
imageavif(): AVIF image support has been disabled

### ISSUE THREAD

**Issue by ADmad** [shivammathur/setup-php#672]
**Describe the bug**
Using GD's `imageavif()` method gives error `imageavif(): AVIF image support has been disabled.`

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest` for Github Actions

**PHP versions**
8.1 and 8.2

**Additional context**
Potentially related to https://github.com/oerdnj/deb.sury.org/issues/1641

**Comment by shivammathur** [comment]
@ADmad 
Please update your workflow to use `ubuntu-22.04`.
`ubuntu-latest` is 20.04 currently and that does not have the `libavif`.

**Comment by ADmad** [comment]
Ah sorry. Wasn't aware that "latest" doesn't actually give you the latest :)
