### ISSUE TITLE
ini-values with equal sign doesn't work

### ISSUE THREAD

**Issue by stefanak-michal** [shivammathur/setup-php#676]
**Describe the bug**
I want to add DSN alias for PDO into php.ini

`ini-values: pdo.dsn.mybolt="bolt:host=localhost;port=7687;appname=pdo-bolt"`

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
^8

**Expected behavior**
I expect to receive full string with this php code
```php
$dsn = get_cfg_var('pdo.dsn.mybolt');
```
`$dsn` should contains `bolt:host=localhost;port=7687;appname=pdo-bolt` but currently this returns only `bolt:host`.

**Are you willing to submit a PR?**
no

**Comment by stefanak-michal** [comment]
https://github.com/stefanak-michal/pdo-bolt/actions/runs/3699091929/jobs/6266073032

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/3407e6019c7258d7d201146fcc127cb112100a85. Will be in the next release.

**Comment by shivammathur** [comment]
Released [`2.23.0`](https://github.com/shivammathur/setup-php/releases/tag/2.23.0) with the fix.
