### ISSUE TITLE
setup-php claims that Xdebug is available for PHP 8.3.0-dev when it is not

### ISSUE THREAD

**Issue by sebastianbergmann** [shivammathur/setup-php#685]
**Describe the bug**

For a couple of days now, PHP 8.3.0-dev does not seem to have a working Xdebug. [Here](https://github.com/sebastianbergmann/phpunit/actions/runs/3899620984/jobs/6659488887) is an example of the job for PHPUnit's `main` branch failing due to Xdebug not being available although `✓ xdebug Xdebug  enabled as coverage driver` is printed.

I know that Xdebug's `master` branch currently does not compile against PHP's `master` branch. I do think, however, that a message such as `✓ xdebug Xdebug  enabled as coverage driver` must not be printed when the extension in question is not available.

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**
- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 22.04.1LTS

**PHP versions**
PHP 8.3.0-dev (4427b2e1ab6cc51a1b328cbb3f216ab4c955f672)

**To Reproduce**
https://github.com/sebastianbergmann/phpunit/blob/main/.github/workflows/ci.yml#L228

**Expected behavior**
Xdebug is available, PHPUnit can detect and use it

**Screenshots/Logs**
https://github.com/sebastianbergmann/phpunit/actions/runs/3899620984/jobs/6659488887

**Comment by shivammathur** [comment]
@sebastianbergmann 

The header file changes in php/php-src#10216 have affected most extensions built along with PHP 8.3 in `shivammathur/php-builder`. I will work on adding patches for them.

**Comment by sebastianbergmann** [comment]
This issue is not about the fact that an extension is currently broken, but about the fact that setup-php claims that an extension is loaded.

**Comment by shivammathur** [comment]
Released the fix in [2.24.0](https://github.com/shivammathur/setup-php/releases/tag/2.24.0)
