### ISSUE TITLE
PHP 8.3 does not work on Windows

### ISSUE THREAD

**Issue by sebastianbergmann** [shivammathur/setup-php#692]
**Describe the bug**
As of a couple of days ago, PHP 8.3 does not work on Windows.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

I use Linux and Windows, only PHP 8.3 on Windows fails.

**PHP versions**

I use PHP 7.2 through PHP 8.3, only PHP 8.3 on Windows fails.

**To Reproduce**

https://github.com/sebastianbergmann/phpunit/blob/main/.github/workflows/ci.yml#L76

**Expected behavior**

PHP 8.3 on Windows should work just as other versions do.

**Screenshots/Logs**

![grafik](https://user-images.githubusercontent.com/25218/215407985-c685df2e-ed49-4089-a9c8-2a801c8c7234.png)

**Comment by shivammathur** [comment]
@sebastianbergmann 

I have reported this to the GitHub Actions team.
https://github.com/actions/runner-images/issues/7007

**Comment by shivammathur** [comment]
Fixed in the new image of windows runner `20230129.1`.
