### ISSUE TITLE
Does not pick thread safe version of zephir_parser package

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#701]
**Describe the bug**
It always picks one type.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Any

**PHP versions**
Any

**To Reproduce**
https://github.com/zephir-lang/zephir/actions/runs/4132412865/jobs/7141078939#step:6:122

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/0d6002468386cec66a4ecac07fca1417e1fd8ee0

**Comment by Jeckerson** [comment]
https://github.com/zephir-lang/zephir/actions/runs/4136608309/jobs/7150711424#step:3:31

Extension wasn't installed.

**Comment by shivammathur** [comment]
@Jeckerson Try will `shivammathur/setup-php@develop`. I fixed another bug in the next commit for enabling extensions.

**Comment by Jeckerson** [comment]
It works, thank you!
