### ISSUE TITLE
composer-unused Could not setup composer-unused

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#703]
**Describe the bug**
`composer-unused Could not setup composer-unused`
https://github.com/Slamdunk/php-p7m-reader/actions/runs/4175072546/jobs/7229492984#step:3:20

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`

**Runners**

- [x] GitHub Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.1`

**To Reproduce**
https://github.com/Slamdunk/php-p7m-reader/blob/98790e85fd22a7888063c3ca3895f35c8a0bb3b5/.github/workflows/ci.yaml#L23-L28

**Comment by shivammathur** [comment]
The latest release of `composer-unused` has the `phar` file, so it should install correctly now.
