### ISSUE TITLE
Update flag having no effect

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#705]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu 22.04.

**PHP versions**

8.1

**To Reproduce**

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: sodium
          tools: composer:v2
          coverage: none
        env:
          update: true
```

**Expected behavior**

PHP 8.1.16 to be installed.

**Screenshots/Logs**

```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.1
    extensions: sodium
    tools: composer:v2
    coverage: none
    ini-file: production
  env:
    update: true
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Found PHP 8.1.2

==> Setup Extensions
✓ sodium Enabled

==> Setup Tools
✓ composer Added composer 2.5.4

==> Setup Coverage
✓ none Disabled Xdebug and PCOV

==> #StandWithUkraine
✓ read-more https://setup-php.com/support-ukraine
```

**Additional context**

It fails to install the latest version of PHP, despite the update flag being set.

**Are you willing to submit a PR?**

**Comment by GrahamCampbell** [comment]
I think this is possibly related to the Ubuntu upgrades that GitHub are gradually rolling out today...

**Comment by shivammathur** [comment]
@GrahamCampbell 

Please rerun it, I could not reproduce the issue.
https://github.com/shivammathur/test-setup-php/actions/runs/4253441088/jobs/7398316083#step:2:1

Can you share the link of the workflow, or reproduce it in a public repo if it is from a private one?

**Comment by GrahamCampbell** [comment]
It seems to be a gradual rollout by github, so not all orgs have the new image yet. :/

**Comment by GrahamCampbell** [comment]
Hmmmm, this seems pretty flakey. I re-ran and this time it updated, without any code changes. 😭

**Comment by GrahamCampbell** [comment]
Seems to have stopped happening. 🤷
