### ISSUE TITLE
Fail if `setup-php` was unable to install the requested PHP version

### ISSUE THREAD

**Issue by weirdan** [shivammathur/setup-php#709]
**Describe the feature**

`setup-php` should fail when it's unable to install the requested PHP version

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Currently, when `setup-php` fails to set up the requested PHP version, the build continues with the PHP version provided by the runner environment, which may not be compatible with the software being built/tested.

**Describe alternatives**

I tried to use `env: fail-fast: true` to no avail.

**Additional context**

![image](https://user-images.githubusercontent.com/57403/224649201-5dcb1187-d30b-4d69-afed-24dfc9cebabf.png)

This happens intermittently but quite often, so I couldn't run it with debugging enabled.

https://github.com/vimeo/psalm/actions/runs/4401974668/jobs/7708673538

**Are you willing to submit a PR?**

I'm not sure I'll be able to do this.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/5f422817a1c142632541535cd6e75a173d61d12f.

Will be in the next release.

**Comment by shivammathur** [comment]
Fix released in [`2.25.0`](https://github.com/shivammathur/setup-php/releases/tag/2.25.0).
