### ISSUE TITLE
uopz extension is not loaded after setup

### ISSUE THREAD

**Issue by linuxjuggler** [shivammathur/setup-php#71]
Hey, here is the log which shows that uopz is installed and enabled.

```shell
Run shivammathur/setup-php@master
  with:
    php-version: 7.1
    extension-csv: redis, uopz
sh /opt/hostedtoolcache/linux.sh 7.1 /home/runner/work/_actions/shivammathur/setup-php/master/lib

==> Setup PHP and Composer
✓ PHP Switched to PHP7.1
✓ Composer Installed

==> Setup Extensions
✓ redis Enabled
✓ uopz Installed and enabled
```

but composer complains that the extension is not installed

```shell
Problem 1
    - Installation request for duncan3dc/uopz-expectations ^0.3.0 -> satisfiable by duncan3dc/uopz-expectations[0.3.0].
    - duncan3dc/uopz-expectations 0.3.0 requires ext-uopz * -> the requested PHP extension uopz is missing from your system.
```

any advise on how to solve this?

**Comment by Jeckerson** [comment]
`uopz` package isn't in Linux packages.
Easiest way is run make separate run on your action and install via **pecl**

```
- name: Install uopz
  run: pecl install uopz
```

**Comment by linuxjuggler** [comment]
basically when you add an extension to `extension-csv` it will run via the installation command which is the same as you have mentioned 

https://github.com/shivammathur/setup-php/blob/e5076cee7018e0c31f78992ad86ab3fb587c0114/src/extensions.ts#L80

**Comment by linuxjuggler** [comment]
Sadly it didn't work since PECL is not installed 

```
Run pecl install uopz
/home/runner/work/_temp/d1cfeae2-2453-48f6-9fad-1cdd2d30047e.sh: line 1: pecl: command not found
##[error]Process completed with exit code 127.
```

**Comment by shivammathur** [comment]
@linuxjuggler working on a fix

**Comment by Jeckerson** [comment]
@linuxjuggler you can easily install it during action

https://pear.php.net/manual/en/installation.getting.php

**Comment by linuxjuggler** [comment]
Thanks @Jeckerson I am aware of the process of the installation, but I hoped such a feature to be enabled by default in the PHP Setup action. 👍

**Comment by Jeckerson** [comment]
PHP Setup action will do the same, just wrapped inside action logic.

**Comment by shivammathur** [comment]
@linuxjuggler @Jeckerson 
Now, when `pecl: true` is specified it will install PECL and will fallback to it, if extension is not on APT.
```yaml
- name: Install PHP
  uses: shivammathur/setup-php@master
  with:
    php-version: '7.3'
    extension-csv: uopz, # uopz works with PHP>=7.1
    pecl: true
```

**Comment by linuxjuggler** [comment]
Amazing work @shivammathur thanks 👍
