### ISSUE TITLE
Could not setup PHP on macOS

### ISSUE THREAD

**Issue by danepowell** [shivammathur/setup-php#710]
**Describe the bug**

Every attempt to install PHP on macOS is failing. For example: https://github.com/typhonius/acquia-php-sdk-v2/actions/runs/4427473587/jobs/7765488510

The only error is:

>  PHP Could not setup PHP 8.0
Error: The process '/bin/bash' failed with exit code 1

This was working fine until today, I'm wondering if GitHub updated something or if it's a network issue that's not being logged

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

macos-latest

**PHP versions**

PHP 8.0/8.1/8.2

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by caendesilva** [comment]
Experiencing this as well. I bumped version 16011a795d747d5f45038f96371c3b98aec5669d to d30ad8b1843ace22e6698ab99bbafaa747b6bd0d but to no avail. 

See https://github.com/hydephp/develop/actions/runs/4427634797/jobs/7765526953
    
    ==> Setup PHP
    ✗ PHP Could not setup PHP 8.1
    Error: The process '/bin/bash' failed with exit code 1

**Comment by caendesilva** [comment]
Seems to be resolved now after rerunning the tests.

**Comment by shivammathur** [comment]
This would be fixed once this incident is resolved and GitHub packages is back up
https://www.githubstatus.com/incidents/ybnn77s3lyf8

**Comment by shivammathur** [comment]
@danepowell  @caendesilva 
Please rerun your workflows, it should work now
