### ISSUE TITLE
PHP-5.5 with system libssl instead

### ISSUE THREAD

**Issue by TingDaoK** [shivammathur/setup-php#714]
**Describe the feature**

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
The PHP-5.5 setup with an old OpenSSL. From `php -i`:
```
 openssl

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2n  7 Dec 2017
OpenSSL Header Version => OpenSSL 1.0.2u  20 Dec 2019
```

The log from `Setup PHP` shows:
```
Selecting previously unselected package libssl1.0.0:amd64.
Preparing to unpack .../libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2n-1ubuntu5.7) ...
```

Seems like it pulls an old libssl1.0.0_1.0.2n.

However github image [ubuntu-lastest](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) comes with `libssl-dev | 3.0.2-0ubuntu1.8` as the default one in system.

Why build php-5.5 with the old 1.0.2 libssl instead of the one comes with the image?

**Describe alternatives**

Setup php5.5 with libssl 3.0.2 in the system.

**Additional context**

**Are you willing to submit a PR?**

No.

**Comment by TingDaoK** [comment]
And all the versions >= 5.6 are using the default version 3.0.2

**Comment by shivammathur** [comment]
@TingDaoK 
PHP 5.5 does not compile with OpenSSL 1.1 and definitely not when OpenSSL 3.
If you have a patch that adds support for newer versions of OpenSSL in PHP 5.5 and lower, please submit them [here](https://github.com/shivammathur/php5-ubuntu).
