### ISSUE TITLE
cs2pr suddenly missing

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#715]
**Describe the bug**
I'm suddenly getting this message in my builds:

`chmod: cannot access '/usr/local/bin/cs2pr': No such file or directory`

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-22.04`

**PHP versions**
PHP 8.2

**To Reproduce**
https://github.com/doctrine/orm/blob/2.14.x/.github/workflows/static-analysis.yml#L47

**Expected behavior**
cs2pr should be present

**Screenshots/Logs**
https://github.com/doctrine/orm/actions/runs/4515206785/jobs/7952245965?pr=10405#step:3:16

**Additional context**
Might be an issue with an upstream repo?

**Are you willing to submit a PR?**
I wouldn't know where to start

**Comment by jeremyfelt** [comment]
I'm seeing the same issue right now.

It appears that GitHub's user content [certificate has expired](https://news.ycombinator.com/item?id=35295216), which may be impacting the retrieval of the PHAR from https://github.com/staabm/annotate-pull-request-from-checkstyle

**Comment by jeremyfelt** [comment]
And it seems to be resolved now. :)
