### ISSUE TITLE
Use new download location for Relay

### ISSUE THREAD

**Issue by tillkruss** [shivammathur/setup-php#719]
**Describe the bug**
Relay used to use GitHub release artifacts, but as of v0.6.2 switched to R2 (same as S3) for artifacts because we were running into GitHub limitations.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [x] Self Hosted

**Operating systems**
All

**PHP versions**
All

**To Reproduce**
See https://github.com/cachewerk/homebrew-tap/commit/08c1b8ce1cf8ed99ebabbb0190f6285854a53fd6

**Are you willing to submit a PR?**
Yes.

**Comment by shivammathur** [comment]
Switched in 7d999d501a7b77228685777a2f7d0e60217d277c

**Comment by shivammathur** [comment]
Released [`2.25.0`](https://github.com/shivammathur/setup-php/releases/tag/2.25.0) with the changes.
