### ISSUE TITLE
Error Creating OpenSSL DSA Keys

### ISSUE THREAD

**Issue by Sephster** [shivammathur/setup-php#720]
**Describe the bug**
I am unsure why but I can't create a DSA key using the following code:

```
$res = \openssl_pkey_new([
                'digest_alg' => 'sha512',
                'private_key_bits' => 2048,
                'private_key_type' => OPENSSL_KEYTYPE_DSA,
            ]);
            // Get private key
            \openssl_pkey_export($res, $keyContent, 'mystrongpassword');
```

This code works fine for PHP 8.1 and 8.2 but fails in 7.4 and 8.0. The call to `openssl_pkey_new()` returns false. I have been able to generate such a key locally on PHP 7.4 and 8.0 in other environments so suspect this might be something to do with the openssl.cnf on the runners although this is purely a guess.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu-latest

**PHP versions**
7.4, 8.0, 8.1, 8.2

**To Reproduce**
I create a [basic test repo](https://github.com/Sephster/openssl_pkey_test/pull/1) to show the issue

**Expected behavior**
The call to openssl_pkey_new should return an OpenSSLAsymetricKey

**Screenshots/Logs**
Detailed in the [test repo](https://github.com/Sephster/openssl_pkey_test/pull/1)

**Additional context**
N/A

**Are you willing to submit a PR?**
I'm unsure of the root cause so wouldn't be able to at this time

**Comment by shivammathur** [comment]
If you are running this on the `ubuntu-latest` or `ubuntu-22.04` runner, that has OpenSSL 3 and support for it was added to PHP in 8.1. Please use `ubuntu-20.04` runner with the older PHP versions and this should work.
