### ISSUE TITLE
PHP 8.0 and 8.1 can't be set up anymore

### ISSUE THREAD

**Issue by driesvints** [shivammathur/setup-php#723]
**Describe the bug**
We're starting to get `dyld[2948]: Library not loaded: '/usr/local/opt/libtiff/lib/libtiff.6.dylib'` issues on the Laravel Valet build. They start at the point when PHP 8.0 or 8.1 are being set up.

PHP 8.2 can still be set up properly.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
macOS 12.6.5

**PHP versions**
8.1.18

**To Reproduce**
https://github.com/laravel/valet/blob/master/.github/workflows/tests.yml

**Expected behavior**
I expect PHP to be installed properly as before this started to happen.

**Screenshots/Logs**
```
dyld[2950]: Library not loaded: '/usr/local/opt/libtiff/lib/libtiff.6.dylib'
  Referenced from: '/usr/local/Cellar/gd/2.3.3_5/lib/libgd.3.dylib'
  Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/lib/libtiff.6.dylib' (no such file), '/usr/lib/libtiff.6.dylib' (no such file), '/usr/local/Cellar/libtiff/4.4.0_1/lib/libtiff.6.dylib' (no such file), '/usr/local/lib/libtiff.6.dylib' (no such file), '/usr/lib/libtiff.6.dylib' (no such file)
```

**Additional context**
Failing build: https://github.com/laravel/valet/actions/runs/4809371187/jobs/8560522947

**Are you willing to submit a PR?**
I don't know how to solve this.

**Comment by ArnaudLigny** [comment]
I confirm I got the same problem today, only on macOS system, see https://github.com/Cecilapp/Cecil/actions/runs/4810705513

**Comment by shivammathur** [comment]
@driesvints @ArnaudLigny 
Queued rebuild in https://github.com/shivammathur/homebrew-php/pull/1678

**Comment by shivammathur** [comment]
This should work now. Let me know if you still get that error.

**Comment by driesvints** [comment]
Works! Thanks @shivammathur 👍

**Comment by ArnaudLigny** [comment]
Yeah, it works again. Thanks a lot @shivammathur \o/
