### ISSUE TITLE
Memcache 8.2

### ISSUE THREAD

**Issue by xepozz** [shivammathur/setup-php#725]
Memcache 8.2 extension was released recently.
https://pecl.php.net/package/memcache

homebrew repo was updated as well in https://github.com/shivammathur/homebrew-extensions/issues/2730

Yii2 uses this repo without version constraints, but the [tests fail](https://github.com/yiisoft/yii2/pull/19749#issuecomment-1532658541) as it was with Memcache 8.0.

As I can see there are no fixed versions as in homebrew repo, but tests do not use 8.2 memcache.

Could you tell what's the problem?

**Comment by xepozz** [comment]
@shivammathur Look please here

**Comment by samdark** [comment]
I confirm the issue. @shivammathur anything we can help to resolve the issue?

**Comment by shivammathur** [comment]
@xepozz @samdark 

Released `2.25.2` with the fix.

Please try now, it should work.

**Comment by samdark** [comment]
Works! Thank you very much ❤️
