### ISSUE TITLE
Integer overflow in PHP 8.1.19 for macOS

### ISSUE THREAD

**Issue by danepowell** [shivammathur/setup-php#730]
On several unrelated projects using setup-php in GitHub Actions, upgrading from PHP 8.1.18 to 8.1.19 in macOS runners caused an integer overflow when running phpstan:

> PHP Fatal error:  Possible integer overflow in memory allocation (2147483648 * 32 + 32) in phar:///Users/runner/work/composer-stager/composer-stager/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/DependencyChecker.php on line 47

For instance, on the acquia-php-sdk-v2 project, here's the [last good build](https://github.com/typhonius/acquia-php-sdk-v2/actions/runs/4875701824/jobs/8698240875) from two weeks ago, and the [first failing build](https://github.com/typhonius/acquia-php-sdk-v2/actions/runs/5025939725/jobs/9013569578) after that. Pretty much the only change is the bump from PHP 8.1.18 to PHP 8.1.19.

Here's [another failing build on the composer-stager project](https://github.com/php-tuf/composer-stager/actions/runs/4983402379/jobs/8920369395).

Running the same script locally on macOS 13.3.1 works fine, as does the same script in Ubuntu, or in PHP 8.0 or 8.2.

Obviously this could be a bug in PHP core or the phpstan libraries, but the extreme specificity of it leads me to believe that it could be a problem with this particular PHP build in GitHub Actions. I know setup-php uses its own homebrew PHP builds, is it possible the PHP 8.1.19 macOS build was corrupted somehow?

**Comment by shivammathur** [comment]
@danepowell I have rebuilt php@8.1, please try restarting the CI job.

**Comment by danepowell** [comment]
Incredibly that worked!

https://github.com/typhonius/acquia-php-sdk-v2/pull/393

I'm going to have my colleagues verify on their projects as well.

I'm quite curious about what might have been wrong with the build.

**Comment by shivammathur** [comment]
PHP 8.1 was retagged in `php-src` mostly likely for this bug. 
Ref: https://github.com/php/web-php-distributions/commit/a5e260ca530b9dc3ece794ba3150dd6ebba7c4aa
