### ISSUE TITLE
Installing `scoutapm` extension no longer works

### ISSUE THREAD

**Issue by asgrim** [shivammathur/setup-php#738]
**Describe the bug**
There appears to be some kind of regression installing the `scoutapm` PHP extension. Not sure why at the moment. Previously specifying `extensions: scoutapm` would install the `scoutapm` extension. Example build from 2nd May [here](https://github.com/scoutapp/scout-apm-php/actions/runs/4862884357/jobs/8669935633#step:3:18).

Now, if I try the same job, I get the following error:

```
==> Setup Extensions
PHP Warning:  PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=/usr/lib/php/20170718/scoutapm.so from php.ini) in Unknown on line 0
✗ scoutapm Could not install scoutapm on PHP 7.2.34
Error: The process '/usr/bin/bash' failed with exit code 1
```

Example build from today [here](https://github.com/scoutapp/scout-apm-php/actions/runs/5142762906/jobs/9352419159#step:3:19).

This is correct, `scoutapm` is a Zend Extension, but previously whatever the `shivammathur/setup-php` action did to install it was working... 

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu, Windows

**PHP versions**
PHP 7.2 through to 8.2

**To Reproduce**

https://github.com/scoutapp/scout-apm-php/blob/a67f695640d073f6c7322e1b24f3e8af3881e729/.github/workflows/continuous-integration.yml#L391-L397

**Expected behavior**

I expect `scoutapm` to be successfully installed still.

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Sorry for the regression.

This is fixed in https://github.com/shivammathur/setup-php/commit/fb5054b163daf85f4e3cd73641c0a4b51ad32b6f. It will be in the next release.

**Comment by asgrim** [comment]
Thank you!
