### ISSUE TITLE
Unable to install gmp and bcmath extensions on i386

### ISSUE THREAD

**Issue by oschwald** [shivammathur/setup-php#744]
**Describe the bug**

In the past week, `i386` builds that depend on the `bcmath` or `gmp` extensions have started failing. Looking at the build logs, it [appears that the extension setup is failing](https://github.com/maxmind/MaxMind-DB-Reader-php/actions/runs/5301629791/jobs/9624877701#step:3:18):

![image](https://github.com/shivammathur/setup-php/assets/278835/78f5bba9-fc1b-4ff5-8bb9-2b084167bf4e)

Previously, this [worked file](https://github.com/maxmind/MaxMind-DB-Reader-php/actions/runs/5233416530/jobs/9448872424#step:3:18).

The `amd64` builds work as expected. I did try downgrading to 2.52.2, but that did not seem to help. I did not debug it further.

**Version**
- [X ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu on i386.

**PHP versions**

7.2-8.2

**To Reproduce**

https://github.com/maxmind/MaxMind-DB-Reader-php/blob/f8cd5d7f83e36b8f1b8de7e3dea149739f7a1bfd/.github/workflows/test.yml#L9-L61

**Expected behavior**

For `gmp` and `bcmatch` to be installed.

**Screenshots/Logs**

See above.

**Additional context**

None.

**Are you willing to submit a PR?**

I don't have any real insight into where the problem is.

**Comment by shivammathur** [comment]
@oschwald 

The `shivammathur/node` i386 image is based on Ubuntu 18.04. I haven't found a newer Ubuntu i386 image and `ppa:ondrej/php` does not support Ubuntu 18.04 anymore as it is deprecated.

**Comment by oschwald** [comment]
Thank you for the update. That is unfortunate. I think 18.04 was the last LTS release to support i386.

Maybe it would be worth adding a note to the extension section of the documentation.

**Comment by shivammathur** [comment]
@oschwald I have switched the base for i386 containers to Debian 12 in https://github.com/shivammathur/node-docker/commit/0c55baf6ab661edbd285c1e245224f3bab6c9e2b. So this should work again.

**Comment by oschwald** [comment]
Thank you!

**Comment by shivammathur** [comment]
@oschwald 
I cannot reproduce this, it might be that the PPA was down, please try running it again.
https://github.com/shivammathur/test-setup-php/actions/runs/5701114466/workflow
