### ISSUE TITLE
Using `extensions` with `none` leads to unexpected result across the operating systems

### ISSUE THREAD

**Issue by kubawerlos** [shivammathur/setup-php#749]
**Describe the bug**

**Version**
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu, Windows, and macOS, when macOS is especially painful.

**PHP versions**
8.2

**To Reproduce**
Workflow and it's summary: https://github.com/werlos/github-actions-php-extensions

**Expected behavior**
using `none` followed by `opcache` should behave the same (by enabling OPcache) for all the operating systems.

**Screenshots/Logs**
See the action in mentioned repo.

**Additional context**
Is it how operating systems (or homebrew?) differently treat what is "shared extension"?

**Are you willing to submit a PR?**
If I will be able to, need at least some guidance how target the problem.

**Comment by shivammathur** [comment]
Fixed re-enabling opcache on macOS in 5b2015e8fefd9b9f5fade844978da626bfd7fe2f. Will be in the next release.

It was not working correctly as homebrew installs the extension in a different directory than php's extension directory.

**Comment by shivammathur** [comment]
Fix released in [`2.25.5`](https://github.com/shivammathur/setup-php/releases/tag/2.25.5)

**Comment by kubawerlos** [comment]
Thank you @shivammathur 👍🏼
