### ISSUE TITLE
Installing ext-oci8 fails on PHP 8.3

### ISSUE THREAD

**Issue by derrabus** [shivammathur/setup-php#756]
**Describe the bug**
When enabling the OCI8 extension on PHP 8.3, Setup PHP fails with exit code 1.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 22.04

**PHP versions**
8.3

**To Reproduce**
https://github.com/doctrine/dbal/blob/195aad31e9596e4093d417583f98342b6f0ec986/.github/workflows/continuous-integration.yml#L137-L143

**Expected behavior**
PHP is installed with ext-oci8 enabled

**Screenshots/Logs**
```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.3
    extensions: oci8
    coverage: pcov
    ini-values: zend.assertions=1
    ini-file: production
  env:
    fail-fast: true
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.3.0-dev (null)

==> Setup Extensions
Error: The process '/usr/bin/bash' failed with exit code 1
```

https://github.com/doctrine/dbal/actions/runs/5760171338/job/15616096049?pr=6118#step:4:33

**Additional context**

**Are you willing to submit a PR?**
I wouldn't know how to debug this. 😓

**Comment by shivammathur** [comment]
@derrabus 
It should work now, please restart your workflow.

I added a check in https://github.com/shivammathur/php-builder/commit/d048151777913d3f5f8b96de691b021937d27993 to prevent this in future.

**Comment by derrabus** [comment]
It does! Thank you very much for your fast response!
