### ISSUE TITLE
Redis could not be installed on MacOS with PHP8.2

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#770]
**Describe the bug**

Redis could not be installed on MacOS with PHP8.2.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
8.2

**To Reproduce**
https://github.com/phalcon/cphalcon/actions/runs/6365608835/job/17282779290?pr=16446#step:4:40

**Expected behavior**
Redis installs on MacOS with PHP8.2

**Comment by shivammathur** [comment]
Apple and `brew` dropped support for macOS 11, so the new version of extensions cannot be built for the OS version. So, I would recommend upgrading `macos-11` in your workflow to `macos-12`.

**Comment by Jeckerson** [comment]
@shivammathur It worked, thank you!
