### ISSUE TITLE
`tools: php-cs-fixer:v3` takes 7 minutes to build

### ISSUE THREAD

**Issue by szepeviktor** [shivammathur/setup-php#773]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.1

**To Reproduce**
https://github.com/mlocati/unipoints/blob/22602389f51f93b8e53721e6434f1262284c4cad/.github/workflows/tests.yml#L19-L35

**Expected behavior**
Finish under 10 seconds

**Screenshots/Logs**
https://github.com/mlocati/unipoints/actions/runs/6684760233/job/18162351050

**Additional context**
PHIVE could download it as 1 file.

**Comment by szepeviktor** [comment]
⚠️ Not with 2.2.25

**Comment by shivammathur** [comment]
@szepeviktor

Thanks for reporting this.

Yes this is not related to `php-cs-fixer`, but the node process in v20 seems to get stuck after the script has run.

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/9855c76987e3b3bbb80f4e19697b69126f9ad03a

**Comment by szepeviktor** [comment]
Thank you.

**Comment by shivammathur** [comment]
Released the fix in https://github.com/shivammathur/setup-php/releases/tag/2.27.0
