### ISSUE TITLE
Module compiled with build ID=API20200930,TS

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#788]
**Describe the bug**
Recently, NTS and TS versions of `zephir_parser` stopped to work

```
PHP Warning:  PHP Startup: zephir_parser: Unable to initialize module
Module compiled with build ID=API20200930,TS
PHP    compiled with build ID=API20200930,NTS
These options need to match
 in Unknown on line 0
✗ zephir_parser Could not install zephir_parser on PHP 8.0.30
```

https://github.com/zephir-lang/zephir/actions/runs/6990819198/job/19020706260#step:3:36

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Any

**PHP versions**
Any

**To Reproduce**
https://github.com/zephir-lang/zephir/blob/development/.github/workflows/main.yml

**Expected behavior**
Work as previous for both: TS and NTS

**Comment by shivammathur** [comment]
@Jeckerson I was testing adding cache for zts builds on the develop branch, it should work now, but I would recommend switching back to `v2` to avoid this.
