### ISSUE TITLE
Mass failure after Ubuntu upgrade

### ISSUE THREAD

**Issue by iBotPeaches** [shivammathur/setup-php#798]
**Describe the bug**

All our builds are failing now (Including Laravel) after this change: https://github.com/shivammathur/php-ubuntu/commit/83d1155cd11a0178b4d7431a0c91ed6c1b7454ad

It manifest as an error of 

```
Error: Child process error (exit code 255): PHP Fatal error:  Declaration of Symfony\Component\Cache\CacheItem::expiresAt(?DateTimeInterface $expiration): static must be compatible with PsrExt\Cache\CacheItemInterface::expiresAt($expiration) in /home/runner/work/xxx-Laravel/xxx-Laravel/vendor/symfony/cache/CacheItem.php on line 65
PHP Fatal error:  Declaration of Monolog\Logger::emergency(Stringable|string $message, array $context = []): void must be compatible with PsrExt\Log\LoggerInterface::emergency($message, array $context = []) in /home/runner/work/PinchAPenny-Laravel/PinchAPenny-Laravel/vendor/monolog/monolog/src/Monolog/Logger.php on line 681
```

Which I found is claimed as a "buggy" extension by Symfony: https://github.com/symfony/symfony/issues/49984

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
All

**To Reproduce**
Run PHPStan?

**Expected behavior**
Not a crash

**Are you willing to submit a PR?**
I'd just revert this https://github.com/shivammathur/php-ubuntu/commit/83d1155cd11a0178b4d7431a0c91ed6c1b7454ad

**Comment by stevebauman** [comment]
Just started getting this too on all of my builds in GitHub actions.

**Comment by ralphjsmit** [comment]
Me too.

**Comment by mattwellss** [comment]
While waiting for a fix, the psr extension can be disabled
> Shared extensions can be disabled by prefixing them with a :. All extensions depending on the specified extension will also be disabled.

```
  steps:
    - uses: shivammathur/setup-php@[whatever]
      with:
        [other stuff]
        extensions: :psr
```

https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support

**Comment by percymamedy** [comment]
> While waiting for a fix, the psr extension can be disabled
> 
> > Shared extensions can be disabled by prefixing them with a :. All extensions depending on the specified extension will also be disabled.
> 
> ```
>   steps:
>     - uses: shivammathur/setup-php@[whatever]
>       with:
>         [other stuff]
>         extensions: :psr
> ```
> 
> https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support

That fix worked for me

**Comment by JonErickson** [comment]
Confirmed from Laravel staff in v10 you need to disable the psr extension. 

https://github.com/laravel/framework/issues/46165

**Comment by iBotPeaches** [comment]
Sure - I can go fix a ton of builds with disabling psr. It isn't that urgent though if I hopefully believe in the morning - that the author will just revert this and things will resume.

As you can see this extension at the core is this outdated PECL extension - https://pecl.php.net/package/psr. This is leading to what we see here.

![Screenshot 2023-12-06 at 4 50 55 PM](https://github.com/shivammathur/setup-php/assets/611784/377727cf-5aa1-4f99-a83f-283ad9ec801b)

So I don't think it merits a default include in the image and should be "opt-in" only.
