### ISSUE TITLE
Fail to setup `msgpack` on PHP >= 8.1 (Windows)

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#807]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows

**PHP versions**
>= 8.1

**To Reproduce**
[](https://github.com/phalcon/cphalcon/actions/runs/7309149732/job/19916477660#step:4:39)

**Expected behavior**
Work as previously.

**Comment by shivammathur** [comment]
Released [`2.29.0`](https://github.com/shivammathur/setup-php/releases/tag/2.29.0) with the fix.
