### ISSUE TITLE
Configure `COMPOSER_PROCESS_TIMEOUT`

### ISSUE THREAD

**Issue by Bilge** [shivammathur/setup-php#811]
**Describe the feature**
Configure `COMPOSER_PROCESS_TIMEOUT`.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
I just had two `composer test` jobs fail on GitHub Actions after a 6 hours timeout (the maximum allowed), burning through 720 minutes of allowance for no reason, all because this action quietly disables the timeout feature entirely. This is not safe or a good idea; the timeout is enabled by default for good reason. Regardless of whether you agree, this should be configurable.

**Describe alternatives**
I could probably manually override the timeout in each step or command where I require the timeout, though doing so would be laborious and hacky.

**Are you willing to submit a PR?**
No, I don't know TypeScript or how to test actions in development.

**Comment by Bilge** [comment]
Yes, that is what I was driving at.

**Comment by shivammathur** [comment]
Added support in https://github.com/shivammathur/setup-php/commit/a6ce3f5633527c57a57c95fea21a2f686f7d9acb. Will be in next release.

**Comment by shivammathur** [comment]
Released in [2.30.0](https://github.com/shivammathur/setup-php/releases/tag/2.30.0).
