### ISSUE TITLE
Customize SAPIs

### ISSUE THREAD

**Issue by arbourd** [shivammathur/setup-php#814]
**Describe the feature**

Customize SAPIs for versions of PHP.

**Version**

- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Being able to install the `embed` SAPI by default for `8.1` and `8.2`, which appears to be missing, but is present for `8.3`.

**Describe alternatives**

I am not a PHP dev and not aware of any alternatives, but am open to them.

**Additional context**

I have found the `sapi` branch and noticed it was not completed.

Again, I'm extremely ignorant of PHP as a whole and any context you can share with me re: SAPIs and changing them would be greatly appreciated 🙏🏻 

**Are you willing to submit a PR?**

Perhaps! But I'd need some context on how the install works first, based on the `sapi` branch.

**Comment by shivammathur** [comment]
I never got to complete the SAPI support, so any contribution to add support for that is welcome.

I have added embed to the cached builds in https://github.com/shivammathur/php-ubuntu/commit/36e6e96785491b010a7383452a94eec0271f9baa. Use `update: true` in `env` and embed should be available now for all versions.
