### ISSUE TITLE
Installing a Debug Build of PHP does not work

### ISSUE THREAD

**Issue by TimWolla** [shivammathur/setup-php#816]
**Describe the bug**

Installing a Debug Build as per https://github.com/shivammathur/setup-php?tab=readme-ov-file#debug-build-setup does not appear to work.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

Any of 7.4 - 8.3 (possible more).

**To Reproduce**

```
name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.3"
          - "8.2"
          - "8.1"
          - "8.0"
          - "7.4"
    steps:
    - uses: actions/checkout@v4
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php }}"
      env:
        debug: "true"
    - run: php -i
    - run: |
        php -i |grep Debug
```

**Expected behavior**

I expected `php -i` to indicate that the PHP build is a debug build.

**Screenshots/Logs**

```
Run php -i |grep Debug
Debug Build => no
APCu Debugging => Disabled
Debug => No
Step Debugger => ✘ disabled
```

**Additional context**

Example run at: https://github.com/TimWolla/setup-php-debug/actions/runs/7874782401

**Are you willing to submit a PR?**

No, as I could not find where it goes wrong. I confirmed that the `debug` environment variable is properly set.

**Comment by shivammathur** [comment]
`php -i | grep Debug` says no, as it is built without `--enable-debug`, but with `-g` in `CFLAGS`.

From that build [`dh_strip`](https://manpages.debian.org/testing/debhelper/dh_strip.1.en.html) removes the debug symbols, so they can be packaged separately, this way it does not need to be built twice. All packaging for Debian is done similarly.

When debug is set to  true is set, it adds those stripped debug symbols to `/var/lib/debug/.build-id` directory. Tools like `objdump` and `gdb` should pick `debuginfo` from there.

**Comment by TimWolla** [comment]
I see. Calling it a “Debug Build Setup” without it actually being a Debug Build of PHP certainly was confusing to me.

Do you plan to provide *actual* Debug Builds with your Action? If not, I would suggest adding a clarification to the README that the “Debug Build Setup” will just install the debug symbols.

Or perhaps it would make sense to always install the debug symbols, GitHub Actions is for testing and debugging after all and having symbols available at all times certainly would not hurt.

**Comment by shivammathur** [comment]
I have tried to improve the documentation for this in https://github.com/shivammathur/setup-php/commit/1a5ac4aa9a4ee5f52acf166f3deebbd514f5735a but switching to debug by default would mean the build size would increase by 3 to 5 times for all, while a very few CI workflows use debug.
Ref: https://github.com/shivammathur/php-ubuntu/releases/tag/builds

**Comment by DanielEScherzer** [comment]
Would it be possible to add an option for using debug builds? For various PHP 8.5 CI flows I have seen segmentation faults which indicate an issue with PHP (https://github.com/symfony/polyfill/actions/runs/17242315471/job/48922680806?pr=543) and it would help to see if there were any assertions that failed
