### ISSUE TITLE
php-version: 'latest' and 'dev'

### ISSUE THREAD

**Issue by fulldecent** [shivammathur/setup-php#826]
**Describe the feature**

Add named version tags

**Version**

- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

Can we please add named versions which resolve to the latest active development version and the latest nightlies version?

This will allow us to create build scripts that are robust and work on the latest versions when they come out without having to be informed of these happenings and remembering what steps need to go when they happen.

**Comment by shivammathur** [comment]
Currently `php-version: latest` resolves to 8.3 and `php-version: nightly` resolves to 8.4. These should cover the requirements you mentioned.

https://github.com/shivammathur/setup-php?tab=readme-ov-file#php-version-optional

**Comment by fulldecent** [comment]
Awesome, thank you!
