### ISSUE TITLE
ssh2 failing to install with php 8.2

### ISSUE THREAD

**Issue by jaysen-fullbay** [shivammathur/setup-php#828]
**Describe the bug**
Approximately 2 hours ago (9:30am mountain time, 3/20/2024) all of my builds that were previously working started to fail saying `ssh2: Could not install ssh2 on PHP 8.2.15`.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ x ] `v2`
- [ ] `v1`

**Runners**

- [ x ] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.2.4 (but setup-php installs 8.2.15)

**To Reproduce**
    env:
      php-version: '8.2.4'
      php-extensions: curl, json, simplexml, soap, ssh2, zip
      php-extension-cache-key: cache-v1
    steps:
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}
          tools: none

**Expected behavior**
I expect php to be installed with the ssh2 extension

**Screenshots/Logs**
![image](https://github.com/shivammathur/setup-php/assets/95240010/84d888fc-7974-4246-9b39-29fc424d3fe3)

**Comment by jaysen-fullbay** [comment]
> Encountered something similar in our own flows installing `gnupg` over `8.1.25` using the configuration
> 
> ```
>     - uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35 # v2.28.0
>       with:
>         tools: phpunit, composer:v2.7.1
>         php-version: 8.1.27
>         coverage: none
>         extensions: gnupg, ast-1.0.16
> ```
> 
> <img alt="image" width="337" src="https://private-user-images.githubusercontent.com/5258036/314587935-30df0313-c7a6-4291-a51b-eb18a3c202ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTMxODksIm5iZiI6MTcxMDk1Mjg4OSwicGF0aCI6Ii81MjU4MDM2LzMxNDU4NzkzNS0zMGRmMDMxMy1jN2E2LTQyOTEtYTUxYi1lYjE4YTNjMjAyYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMTY0MTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUwN2M0YmVhOGY5N2I1MTZkNmZhZWU5NTkyY2JlNTcwOTBlZjMzYzA0ZjRhNjQ3MzQ3MzQxMGIwOTE1MDc0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JMGZTdYl26Lq0SAie4GZi6f1yZ09xYfLzbI8ROEcUoE">
> Can we have the entire action fail in this case? I don't think it helps to have a broken extension and then attempt to move forward in the rest of the action. Thanks!

[johnmlee101](https://github.com/johnmlee101) FYI, there is already a "fail-fast" option that will kill the entire action if an extension fails.
![image](https://github.com/shivammathur/setup-php/assets/95240010/3109befc-2cb8-42f6-b1a1-9d91da3e00d6)

**Comment by pluseg** [comment]
Same but for `mailparse` extension and PHP 8.2.15. Tried both on 2.29.0 and 2.30.0 versions of setup-php.
```
Run shivammathur/setup-php@2.30.0
  with:
    coverage: none
    php-version: 8.2.14
    tools: composer:v2, pecl
    extensions: mbstring, amqp, ctype, iconv, mailparse, pdo
    ini-file: production
  env:
    MESSENGER_TRANSPORT_DSN_ENTITY_CACHE_UPDATE: in-memory://
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/2.30.0/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.2.15

==> Setup Extensions
✓ mbstring Enabled
✓ amqp Enabled
✓ ctype Enabled
✓ iconv Enabled
✗ mailparse Could not install mailparse on PHP 8.2.15
✓ pdo Enabled

==> Setup Tools
✓ composer Added composer 2.7.2
✓ PECL Added PECL 1.[10](https://github.com/celebrityagent/celebrityagent/actions/runs/8362309078/job/22894602343#step:4:10).[12](https://github.com/celebrityagent/celebrityagent/actions/runs/8362309078/job/22894602343#step:4:12)

==> Setup Coverage
✓ none Disabled Xdebug and PCOV
```

**Comment by shivammathur** [comment]
Launchpad PPA hosting is down for maintenance. This affects downloading the extension packages.
https://twitter.com/launchpadstatus/status/1770482383453577682

**Comment by shivammathur** [comment]
This has been resolved. Please restart your workflows.
https://twitter.com/launchpadstatus/status/1770532196257849798

**Comment by aykonsvk** [comment]
Any updates on this? I'm getting it today:

`Run shivammathur/setup-php@2.30.2
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/2.30.2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.1.31

==> Setup Extensions
✓ pdo_sqlite Enabled
✗ rdkafka Could not install rdkafka on PHP 8.1.31

==> Setup Tools
✓ composer Added composer 2.8.5

==> Setup Coverage
✓ pcov.enabled=1 Added to php.ini
✓ pcov PCOV 1.0.11 enabled as coverage driver

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor`
