### ISSUE TITLE
Imposible install apc, mycript, PHP 7.3, 7.4.

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#829]
Imposible install extensions `apc`, `mycript`, `PHP 7.3, 7.4`.

![image](https://github.com/shivammathur/setup-php/assets/42547589/9714df26-8510-4887-bc56-1c22ca1d729b)

**Comment by terabytesoftw** [comment]
thks 👍

**Comment by shivammathur** [comment]
This has been resolved. Please restart your workflows.
https://twitter.com/launchpadstatus/status/1770532196257849798
