### ISSUE TITLE
PHP8.3 `RecursiveDirectoryIterator::__construct : Failed to open directory: Not a directory`

### ISSUE THREAD

**Issue by limingxinleo** [shivammathur/setup-php#832]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
PHP8.3

**To Reproduce**

When I run test cases in PHP8.3, it will be thrown this exception

`RecursiveDirectoryIterator::__construct : Failed to open directory: Not a directory`

The github actions yml:

https://github.com/hyperf/hyperf/blob/master/.github/workflows/test.yml#L31

**Screenshots/Logs**
![image](https://github.com/shivammathur/setup-php/assets/16648551/d9efdf59-08d5-4719-a6c7-bd78b5043f40)

**Comment by shivammathur** [comment]
@limingxinleo This does not seem to be related to setup-php.
