### ISSUE TITLE
Improve error reporting when ubuntu launchpad is down?

### ISSUE THREAD

**Issue by SystemKeeper** [shivammathur/setup-php#834]
**Describe the feature**

Today ubuntu launchpad went into maintenance (see https://ubuntu.social/@launchpadstatus/112286753813553221) and installation of php failed because of that:

<img width="543" alt="image" src="https://github.com/shivammathur/setup-php/assets/1580193/88a46cd7-a515-4fa6-8cfc-6a3178008af5">

I am wondering if it would be possible to output a message that indicates why the installation failed in that case?

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Describe alternatives**

I guess there's no alternative instead of guessing what happens.

**Are you willing to submit a PR?**

Yes in general, but never looked at the setup-php code in more detail.

**Comment by shivammathur** [comment]
@SystemKeeper 

I plan to add a mirror for the [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) we use as a fallback to avoid this in future.

**Comment by rukaelin** [comment]
Hi there, we experienced the same issue last week. it's great to see that you are working on this, thank you @shivammathur 🙏

**Comment by samansupriadi** [comment]
Hi i have similiar issue

![image](https://github.com/shivammathur/setup-php/assets/12885184/b3162132-8a3c-44b0-aeca-4b8cd43f702a)

**Comment by shivammathur** [comment]
@samansupriadi Please create a separate issue with details about your workflow.

**Comment by dac-humi** [comment]
Hello, thank you for your work on this repo. It is very much appreciated. 🙏 

Major PPA outage today triggering fail. [Acknowledged by Canonical here.](https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQF3uEO2vrSV2IkKQrdvV0X5EarpASdRjmRm4vWcLYw38Q==)

Although you said:

> I plan to add a mirror for the [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) we use as a fallback to avoid this in future.

I think this ticket is more about showing _some_ logs when an incident like this occurs. Right now, we have to trigger by changing `shivammathur/setup-php@2.30.5` to `shivammathur/setup-php@verbose@verbose`

Then I see a massive dump that includes the one line I care about:

`Cannot initiate the connection to ppa.launchpad.net:80 (2620:2d:4000:1::81). - connect (101: Network is unreachable)`

Would be nice if error was shown without verbose.

**Comment by shivammathur** [comment]
@dac-humi 

I understand that, but to display that error in the `apt-get update` command it is required to change how logs are piped in the action and that change is not trivial, and I cannot work on that right now.

It would be much easier for me to maintain a fallback mirror for the PPA.

**Comment by shivammathur** [comment]
Added a fallback mirror in [2.31.0](https://github.com/shivammathur/setup-php/releases/tag/2.31.0).
