### ISSUE TITLE
Add `shipmonk/composer-dependency-analyser` tool

### ISSUE THREAD

**Issue by alies-dev** [shivammathur/setup-php#841]
**Describe the feature**
`shipmonk/composer-dependency-analyser` is a faster alternative to `composer-unused` + `maglnet/ComposerRequireChecker`

GitHub: https://github.com/shipmonk-rnd/composer-dependency-analyser

**Comment by shivammathur** [comment]
Happy to add it, are you willing to create a PR?

**Comment by shivammathur** [comment]
Added in #859

**Comment by shivammathur** [comment]
Released in [`2.32.0`](https://github.com/shivammathur/setup-php/releases/tag/2.32.0).
