### ISSUE TITLE
Incorrect pick of thread-safe `zephir_parser` package in MacOS

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#846]
**Describe the bug**

```
PHP Warning:  PHP Startup: zephir_parser: Unable to initialize module
Module compiled with build ID=API20200930,NTS
PHP    compiled with build ID=API20200930,TS
These options need to match
 in Unknown on line 0
✗ zephir_parser Could not install zephir_parser on PHP 8.0.30
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
Any

**To Reproduce**
https://github.com/zephir-lang/zephir/blob/3580126998bd2c279f31c5bbd4e0558a6bdb1ed5/.github/workflows/main.yml#L65

**Comment by shivammathur** [comment]
@Jeckerson 
Please check the ts builds for macos in the 1.6.0 release
It is just downloading the zip from the release and extracting it.
https://github.com/shivammathur/test-setup-php/actions/runs/9334920513/job/25693699936#step:2:452

**Comment by Jeckerson** [comment]
After new release of Zephir parser (1.6.1) problem still persists
https://github.com/zephir-lang/zephir/actions/runs/9357645619/job/25757833733#step:3:31

**Comment by shivammathur** [comment]
@Jeckerson 
Please update the version in the workflow, or you can remove it so that it installs the latest one.
https://github.com/zephir-lang/zephir/actions/runs/9357645619/workflow#L20

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/9362899816/workflow

**Comment by Jeckerson** [comment]
Now all works fine, thank you!
