### ISSUE TITLE
No .ini files in PHP8.3 MacOS

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#847]
**Describe the bug**
```
==> Setup PHP
chmod: /usr/local/etc/php/8.3-zts/php.ini: No such file or directory
cp: /usr/local/etc/php/8.3-zts/php.ini: No such file or directory
cp: /usr/local/etc/php/8.3-zts/php.ini-production: No such file or directory
✓ PHP Updated to PHP 8.3.7
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
PHP8.3

**To Reproduce**
https://github.com/zephir-lang/php-zephir-parser/actions/runs/9339343249/job/25703586564#step:3:14

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/fc14643b0a99ee9db10a3c025a33d76544fa3761

**Comment by Jeckerson** [comment]
@shivammathur Same problem
https://github.com/zephir-lang/php-zephir-parser/pull/152/commits/dbad1b7c6260c47781afbdf9be10213b1ac82625

**Comment by shivammathur** [comment]
@Jeckerson 

Please check the error again and try rerunning the failed job. It seems to have built correctly, but failed to upload the artifact.
https://github.com/zephir-lang/php-zephir-parser/actions/runs/9340256530/job/25705603437#step:10:21

**Comment by shivammathur** [comment]
@Jeckerson 
Please update the tag here as well and rerun.
https://github.com/zephir-lang/php-zephir-parser/blob/dbad1b7c6260c47781afbdf9be10213b1ac82625/.github/workflows/ci.yml#L70

**Comment by Jeckerson** [comment]
@shivammathur Now seems to work, thank you!

**Comment by shivammathur** [comment]
Released https://github.com/shivammathur/setup-php/releases/tag/2.30.5 with the fix
