### ISSUE TITLE
The win32 script is overly complex

### ISSUE THREAD

**Issue by mlocati** [shivammathur/setup-php#85]
The `win32.ps1` file is overly complex, it could be simplified by using commands that come with PhpManager.
For example:
```
Add-Content C:\tools\php\php.ini "extension=php_openssl.dll`nextension=php_curl.dll"
```
can be replaced by
```
Enable-PhpExtension openssl,curl
```

Furthermore, it doesn't configure the curl/openssl extensions to a valid list of Certification Authorities (so, https requests will fail).

**Comment by shivammathur** [comment]
Fixed in #86
