### ISSUE TITLE
All Mac runners failing: No such file or directory

### ISSUE THREAD

**Issue by caendesilva** [shivammathur/setup-php#857]
Mac runners on PHP 8.1, 8.2, 8.3 are failing across the board.

```
Run shivammathur/setup-php@v2
/bin/bash /Users/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
sed: : No such file or directory
grep: : No such file or directory
/Users/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/unix.sh: line [1](https://github.com/hydephp/develop/actions/runs/9922425058/job/27411474130#step:2:1)89: php: command not found
mkdir: : No such file or directory
chmod: /php.ini: No such file or directory
/Users/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/unix.sh: line 1[8](https://github.com/hydephp/develop/actions/runs/9922425058/job/27411474130#step:2:9)4: php_config: parameter null or not set
cp: /php.ini: No such file or directory
cp: /php.ini-production: No such file or directory
✗ PHP Could not setup PHP 8.3
Error: The process '/bin/bash' failed with exit code 1
```

**Comment by shivammathur** [comment]
@caendesilva 

Homebrew has enabled attestation for everyone using `HOMEBREW_DEVELOPER=1` in https://github.com/Homebrew/brew/pull/17692.

Now it requires setting `HOMEBREW_GITHUB_API_TOKEN` for it to check dependencies it downloads.

I'm testing removing `HOMEBREW_DEVELOPER` and will do a hotfix release if nothing breaks.

**Comment by caendesilva** [comment]
**Reminder to people coming across this:** Working on behalf of a business? This action probably saves your company a huge amount of money. You can help prevent issues like these from happening as often by sponsoring the maintainer at https://github.com/sponsors/shivammathur. See it as an investment where you'll save a ton of cash in the long term by having to spend less time on issues like these.

**Comment by shivammathur** [comment]
This has been resolved in https://github.com/Homebrew/brew/pull/17713.
