### ISSUE TITLE
Nightly build not building ?

### ISSUE THREAD

**Issue by jrfnl** [shivammathur/setup-php#861]
I just wanted to do a test run for a specific project with the latest PHP 8.4 (well, "latest" as in: build somewhere in the last 24 hours), what with so many PHP 8.4 deprecation commits going in over the last few days.

To verify which deprecation commits would be included for the test run, I checked the commit hash:
```
 ==> Setup PHP
✓ PHP Installed PHP 8.4.0-dev (634708a14f9546cc81bc5f9bf269ec0c46743a0f)
```

... which takes me to a commit from three days ago: https://github.com/php/php-src/commit/634708a14f9546cc81bc5f9bf269ec0c46743a0f which surprised me.

It may well be fine, but I figured a heads-up to check if the nightly builds are still building may be appropriate ?

**Comment by jrfnl** [comment]
Just found https://github.com/shivammathur/php-builder and I can see in the build failures in the [Actions summary](https://github.com/shivammathur/php-builder/actions), so my suspicion has been confirmed.

@shivammathur I can also see that you have fixed this a couple of times in the last week already, only for things to break again the next day. Sorry PHP 8.4 is causing you so much work!

**Comment by shivammathur** [comment]
@jrfnl 

Yes, recent changes have required the patches to be updated quite frequently. 

It has been fixed for now.

**Comment by jrfnl** [comment]
Thank you @shivammathur!
