### ISSUE TITLE
PHP 8.4: could not install `imap`

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#866]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.4.0-dev`

**To Reproduce**

* YML file: https://github.com/ddeboer/imap/blob/php_84/.github/workflows/ci.yaml#L63
* Result: https://github.com/ddeboer/imap/actions/runs/11027077228/job/30624718688?pr=578#step:3:94

NOTE
====

`imap` extension has been unbundled from `php-src` and moved to `PECL`:

1. RFC: https://wiki.php.net/rfc/unbundle_imap_pspell_oci8
2. PR: https://github.com/php/php-src/pull/13190
3. PECL: https://pecl.php.net/package/imap

**Comment by shivammathur** [comment]
@Slamdunk The latest release on PECL is not compatible with PHP 8.4, once a new version is tagged it should start working
https://github.com/php/pecl-mail-imap/issues/12

**Comment by shivammathur** [comment]
@Slamdunk i have added the extension to build alongside PHP from the main branch for now. It should not fail anymore.
https://github.com/shivammathur/php-builder/commit/6f4cbbbce326d87297ba779f75953d6546cf320a

**Comment by Slamdunk** [comment]
It works, thank you very much :muscle:
