### ISSUE TITLE
Problem with mongodb-1.20

### ISSUE THREAD

**Issue by OskarStark** [shivammathur/setup-php#868]
Hi, I am facing a bug where I cannot install mongodb-1.20 in my GHA:
![CleanShot 2024-09-28 at 16 06 26@2x](https://github.com/user-attachments/assets/6c2c75d8-a870-4174-a2a9-869c1433c76b)

![CleanShot 2024-09-28 at 16 06 32@2x](https://github.com/user-attachments/assets/4ac17c1a-1adb-4f17-ba6a-032df91ebf94)

I cannot See which version is installed, I only see `Enabled`

Can you help?

Thanks

**Comment by OskarStark** [comment]
cc @alcaeus

**Comment by OskarStark** [comment]
You can check failing test cases here:
* https://github.com/php-llm/llm-chain/pull/51

**Comment by shivammathur** [comment]
@OskarStark I have updated the builds cache. This should be fixed now.

**Comment by OskarStark** [comment]
Many thanks

**Comment by GromNaN** [comment]
Hello @shivammathur, a [new version 1.21.0](https://pecl.php.net/package/mongodb/1.21.0) of `ext-mongodb` have been release. Is it possible to update the build cache please?

**Comment by shivammathur** [comment]
@GromNaN Done.
