### ISSUE TITLE
Support `php-version: preinstalled`

### ISSUE THREAD

**Issue by SystemKeeper** [shivammathur/setup-php#872]
**Describe the feature**
Most runners (be it GitHub-Hosted or Self-Hosted) have php versions pre-installed. For some workflows the performance is more important than the exact php version. So when targeting `ubuntu-24.04` it makes sense to use PHP 8.3, while on `ubuntu-22.04` it makes sense to use PHP 8.1. Therefore I was thinking if adding something like `php-version: preinstalled` or `php-version: highest-preinstalled` would make sense and `setup-php` would automatically choose the (highest) version that's already inside the image?

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
Reduce bandwidth consumption and time to setup. 

**Describe alternatives**
Manually adjust the workflows.

**Additional context**
-

**Are you willing to submit a PR?**
Generally yes, although no idea where to start.

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/setup-php/commit/da729085ef6e82caa5d7ef97fd6c254d304beb7d

**Comment by SystemKeeper** [comment]
Awesome ❤️ 

Quick question, the linked commit says `pre-installed` in the docs, but checks for `pre` in the scripts?

**Comment by shivammathur** [comment]
It should accept `pre`, `pre-installed` and `preinstalled`.

**Comment by SystemKeeper** [comment]
But the check is only for "pre":
https://github.com/shivammathur/setup-php/blob/775fa76ea4f13164a58f45785aaf2a5ce727291d/src/scripts/unix.sh#L189

Or am I missing something?

**Comment by shivammathur** [comment]
It only passes first 3 characters to the scripts.
https://github.com/shivammathur/setup-php/blob/775fa76ea4f13164a58f45785aaf2a5ce727291d/src/utils.ts#L61-L74

**Comment by shivammathur** [comment]
Released in [`2.32.0`](https://github.com/shivammathur/setup-php/releases/tag/2.32.0).
