### ISSUE TITLE
Please remove "self hosted" from issue template

### ISSUE THREAD

**Issue by withinboredom** [shivammathur/setup-php#879]
**Describe the bug**

If you want to search for issues affecting "self hosted runners" and attempt to search for it, then all issues are returned because it is part of the template. 

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

All

**PHP versions**

All

**To Reproduce**

Attempt to discover if an issue affecting self-hosted runners has already been reported.

**Expected behavior**

To be able to find issues related to self hosted runners

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
I understand, but It is important to know the runner when an issue is submitted. Might be a good idea to replace the current templates with issue forms.

For now, Please use `label: self-hosted` as the search term, I have tried to tag them with the label.
https://github.com/shivammathur/setup-php/issues?q=label%3Aself-hosted

Also, if you are facing a particular issue, feel free to create a new one with the details.
