### ISSUE TITLE
Bug: Getting PHP 8.4.0 on windows

### ISSUE THREAD

**Issue by joehoyle** [shivammathur/setup-php#885]
### Describe the bug

We're seeing Windows CI jobs only get PHP 8.4.0, even though 8.4.1 is available (and was 8.4.0 actually a release?!). Even when forcing `php-version: 8.4.1` I'm seeing 8.4.0:

<img width="561" alt="Screenshot 2024-11-25 at 2 23 04 PM" src="https://github.com/user-attachments/assets/500e4207-5408-41cf-a823-2e0827584946">

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Windows-latest

### PHP versions

PHP 8.4 dev

### To Reproduce

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.1'
        env:
          debug: true
```

### Expected behavior

PHP 8.4.1 is installed

### Are you willing to submit a PR?

No

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/php-builder-windows/commit/3452b4e1d93773b6fc4dc20d04f53095f38347f1

**Comment by Xenira** [comment]
Seems to be working. Thank you!

**Comment by joehoyle** [comment]
Thanks @shivammathur !
