### ISSUE TITLE
Bug: PHP 8.3 Fails

### ISSUE THREAD

**Issue by onairmarc** [shivammathur/setup-php#893]
### Describe the bug

Running with PHP 8.3 fails during setup. This action is called from a reusable workflow. The default PHP version that we specify is 8.3, however the setup fails and therefore the rest of the pipeline cannot proceed.

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-latest

### PHP versions

PHP 8.3

### To Reproduce

Call the workflow specifying PHP version 8.3

### Expected behavior

The action should successfully setup PHP without error.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/0b996d07-d0d3-433b-9917-04daf4969f73)
![image](https://github.com/user-attachments/assets/63e9b9a7-5baa-4995-9447-0d37bf4905a2)

### Are you willing to submit a PR?

Yes

**Comment by Tailzip** [comment]
Facing exact same issue, started a few minutes ago

**Comment by onairmarc** [comment]
Yep! Everything was working fine until suddenly it all came crashing down.

**Comment by cedaesca** [comment]
Same problem here

**Comment by CodeWithKyrian** [comment]
Same issue here as well

**Comment by yojahny55** [comment]
Same issue with 8.2, it seems a problem with the release file
![image](https://github.com/user-attachments/assets/46254ad5-9346-428d-b69a-ac13756c1e8d)
Refererence here: https://github.com/shivammathur/setup-php/issues/789#issuecomment-1826799404

**Comment by WildanMZaki** [comment]
Facing same problem with 8.2 version

**Comment by richard015ar** [comment]
same here

**Comment by tannerhelton** [comment]
same here version 8.2

**Comment by nguereza-tony** [comment]
Same issue with 7.4

**Comment by westonruter** [comment]
Same with `latest` (`8.4`):

![image](https://github.com/user-attachments/assets/4ca3d1d3-9e92-4381-b139-0c30b13a488d)

**Comment by michaelnguyen2021** [comment]
same issue with php 8.2

<img width="1291" alt="Screenshot 2024-12-14 at 11 03 54 PM" src="https://github.com/user-attachments/assets/62770f05-3568-4c1d-b300-91522b13f6f2" />

**Comment by ofirya-fullpath** [comment]
Same issue with PHP 8.3

**Comment by techgaun** [comment]
I wonder if this is failing only on github environment. I pulled down `setup-php` and tested locally. We run php8.2 and it works fine. The error is coming from https://github.com/shivammathur/setup-php/blob/v2/src/scripts/linux.sh#L270-L271 (or equivalent probably).

The issue seems on `command -v php8.2` not working. On testing locally, the binary works fine.

The `run.sh` script looks as below:

```shell
. /run/act/actions/shivammathur-setup-php@v2/src/scripts/linux.sh 8.2 production
step_log "Setup Tools"
add_tool https://github.com/shivammathur/composer-cache/releases/latest/download/composer-8.2-2.phar,https://dl.cloudsmith.io/public/shivammathur/composer-cache/raw/files/composer-8.2-2.phar,https://getcomposer.org/composer-2.phar composer 2
step_log "Setup Coverage"

step_log "Setup Extensions" >/dev/null 2>&1

disable_extension pcov false >/dev/null 2>&1

step_log "Setup Extensions" >/dev/null 2>&1

disable_extension xdebug false >/dev/null 2>&1
add_log "$tick" "none" "Disabled Xdebug and PCOV"
step_log "Sponsor setup-php"
```

so its failing on the first line itself. Need to debug further but maybe github IP space is somehow not able to download the some artifact.

**Comment by Tailzip** [comment]
Switching runner from `ubuntu-latest` (22.04) to `ubuntu-24.04` works.

**Comment by mostafaznv** [comment]
I am experiencing the same issue with versions 8.2, 8.3, and 8.4. However, version 8.1 runs smoothly.

**Comment by nn6v6nn** [comment]
> Same issue here as well for 8.2, 8.3 and 8.4. 8.1 runs smoothtly though

Github Runner is Ubuntu 22.04 , and pre-installed php 8.1

**Comment by 3x1io** [comment]
i have the same issue on PHP 8.1 

![Screenshot 2024-12-15 at 9 56 45 AM](https://github.com/user-attachments/assets/5eea1bfd-4293-42fc-b660-d6fb7be127ed)

**Comment by abdulalief** [comment]
downgrade runner ubuntu-latest to Ubuntu 22.04, version php 7.2, 7.3, 8.2   Facing same problem 
![Screenshot 2024-12-15 155619](https://github.com/user-attachments/assets/b41f404e-f72a-4f74-a206-37afd41e33b3)

**Comment by abdulalief** [comment]
runner ubuntu 24.04 also same problem
![Screenshot 2024-12-15 155929](https://github.com/user-attachments/assets/be308a05-48d8-48d1-adda-bf413bc651a7)

**Comment by szepeviktor** [comment]
```
PHP Could not setup PHP 7.4
```

**Comment by 3x1io** [comment]
> Switching runner from `ubuntu-latest` (22.04) to `ubuntu-24.04` works (EDIT: as a temporary workaround).

not working for me

**Comment by midnite81** [comment]
Facing the same issue

**Comment by shivammathur** [comment]
This has been fixed.
Please restart your workflows.

**Comment by techgaun** [comment]
Great, thanks for fixing! this seems to be coming from https://github.com/shivammathur/php-ubuntu and fix probably on https://github.com/shivammathur/php-ubuntu/commit/d893807f8a6726c33600d0dbfd601391b57791e5 for anyone interested
