### ISSUE TITLE
Feature: Specify a different path of composer.json file

### ISSUE THREAD

**Issue by meteorlxy** [shivammathur/setup-php#894]
### Describe the feature

Per the docs:

> php-version (optional)
> - ...
> - If not specified, it looks for the following in order:
>   - The `php-version-file` input if it exists
>   - A `composer.lock` file and the `platform-overrides.php` value
>   - A `composer.json` file and the `config.platform.php` value

However, if `composer.json` file is in a different sub directory, it could not be located correctly.

So it would be better to support specifying a different path of `composer.json` file.

### Please check the latest release

- [X] I have checked releases, and the feature is missing in the latest patch version of `v2`.

### Underlying issue

Currently the filepath is hard-coded. It would be better to make it customizable:

https://github.com/shivammathur/setup-php/blob/85a8dfd0c711cf13677391db4c529061ab491414/src/utils.ts#L455-L456

### Are you willing to submit a PR?

Yes

**Comment by shivammathur** [comment]
Added in https://github.com/shivammathur/setup-php/commit/84f76b1fc988dcf5f9444a21b9cb53ddf89980a3
