### ISSUE TITLE
Bug: "wrong" PHP 8.3 version installed when setup-php used twice in workflow

### ISSUE THREAD

**Issue by jrfnl** [shivammathur/setup-php#895]
### Describe the bug

When installing PHP, setup-php will always install the latest released version of specific PHP minor.

The bug I'm currently seeing is one where this is not happening when setup-php is used twice in a workflow and the second time PHP 8.3 is being installed.

I've done some investigating and it looks like this issue **_only_** occurs with PHP 8.3.

This is a table with my findings (can be verified via the GH Actions logs link posted below):

PHP | Single install | Double install
--- | --- | ---
7.2 | 7.2.34 | 7.2.34
7.3 | 7.3.33 | 7.3.33
7.4 | 7.4.33 | 7.4.33
8.0 | 8.0.30 | 8.0.30
8.1 | 8.1.31 | 8.1.31
8.2 | 8.2.26 | 8.2.26
8.3 | 8.3.14 | **8.3.6** :point_left
8.4 | 8.4.1 | 8.4.1

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-latest

### PHP versions

8.3

### To Reproduce

I've testing the issue in isolation - a demo of the issue can be found here:
* Workflow: https://github.com/jrfnl/bug-report-reproduction-scenarios/blob/setup-php/php-version-issue/.github/workflows/test.yml
* Test run: https://github.com/jrfnl/bug-report-reproduction-scenarios/actions/runs/12393747114/job/34595664865

### Expected behavior

I expected PHP 8.3.14 to be installed, but I got PHP 8.3.6 instead.

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/1e53b856-2fec-4f2a-a814-96b685c4d153)

### Additional context

Would love to submit a PR, but I searched the code base and couldn't find any direct clue as to why this is happening.

### Are you willing to submit a PR?

No

**Comment by shivammathur** [comment]
@jrfnl 

Please test if this happens even if you set update env to true in the setup-php step.

**Comment by shivammathur** [comment]
I have identified why this happens.

We have a logic to force update if the [`ondrej/php`](https://launchpad.net/~ondrej/+archive/ubuntu/php) PPA is not present on the runner (ubuntu-22.04 and ubuntu-24.04). So when it runs for the first time with PHP 7.4, it adds that PPA and on the next run, now that it has the PPA update is not set to true.

I will try to fix this in the next release that we maintain the update logic on subsequent runs in the same job, but the workaround to specify `update: true` env should help in avoiding this all together.

**Comment by jrfnl** [comment]
@shivammathur Thank you - as always - for your super-fast response.

I've added a second commit to the reproduction branch and [can confirm that adding the `update` `env` variable fixes the issue](https://github.com/jrfnl/bug-report-reproduction-scenarios/actions/runs/12395713307/job/34602078184#step:4:16).

The thing I find weird about it, is that the issue only occured with PHP 8.3, not with any of the other PHP versions ?

I very much appreciate that you are looking into the root cause of this, but yes, for my specific usecase, the update env will fix this.

**Comment by shivammathur** [comment]
ubuntu-24.04 has php 8.3.6 preinstalled.
https://packages.ubuntu.com/noble/php8.3

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/cdfde5ebec2b1d6902daaeee939e77a6560409ff. Will be in the next release.

**Comment by shivammathur** [comment]
Released in [`2.32.0`](https://github.com/shivammathur/setup-php/releases/tag/2.32.0).
